import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { SceneCache } from "../../src/domain/cache.js";
import { createWritableRoot, hashFile, linkOrCopy, resolveExistingContained } from "../../src/infrastructure/files.js";

const roots: string[] = [];
afterEach(async () => Promise.all(roots.splice(0).map((root) => fs.rm(root, { recursive: true, force: true }))));
async function setup() { const root = await fs.mkdtemp(path.join(os.tmpdir(), "renderer-security-")); roots.push(root); const cacheRoot = path.join(root, "cache"); const outside = path.join(root, "outside"); await fs.mkdir(outside); await fs.writeFile(path.join(outside, "sentinel"), "safe"); return { root, cacheRoot, outside, cache: new SceneCache(cacheRoot) }; }
async function video(root: string, name: string, content: string) { const file = path.join(root, name); await fs.writeFile(file, content); return { file, sha256: await hashFile(file), bytes: Buffer.byteLength(content) }; }

describe("cache and filesystem containment", () => {
  it.each(["output", "output/renderer", "output/renderer/scenes", "output/renderer/scenes/scene", "output/final", "output/renderer/temporary"])("rejects a symlinked writable component at %s and preserves the outside sentinel", async (component) => {
    const { root, outside } = await setup(); const workspace = path.join(root, "workspace"); await createWritableRoot(workspace); const source = path.join(workspace, "source"); await fs.writeFile(source, "video"); const link = path.join(workspace, component); await fs.mkdir(path.dirname(link), { recursive: true }); await fs.symlink(outside, link);
    const target = component === "output/final" ? path.join(workspace, component, "lesson.mp4") : component === "output/renderer/temporary" ? path.join(workspace, component, "temporary.mp4") : path.join(workspace, "output", "renderer", "scenes", "scene", "scene.mp4");
    await expect(linkOrCopy(workspace, source, target)).rejects.toMatchObject({ data: { code: "FILESYSTEM_BOUNDARY_VIOLATION" } });
    expect(await fs.readFile(path.join(outside, "sentinel"), "utf8")).toBe("safe");
  });
  it("rejects dangling and in-root symlinks as writable targets", async () => {
    const { root } = await setup(); const workspace = path.join(root, "workspace"); await createWritableRoot(workspace); const source = path.join(workspace, "source"); await fs.writeFile(source, "video"); await fs.mkdir(path.join(workspace, "safe")); await fs.symlink(path.join(workspace, "missing"), path.join(workspace, "dangling")); await fs.symlink(path.join(workspace, "safe"), path.join(workspace, "in-root"));
    await expect(linkOrCopy(workspace, source, path.join(workspace, "dangling", "scene.mp4"))).rejects.toMatchObject({ data: { code: "FILESYSTEM_BOUNDARY_VIOLATION" } });
    await expect(linkOrCopy(workspace, source, path.join(workspace, "in-root", "scene.mp4"))).rejects.toMatchObject({ data: { code: "FILESYSTEM_BOUNDARY_VIOLATION" } });
  });
  it("fails closed when a destination parent is replaced after staging", async () => {
    const { root, outside } = await setup(); const workspace = path.join(root, "workspace"); await createWritableRoot(workspace); const source = path.join(workspace, "source"); const parent = path.join(workspace, "output"); await fs.writeFile(source, "video"); await fs.mkdir(parent);
    await expect(linkOrCopy(workspace, source, path.join(parent, "scene.mp4"), { beforePromote: async () => { await fs.rename(parent, `${parent}.original`); await fs.symlink(outside, parent); } })).rejects.toMatchObject({ data: { code: "FILESYSTEM_BOUNDARY_VIOLATION" } });
    expect(await fs.readFile(path.join(outside, "sentinel"), "utf8")).toBe("safe"); await expect(fs.access(path.join(outside, "scene.mp4"))).rejects.toBeTruthy();
  });
  it("uses a safe hard link and copy fallback", async () => {
    const { root } = await setup(); const workspace = path.join(root, "workspace"); await createWritableRoot(workspace); const source = path.join(workspace, "source"); await fs.writeFile(source, "video"); const linked = path.join(workspace, "linked.mp4"); await linkOrCopy(workspace, source, linked); expect(await fs.readFile(linked, "utf8")).toBe("video"); const copied = path.join(workspace, "copied.mp4"); await linkOrCopy(workspace, source, copied, { linkFile: async () => { throw Object.assign(new Error("cross-device"), { code: "EXDEV" }); } }); expect(await fs.readFile(copied, "utf8")).toBe("video");
  });
  it.each(["../../outside", "/tmp/outside", "ABC", "a".repeat(63), "g".repeat(64)])("rejects an invalid public cache key: %s", async (cacheKey) => { const { cache } = await setup(); await expect(cache.inspect({ cacheKey })).rejects.toMatchObject({ data: { code: "INVALID_REQUEST" } }); await expect(cache.clean({ cacheKey })).rejects.toMatchObject({ data: { code: "INVALID_REQUEST" } }); });
  it.each(["../../outside", "/tmp/outside", "bad-hash"])("anchors a malicious manifest key to the discovered entry: %s", async (manifestKey) => {
    const { cacheRoot, outside, cache } = await setup(); const key = "a".repeat(64); const directory = path.join(cacheRoot, "scenes", "aa", key); await fs.mkdir(directory, { recursive: true }); await fs.writeFile(path.join(directory, "manifest.json"), JSON.stringify({ version: "1", cacheKey: manifestKey, sceneId: "scene", sha256: key, bytes: 1, createdAt: new Date().toISOString(), renderer: "svg-static.v1", representation: "static-segment" }));
    expect((await cache.inspect()).entries).toEqual([{ cacheKey: key, status: "corrupt", bytes: 0 }]); await cache.clean({ corruptOnly: true }); expect(await fs.readFile(path.join(outside, "sentinel"), "utf8")).toBe("safe"); await expect(fs.access(directory)).rejects.toBeTruthy();
  });
  it("does not traverse an in-cache symlink", async () => { const { cacheRoot, outside, cache } = await setup(); await fs.mkdir(path.join(cacheRoot, "scenes"), { recursive: true }); await fs.symlink(outside, path.join(cacheRoot, "scenes", "aa")); expect((await cache.inspect()).entries).toEqual([]); await cache.clean({ corruptOnly: true }); expect(await fs.readFile(path.join(outside, "sentinel"), "utf8")).toBe("safe"); });
  it("rejects existing input symlinks that escape their root and preserves in-root files", async () => { const { root, outside } = await setup(); const workspace = path.join(root, "workspace"); await fs.mkdir(workspace); await fs.writeFile(path.join(workspace, "safe"), "ok"); await fs.symlink(path.join(outside, "sentinel"), path.join(workspace, "escape")); expect(await resolveExistingContained(workspace, "safe")).toBe(path.join(workspace, "safe")); await expect(resolveExistingContained(workspace, "escape")).rejects.toMatchObject({ data: { code: "FILESYSTEM_BOUNDARY_VIOLATION" } }); });
  it.each(["staging-created", "video-staged", "manifest-staged", "previous-snapshotted", "commit-started", "video-installed", "manifest-installed"] as const)("recovers the prior valid pair after interruption at %s", async (faultStep) => { const { root, cacheRoot } = await setup(); const key = "b".repeat(64); const original = await video(root, "original.mp4", "original-video"); const initial = new SceneCache(cacheRoot); await initial.promote(key, original.file, "scene", original.sha256, original.bytes); const replacement = await video(root, "replacement.mp4", "replacement-video"); const interrupted = new SceneCache(cacheRoot, { leaveInterruptedTransaction: true, promotionStep: (step) => { if (step === faultStep) throw new Error(`crash:${step}`); } }); await expect(interrupted.promote(key, replacement.file, "scene", replacement.sha256, replacement.bytes)).rejects.toThrow(`crash:${faultStep}`); const lookup = await new SceneCache(cacheRoot).lookup(key); expect(lookup.status).toBe("hit"); expect(await fs.readFile(lookup.videoPath, "utf8")).toBe(faultStep === "manifest-installed" ? "replacement-video" : "original-video"); expect(lookup.manifest?.sha256).toBe(faultStep === "manifest-installed" ? replacement.sha256 : original.sha256); });
  it.each(["staging-created", "video-staged", "manifest-staged", "previous-snapshotted", "commit-started", "video-installed"] as const)("never exposes a false hit for an interrupted first promotion at %s", async (faultStep) => { const { root, cacheRoot } = await setup(); const key = "c".repeat(64); const candidate = await video(root, "candidate.mp4", "candidate-video"); const interrupted = new SceneCache(cacheRoot, { leaveInterruptedTransaction: true, promotionStep: (step) => { if (step === faultStep) throw new Error(`crash:${step}`); } }); await expect(interrupted.promote(key, candidate.file, "scene", candidate.sha256, candidate.bytes)).rejects.toThrow(); expect((await new SceneCache(cacheRoot).lookup(key)).status).not.toBe("hit"); });
  it("validates manifest bytes and renderer identity before a hit", async () => { const { root, cacheRoot, cache } = await setup(); const key = "d".repeat(64); const candidate = await video(root, "candidate.mp4", "candidate-video"); await cache.promote(key, candidate.file, "scene", candidate.sha256, candidate.bytes); const manifestPath = cache.paths(key).manifest; const manifest = JSON.parse(await fs.readFile(manifestPath, "utf8")) as Record<string, unknown>; await fs.writeFile(manifestPath, JSON.stringify({ ...manifest, bytes: candidate.bytes + 1 })); expect((await cache.lookup(key)).status).toBe("corrupt"); await fs.writeFile(manifestPath, JSON.stringify({ ...manifest, renderer: "other-renderer" })); expect((await cache.lookup(key)).status).toBe("corrupt"); });
  it("does not traverse a symlinked promotion transaction", async () => { const { cacheRoot, outside, cache } = await setup(); const key = "e".repeat(64); const paths = cache.paths(key); await fs.mkdir(paths.directory, { recursive: true }); await fs.symlink(outside, paths.transaction); expect((await cache.lookup(key)).status).toBe("corrupt"); await cache.clean({ corruptOnly: true }); expect(await fs.readFile(path.join(outside, "sentinel"), "utf8")).toBe("safe"); });
  it.each(["prefix", "entry", "transaction", "target"] as const)("rejects a symlinked cache %s during promotion and preserves the sentinel", async (location) => {
    const { root, cacheRoot, outside, cache } = await setup(); const key = "3".repeat(64); const paths = cache.paths(key); const candidate = await video(root, "candidate.mp4", "candidate-video"); await fs.mkdir(path.join(cacheRoot, "scenes"), { recursive: true });
    const link = location === "prefix" ? path.join(cacheRoot, "scenes", "33") : location === "entry" ? paths.directory : location === "transaction" ? paths.transaction : paths.video;
    await fs.mkdir(path.dirname(link), { recursive: true }); if (location === "target") await fs.symlink(path.join(outside, "sentinel"), link); else await fs.symlink(outside, link);
    await expect(cache.promote(key, candidate.file, "scene", candidate.sha256, candidate.bytes)).rejects.toMatchObject({ data: { code: "FILESYSTEM_BOUNDARY_VIOLATION" } }); expect(await fs.readFile(path.join(outside, "sentinel"), "utf8")).toBe("safe");
  });
  it("never removes an entry protected by a live lock, regardless of age", async () => { const { cacheRoot } = await setup(); const key = "f".repeat(64); const now = Date.now(); const cache = new SceneCache(cacheRoot, { now: () => now, processIsAlive: () => true }); const paths = cache.paths(key); await fs.mkdir(paths.directory, { recursive: true }); await fs.writeFile(paths.lock, JSON.stringify({ version: "1", pid: 42, token: "00000000-0000-4000-8000-000000000000", createdAt: new Date(now - 600_000).toISOString() })); await fs.utimes(paths.lock, new Date(now - 600_000), new Date(now - 600_000)); await expect(cache.acquire(key)).rejects.toMatchObject({ data: { code: "LOCK_ACQUISITION_FAILED" } }); expect((await cache.clean()).removedEntries).toBe(0); expect(await fs.access(paths.lock)).toBeUndefined(); });
  it("does not recover or clean a transaction owned by a live lock", async () => { const { cacheRoot } = await setup(); const key = "0".repeat(64); const cache = new SceneCache(cacheRoot, { processIsAlive: () => true }); const paths = cache.paths(key); await fs.mkdir(paths.transaction, { recursive: true }); await fs.writeFile(paths.stagedVideo, "in-progress"); await fs.writeFile(paths.lock, JSON.stringify({ version: "1", pid: 42, token: "00000000-0000-4000-8000-000000000000", createdAt: new Date().toISOString() })); expect((await cache.inspect()).entries).toEqual([{ cacheKey: key, status: "stale", bytes: 0 }]); expect((await cache.clean({ corruptOnly: true })).removedEntries).toBe(0); expect(await fs.readFile(paths.stagedVideo, "utf8")).toBe("in-progress"); });
  it("reclaims a validated stale lock only when its owner is dead", async () => { const { cacheRoot } = await setup(); const key = "1".repeat(64); const now = Date.now(); const cache = new SceneCache(cacheRoot, { now: () => now, processIsAlive: () => false }); const paths = cache.paths(key); await fs.mkdir(paths.directory, { recursive: true }); await fs.writeFile(paths.lock, JSON.stringify({ version: "1", pid: 42, token: "00000000-0000-4000-8000-000000000000", createdAt: new Date(now - 600_000).toISOString() })); await fs.utimes(paths.lock, new Date(now - 600_000), new Date(now - 600_000)); const release = await cache.acquire(key); await release(); await expect(fs.access(paths.lock)).rejects.toBeTruthy(); });
  it("maps ENOSPC during cache promotion without exposing a hit", async () => { const { root, cacheRoot } = await setup(); const key = "2".repeat(64); const candidate = await video(root, "candidate.mp4", "candidate-video"); const noSpace = Object.assign(new Error("no space"), { code: "ENOSPC" }); const cache = new SceneCache(cacheRoot, { promotionStep: (step) => { if (step === "video-staged") throw noSpace; } }); await expect(cache.promote(key, candidate.file, "scene", candidate.sha256, candidate.bytes)).rejects.toMatchObject({ data: { code: "INSUFFICIENT_DISK_SPACE" } }); expect((await cache.lookup(key)).status).not.toBe("hit"); });
});
