import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createEducationalRenderer } from "../../src/index.js";
import { EducationalRendererService } from "../../src/application/renderer.js";
import { SceneCache, type CacheLookup } from "../../src/domain/cache.js";
import { assertSufficientDiskSpace, writeJsonAtomic } from "../../src/infrastructure/files.js";
import { runProcess } from "../../src/infrastructure/process.js";

const roots: string[] = [];
const plan = { version: "1", lessonId: "validation", locale: "de", title: "Test", scenes: [{ id: "title", type: "title", durationMs: 1_000, localeSensitivity: "localized", title: "Test" }] } as const;
afterEach(async () => Promise.all(roots.splice(0).map((root) => fs.rm(root, { recursive: true, force: true }))));
async function setup() { const root = await fs.mkdtemp(path.join(os.tmpdir(), "renderer-api-")); roots.push(root); return { root, renderer: await createEducationalRenderer({ workspaceDirectory: root, cacheDirectory: path.join(root, "cache"), temporaryDirectory: path.join(root, "tmp") }) }; }
const invoke = (method: (...args: never[]) => unknown, receiver: object, value: unknown) => Reflect.apply(method, receiver, [value]) as Promise<unknown>;

describe("runtime public API validation", () => {
  it("maps strict validation failures to stable codes", async () => { const { renderer } = await setup(); const wrongVersion = await invoke(renderer.validate, renderer, { requestVersion: "2", visualPlan: plan, profile: "preview" }); expect(wrongVersion).toMatchObject({ resultVersion: "1", valid: false, errors: [{ code: "INVALID_REQUEST" }] }); const extra = await invoke(renderer.validate, renderer, { requestVersion: "1", visualPlan: plan, profile: "preview", extra: true }); expect(extra).toMatchObject({ errors: [{ code: "INVALID_REQUEST" }] }); const encoder = await invoke(renderer.validate, renderer, { requestVersion: "1", visualPlan: plan, profile: { name: "preview", encoder: "invalid" } }); expect(encoder).toMatchObject({ errors: [{ code: "INVALID_RENDER_PROFILE" }] }); expect(() => JSON.stringify(encoder)).not.toThrow(); });
  it("validates render, renderScene, and compose before using values", async () => { const { renderer } = await setup(); const rendered = await invoke(renderer.render, renderer, { requestVersion: "2", jobId: "validation", visualPlan: plan, profile: "preview", outputDirectory: "out" }); expect(rendered).toMatchObject({ status: "failed", errors: [{ code: "INVALID_REQUEST" }] }); await expect(invoke(renderer.renderScene, renderer, { requestVersion: "1", jobId: "validation", visualPlan: plan, profile: "preview", outputDirectory: "out", sceneId: "../bad" })).rejects.toMatchObject({ data: { code: "INVALID_REQUEST" } }); const composed = await invoke(renderer.compose, renderer, { requestVersion: "1", jobId: "validation", profile: "preview", outputDirectory: "out", scenePaths: [] }); expect(composed).toMatchObject({ resultVersion: "1", status: "failed", errors: [{ code: "INVALID_REQUEST" }] }); });
  it("validates benchmark and cache requests including versions and hashes", async () => { const { renderer } = await setup(); await expect(invoke(renderer.benchmark, renderer, { requestVersion: "2" })).rejects.toMatchObject({ data: { code: "INVALID_REQUEST" } }); await expect(invoke(renderer.inspectCache, renderer, { requestVersion: "1", cacheKey: "../../outside" })).rejects.toMatchObject({ data: { code: "INVALID_REQUEST" } }); await expect(invoke(renderer.cleanCache, renderer, { requestVersion: "1", cacheKey: "A".repeat(64) })).rejects.toMatchObject({ data: { code: "INVALID_REQUEST" } }); });
  it("rejects an output symlink without touching its target", async () => { const { root, renderer } = await setup(); const outside = path.join(root, "outside"); await fs.mkdir(outside); await fs.writeFile(path.join(outside, "sentinel"), "safe"); await fs.symlink(outside, path.join(root, "out")); const result = await renderer.render({ requestVersion: "1", jobId: "validation", visualPlan: plan, profile: "preview", outputDirectory: "out" }); expect(result.errors[0]?.code).toBe("FILESYSTEM_BOUNDARY_VIOLATION"); expect(await fs.readFile(path.join(outside, "sentinel"), "utf8")).toBe("safe"); });
  it("fails preflight before rendering and tolerates unavailable statfs", async () => { const { root } = await setup(); const renderer = await EducationalRendererService.create({ workspaceDirectory: root, cacheDirectory: path.join(root, "small-cache"), temporaryDirectory: path.join(root, "small-tmp") }, { statfs: async () => ({ bavail: 1, bsize: 1 }) }); const result = await renderer.render({ requestVersion: "1", jobId: "validation", visualPlan: plan, profile: "preview", outputDirectory: "small-output" }); expect(result).toMatchObject({ status: "failed", errors: [{ code: "INSUFFICIENT_DISK_SPACE" }] }); expect(() => JSON.stringify(result)).not.toThrow(); const unavailable = Object.assign(new Error("unsupported"), { code: "ENOSYS" }); await expect(assertSufficientDiskSpace(path.join(root, "unknown"), 100, async () => { throw unavailable; })).resolves.toEqual({ requiredBytes: 100 }); });
  it("maps process ENOSPC stderr to the stable disk-space code", async () => { await expect(runProcess(process.execPath, ["-e", "console.error('No space left on device'); process.exit(1)"])).rejects.toMatchObject({ data: { code: "INSUFFICIENT_DISK_SPACE" } }); });
  it("terminates an active controlled process with the interruption code", async () => { const controller = new AbortController(); const running = runProcess(process.execPath, ["-e", "setInterval(() => {}, 1000)"], { signal: controller.signal }); setTimeout(() => controller.abort(), 100); await expect(running).rejects.toMatchObject({ data: { code: "PROCESS_INTERRUPTED" } }); });
  it("returns the original disk error when result persistence fails", async () => { const { root } = await setup(); const cachedVideo = path.join(root, "cached.mp4"); await fs.writeFile(cachedVideo, "not-media"); class HitCache extends SceneCache { public override async lookup(key: string): Promise<CacheLookup> { return { status: "hit", videoPath: cachedVideo, manifest: { version: "1", cacheKey: key, sceneId: "title", sha256: "a".repeat(64), bytes: 9, createdAt: new Date().toISOString(), renderer: "svg-static.v2", representation: "static-segment" }, reason: "test-hit" }; } } const cache = new HitCache(path.join(root, "cache")); const renderer = await EducationalRendererService.create({ workspaceDirectory: root, cacheDirectory: path.join(root, "cache"), temporaryDirectory: path.join(root, "tmp-write") }, { cache, writeJson: async (filePath, value) => { if (filePath.endsWith("result.json")) throw Object.assign(new Error("write failed"), { code: "ENOSPC" }); await writeJsonAtomic(root, filePath, value); } }); const result = await renderer.render({ requestVersion: "1", jobId: "validation", visualPlan: plan, profile: "preview", outputDirectory: "write-output" }); expect(result.status).toBe("incomplete"); expect(result.errors.some((error) => error.code === "INSUFFICIENT_DISK_SPACE")).toBe(true); expect(() => JSON.stringify(result)).not.toThrow(); });
  it("sanitizes unknown persistence failures at the public boundary", async () => { const { root } = await setup(); const renderer = await EducationalRendererService.create({ workspaceDirectory: root, cacheDirectory: path.join(root, "cache-secret"), temporaryDirectory: path.join(root, "tmp-secret") }, { writeJson: async (filePath, value) => { if (filePath.endsWith("result.json")) throw new Error(`/secret/path --token hidden ${JSON.stringify(value)}`); await writeJsonAtomic(root, filePath, value); } }); const result = await renderer.render({ requestVersion: "1", jobId: "validation", visualPlan: plan, profile: "preview", outputDirectory: "secret-output" }); const serialized = JSON.stringify(result); expect(result.errors).toContainEqual({ code: "INTERNAL_ERROR", message: "An internal renderer failure occurred." }); expect(serialized).not.toContain("/secret/path"); expect(serialized).not.toContain("--token"); });
});
