import type { SdkV1OperationContract } from "../types.js";

export const lifecycleSdkV1Operations = {
  listProductionTemplates: {
    method: "GET",
    path: "/v1/workspaces/{workspace}/production-templates",
    successStatus: "200",
    responseSchema: "ProductionTemplatePage",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  createProductionTemplate: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/production-templates",
    successStatus: "201",
    responseSchema: "ProductionTemplateRecord",
    requestSchema: "ProductionTemplateCreateInput",
    requiredHeaders: [],
    problemResponses: true,
  },
  getProductionTemplate: {
    method: "GET",
    path: "/v1/workspaces/{workspace}/production-templates/{template}",
    successStatus: "200",
    responseSchema: "ProductionTemplateRecord",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  updateProductionTemplate: {
    method: "PATCH",
    path: "/v1/workspaces/{workspace}/production-templates/{template}",
    successStatus: "200",
    responseSchema: "ProductionTemplateRecord",
    requestSchema: "ProductionTemplateUpdateInput",
    requiredHeaders: ["IfMatch"],
    problemResponses: true,
  },
  listReusableAssets: {
    method: "GET",
    path: "/v1/workspaces/{workspace}/projects/{project}/reusable-assets",
    successStatus: "200",
    responseSchema: "ReusableAssetPage",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  cloneEpisode: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/projects/{project}/episodes/{episode}:clone",
    successStatus: "201",
    responseSchema: "EpisodeCloneResult",
    requestSchema: "EpisodeCloneInput",
    requiredHeaders: ["IdempotencyKey"],
    problemResponses: true,
  },
  attachEpisodeAssetReference: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/projects/{project}/episodes/{episode}/asset-references",
    successStatus: "201",
    responseSchema: "EpisodeAssetReferenceAttachResult",
    requestSchema: "EpisodeAssetReferenceAttachInput",
    requiredHeaders: [],
    problemResponses: true,
  },
  applyProductionTemplate: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/projects/{project}/episodes/{episode}/production-template:apply",
    successStatus: "200",
    responseSchema: "ProductionTemplateApplyResult",
    requestSchema: "ProductionTemplateApplyInput",
    requiredHeaders: [],
    problemResponses: true,
  },
  getEpisodeProductionTemplateBinding: {
    method: "GET",
    path: "/v1/workspaces/{workspace}/projects/{project}/episodes/{episode}/production-template-binding",
    successStatus: "200",
    responseSchema: "ProductionTemplateApplyResult",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
} satisfies Record<string, SdkV1OperationContract>;
