import type { SdkV1OperationContract } from "../types.js";

export const publicationPreparationSdkV1Operations = {
  listPublishingChannels: {
    method: "GET",
    path: "/v1/workspaces/{workspace}/publishing-channels",
    successStatus: "200",
    responseSchema: "PublishingChannelPage",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  getPublishingChannel: {
    method: "GET",
    path: "/v1/workspaces/{workspace}/publishing-channels/{channel}",
    successStatus: "200",
    responseSchema: "PublishingChannelRecord",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  beginChannelConnect: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/publishing-channels:connect",
    successStatus: "200",
    responseSchema: "ChannelConnectBeginResult",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  disconnectPublishingChannel: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/publishing-channels/{channel}:disconnect",
    successStatus: "200",
    responseSchema: "PublishingChannelRecord",
    requestSchema: null,
    requiredHeaders: ["IfMatch"],
    problemResponses: true,
  },
  evaluatePublicationPreflight: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/projects/{project}/episodes/{episode}/publication-intents:preflight",
    successStatus: "200",
    responseSchema: "PublicationPreflightResult",
    requestSchema: "PublicationPreflightInput",
    requiredHeaders: [],
    problemResponses: true,
  },
  preparePublicationIntent: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/projects/{project}/episodes/{episode}/publication-intents:prepare",
    successStatus: "201",
    responseSchema: "PublicationPrepareResult",
    requestSchema: "PublicationPrepareInput",
    requiredHeaders: ["IdempotencyKey"],
    problemResponses: true,
  },
  cancelPublicationIntent: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/projects/{project}/publications/{publication}:cancel",
    successStatus: "200",
    responseSchema: "Publication",
    requestSchema: null,
    requiredHeaders: ["IfMatch"],
    problemResponses: true,
  },
  updatePublicationSchedule: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/projects/{project}/publications/{publication}:updateSchedule",
    successStatus: "200",
    responseSchema: "PublicationScheduleUpdateResult",
    requestSchema: "PublicationScheduleUpdateInput",
    requiredHeaders: ["IfMatch"],
    problemResponses: true,
  },
} as const satisfies Readonly<Record<string, SdkV1OperationContract>>;
