import type { SdkV1OperationContract } from "../types.js";

export const webhookSdkV1Operations = {
  createWebhookEndpoint: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/webhook-endpoints",
    successStatus: "201",
    responseSchema: "WebhookEndpointCreateResult",
    requestSchema: "WebhookEndpointCreateInput",
    requiredHeaders: [],
    problemResponses: true,
  },
  listWebhookEndpoints: {
    method: "GET",
    path: "/v1/workspaces/{workspace}/webhook-endpoints",
    successStatus: "200",
    responseSchema: "WebhookEndpointPage",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  getWebhookEndpoint: {
    method: "GET",
    path: "/v1/workspaces/{workspace}/webhook-endpoints/{endpoint}",
    successStatus: "200",
    responseSchema: "WebhookEndpointRecord",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  updateWebhookEndpoint: {
    method: "PATCH",
    path: "/v1/workspaces/{workspace}/webhook-endpoints/{endpoint}",
    successStatus: "200",
    responseSchema: "WebhookEndpointRecord",
    requestSchema: "WebhookEndpointUpdateInput",
    requiredHeaders: ["IfMatch"],
    problemResponses: true,
  },
  rotateWebhookEndpointSecret: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/webhook-endpoints/{endpoint}:rotate-secret",
    successStatus: "200",
    responseSchema: "WebhookSecretRotateResult",
    requestSchema: "WebhookSecretRotateInput",
    requiredHeaders: ["IfMatch"],
    problemResponses: true,
  },
  testWebhookEndpoint: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/webhook-endpoints/{endpoint}:test",
    successStatus: "200",
    responseSchema: "WebhookTestResult",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  listWebhookDeliveries: {
    method: "GET",
    path: "/v1/workspaces/{workspace}/webhook-deliveries",
    successStatus: "200",
    responseSchema: "WebhookDeliveryPage",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  listWebhookDeliveryAttempts: {
    method: "GET",
    path: "/v1/workspaces/{workspace}/webhook-deliveries/{delivery}/attempts",
    successStatus: "200",
    responseSchema: "WebhookDeliveryAttemptPage",
    requestSchema: null,
    requiredHeaders: [],
    problemResponses: true,
  },
  resendWebhookDelivery: {
    method: "POST",
    path: "/v1/workspaces/{workspace}/webhook-deliveries/{delivery}:resend",
    successStatus: "201",
    responseSchema: "WebhookDeliveryRecord",
    requestSchema: null,
    requiredHeaders: ["IfMatch"],
    problemResponses: true,
  },
} as const satisfies Readonly<Record<string, SdkV1OperationContract>>;
