import { mkdtempSync } from "node:fs";
import fs from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { APPROVAL_SCHEMA_VERSION, TASK_SCHEMA_VERSION, WORKFLOW_SCHEMA_VERSION, approvalRecordSchema, taskDefinitionSchema, type ApprovalRecord } from "@mediaforge/domain";
import { createEpisodePathResolver } from "@mediaforge/shared";
import { persistStrategicItalianMedia } from "./strategic-italian-media-persistence.js";
import { strategicItalianQaPolicyHash, strategicItalianSha256 } from "./strategic-italian-qa.js";

const script = "Luca Bianchi presenta il piano di Milano.";
const scriptHash = strategicItalianSha256(script); const sourceHash = "c".repeat(64); const audio = Buffer.concat([Buffer.from("RIFF\u0000\u0000\u0000\u0000WAVE"), Buffer.from("supplied-audio")]);
const policy = { protectedTerms: ["Luca Bianchi", "Milano"], pronunciationTerms: ["Luca Bianchi"], requireItalianCta: true };
const metadata = { cta: { destination: "https://example.invalid/guida", label: "Leggi la guida", text: "Apri la guida completa." } };
function task(gate: "canonical-script" | "localization" | "voice" | "metadata", id: `${string}.${string}`) { return taskDefinitionSchema.parse({ schemaVersion: TASK_SCHEMA_VERSION, id, implementationVersion: "1.0.0", displayName: id, description: id, applicableProfiles: ["strategic-reinvention"], dependencies: [], inputs: [], outputs: [], executionKind: "manual-approval", policies: { cache: "fingerprint", retryLimit: 1, timeoutMs: 1000, lockScope: "task", approvalRequired: true, approval: { gate, highRisk: gate === "voice", requiredDistinctActors: gate === "voice" ? 2 : 1 }, batchable: false, provider: "none", estimatedCostClass: "none" }, cli: { resource: "task", command: id, examples: [id] }, observability: { operationName: id, redactedFields: [] } }); }
const taskDefinitions = { canonicalFull: task("canonical-script", "strategic.canonical.full"), canonicalShort: task("canonical-script", "strategic.canonical.short"), localizationFull: task("localization", "strategic.localization.full"), localizationShort: task("localization", "strategic.localization.short"), voice: task("voice", "strategic.voice"), metadata: task("metadata", "strategic.metadata") };
function approval(gate: "canonical-script" | "voice" | "metadata", inputs: string[], output: string, actor: string, id: string): ApprovalRecord {
  return approvalRecordSchema.parse({ schemaVersion: APPROVAL_SCHEMA_VERSION, id, workflowInstanceId: "instance-001", taskId: gate === "canonical-script" ? taskDefinitions.canonicalFull.id : gate === "voice" ? taskDefinitions.voice.id : taskDefinitions.metadata.id, profileId: "strategic-reinvention", unitId: "episode-001", locale: "it", variant: "full", decision: "approved", actor, reason: "Reviewed.", boundRevision: "revision-1", artifactHashes: [output], createdAt: "2026-07-01T00:00:00.000Z", expiresAt: "2027-01-01T00:00:00.000Z", scope: { gate, locale: "it", variant: "full", inputArtifactHashes: inputs, outputArtifactHashes: [output], highRisk: gate === "voice" } });
}
function payload(overrides: Record<string, unknown> = {}) {
  const audioHash = strategicItalianSha256(audio); const metadataHash = strategicItalianSha256(`${JSON.stringify(metadata, null, 2)}\n`);
  const approvals = [approval("canonical-script", [sourceHash], scriptHash, "canonical@example.invalid", "approval-canonical"), approval("voice", [scriptHash], audioHash, "voice-one@example.invalid", "approval-voice-one"), approval("voice", [scriptHash], audioHash, "voice-two@example.invalid", "approval-voice-two"), approval("metadata", [scriptHash, strategicItalianQaPolicyHash(policy)], metadataHash, "metadata@example.invalid", "approval-metadata")];
  const workflow = { route: "strategic-italian" as const, locale: "it" as const, canonicalFingerprint: scriptHash, italianCanonicalArtifact: { artifactId: "artifact:episode-001:it:full:narration:abc" as never, artifactType: "localized-story-package", owner: "narration", locale: "it" as const, format: "full" as const, provenance: "generated" as const, path: "it/full/script.md", fingerprint: scriptHash, schemaVersion: "v1", parents: [], sourceStageId: "stage:canonical" as never }, approvalLedger: approvals, workflowEvents: approvals.map((record, index) => ({ schemaVersion: WORKFLOW_SCHEMA_VERSION, eventId: `event-${index}`, workflowInstanceId: "instance-001", occurredAt: `2026-07-01T00:00:0${index}.000Z`, eventType: "approval-recorded" as const, approvalId: record.id, taskId: record.taskId, decision: record.decision, actor: record.actor, gate: record.scope?.gate, locale: "it" as const, variant: "full" as const })), workflowInstanceId: "instance-001", taskDefinitions, unitId: "episode-001", workflowRevision: "revision-1", canonicalInputHashes: [sourceHash], episodeBlueprint: { schemaVersion: "1.1", episodeId: "episode-001", genreId: "strategic-reinvention", creatorProfileId: "veronica-benini", canonicalLocale: "it", mode: "tactical-lesson", sources: ["source-001"], contentTier: "public", thesis: "A sufficiently specific strategic thesis.", beats: ["hook", "situation", "story", "reframe", "framework", "cta"].map((type, index) => ({ beatId: `beat-${index}`, type, purpose: "Reviewed strategic beat.", sourceIds: ["source-001"] })), cta: { kind: "free-resource", destination: "https://example.invalid/guide", campaignId: "campaign-001", localizedDestinations: { it: "https://example.invalid/guida" } }, requiredApprovalGates: ["canonical-script", "voice"] }, generatedArtifact: undefined };
  return { workflow, contentProfileId: "strategic-reinvention", creatorProfileId: "veronica-benini", artifact: { fingerprint: scriptHash, locale: "it", variant: "full", parents: [] }, script, captionsVtt: `WEBVTT\nX-MEDIAFORGE-LOCALE: it\nX-MEDIAFORGE-CANONICAL-SHA256: ${scriptHash}\nX-MEDIAFORGE-CHILD-SHA256: ${scriptHash}\n\n00:00.000 --> 00:01.000\n${script}`, suppliedAudio: audio, audioTrackManifest: {}, metadata, capabilityReport: {}, qaPolicy: policy, now: "2026-08-01T00:00:00.000Z", ...overrides } as never;
}
describe("strategic Italian media persistence", () => {
  it("writes only full internally-evidenced supplied-media artifacts with hashes", async () => {
    const root = mkdtempSync(path.join(tmpdir(), "strategic-it-")); const resolver = createEpisodePathResolver(root); const value = payload();
    await persistStrategicItalianMedia({ resolver, episodeId: "episode-001", payload: value });
    const context = { episodeId: "episode-001" as never, locale: "it" as never, variant: "full" as never };
    await expect(fs.readFile(resolver.audioNarration(context))).resolves.toEqual(audio);
    await expect(fs.readFile(resolver.metadataFile(context), "utf8")).resolves.toContain("guida");
    await expect(fs.readFile(resolver.capabilityReport(context, "italian-media"), "utf8")).resolves.toContain(scriptHash);
  });
  it("rejects self-asserted, changed, or missing approval evidence before writing", async () => {
    const root = mkdtempSync(path.join(tmpdir(), "strategic-it-")); const resolver = createEpisodePathResolver(root); const value = payload({ approved: true });
    await expect(persistStrategicItalianMedia({ resolver, episodeId: "episode-001", payload: { ...value, suppliedAudio: Buffer.concat([Buffer.from("RIFF\u0000\u0000\u0000\u0000WAVE"), Buffer.from("changed")]) } })).rejects.toThrow("creator voice");
    await expect(persistStrategicItalianMedia({ resolver, episodeId: "episode-001", payload: { ...value, workflow: { ...value.workflow, approvalLedger: [] } } })).rejects.toThrow();
    await expect(persistStrategicItalianMedia({ resolver, episodeId: "episode-001", payload: { ...value, captionsVtt: "WEBVTT\nX-MEDIAFORGE-LOCALE: it" } })).rejects.toThrow("WEBVTT");
    await expect(persistStrategicItalianMedia({ resolver, episodeId: "other-001", payload: value })).rejects.toThrow("exact Italian route");
    await expect(persistStrategicItalianMedia({ resolver, episodeId: "episode-001", payload: { ...value, workflow: { ...value.workflow, workflowEvents: value.workflow.workflowEvents.map((event: Record<string, unknown>) => ({ ...event, taskId: "wrong.task" })) } } })).rejects.toThrow();
    await expect(fs.stat(resolver.localeVariantRoot({ episodeId: "episode-001" as never, locale: "it" as never, variant: "full" as never }))).rejects.toThrow();
  });
  it("persists the six exact locale/variant coordinates only with their selected lineage", async () => {
    const coordinates = [["it", "full"], ["en", "full"], ["es", "full"], ["it", "short"], ["en", "short"], ["es", "short"]] as const;
    const root = mkdtempSync(path.join(tmpdir(), "strategic-six-")); const resolver = createEpisodePathResolver(root);
    for (const [locale, variant] of coordinates) {
      const base = payload(); const coordinateScript = locale === "it" && variant === "full" ? script : `${script} ${locale}-${variant}.`; const childHash = strategicItalianSha256(coordinateScript);
      const localeFullHash = strategicItalianSha256(`${script} ${locale}-full.`);
      const parents = locale === "it" && variant === "full" ? [] : variant === "full" ? [{ fingerprint: scriptHash, locale: "it" as const, variant: "full" as const }] : locale === "it" ? [{ fingerprint: scriptHash, locale: "it" as const, variant: "full" as const }] : [{ fingerprint: scriptHash, locale: "it" as const, variant: "full" as const }, { fingerprint: localeFullHash, locale, variant: "full" as const }];
      const gate = locale === "it" ? "canonical-script" : "localization";
      const taskId = gate === "canonical-script" ? (variant === "full" ? taskDefinitions.canonicalFull.id : taskDefinitions.canonicalShort.id) : (variant === "full" ? taskDefinitions.localizationFull.id : taskDefinitions.localizationShort.id);
      const inputs = locale === "it" && variant === "full" ? [sourceHash] : parents.map((parent) => parent.fingerprint);
      const release = approvalRecordSchema.parse({ schemaVersion: APPROVAL_SCHEMA_VERSION, id: `release-${locale}-${variant}`, workflowInstanceId: "instance-001", taskId, profileId: "strategic-reinvention", unitId: "episode-001", locale, variant, decision: "approved", actor: "release@example.invalid", reason: "Reviewed.", boundRevision: "revision-1", artifactHashes: [childHash], createdAt: "2026-07-01T00:00:04.000Z", scope: { gate, locale, variant, inputArtifactHashes: inputs, outputArtifactHashes: [childHash], highRisk: false } });
      const audioHash = strategicItalianSha256(audio); const metadataValue = { cta: { destination: `https://example.invalid/${locale}`, label: `Read ${locale}`, text: `Open ${locale} guide` } }; const metadataHash = strategicItalianSha256(`${JSON.stringify(metadataValue, null, 2)}\n`);
      const voice = approval("voice", [childHash], audioHash, "voice-one@example.invalid", `voice-one-${locale}-${variant}`); const voiceTwo = approval("voice", [childHash], audioHash, "voice-two@example.invalid", `voice-two-${locale}-${variant}`); const meta = approval("metadata", [childHash, strategicItalianQaPolicyHash(policy)], metadataHash, "metadata@example.invalid", `metadata-${locale}-${variant}`);
      const approvals = [base.workflow.approvalLedger[0], release, { ...voice, locale, variant, taskId: taskDefinitions.voice.id, scope: { ...voice.scope!, locale, variant } }, { ...voiceTwo, locale, variant, taskId: taskDefinitions.voice.id, scope: { ...voiceTwo.scope!, locale, variant } }, { ...meta, locale, variant, taskId: taskDefinitions.metadata.id, scope: { ...meta.scope!, locale, variant } }] as ApprovalRecord[];
      const workflow = { ...base.workflow, approvalLedger: approvals, workflowEvents: approvals.map((record, index) => ({ schemaVersion: WORKFLOW_SCHEMA_VERSION, eventId: `six-${locale}-${variant}-${index}`, workflowInstanceId: "instance-001", occurredAt: `2026-07-01T00:00:${String(index + 4).padStart(2, "0")}.000Z`, eventType: "approval-recorded" as const, approvalId: record.id, taskId: record.taskId, decision: record.decision, actor: record.actor, gate: record.scope?.gate, locale: record.locale, variant: record.variant })), episodeBlueprint: { ...base.workflow.episodeBlueprint, cta: { ...base.workflow.episodeBlueprint.cta, localizedDestinations: { it: "https://example.invalid/it", en: "https://example.invalid/en", es: "https://example.invalid/es" } } } };
      const value = { ...base, workflow, locale, variant, script: coordinateScript, artifact: { fingerprint: childHash, locale, variant, parents }, captionsVtt: `WEBVTT\nX-MEDIAFORGE-LOCALE: ${locale}\nX-MEDIAFORGE-CANONICAL-SHA256: ${scriptHash}\nX-MEDIAFORGE-CHILD-SHA256: ${childHash}\n\n00:00.000 --> 00:01.000\n${coordinateScript}`, metadata: metadataValue } as never;
      await persistStrategicItalianMedia({ resolver, episodeId: "episode-001", payload: value });
      await expect(fs.stat(resolver.metadataFile({ episodeId: "episode-001" as never, locale: locale as never, variant: variant as never }))).resolves.toBeDefined();
    }
  });
});
