export type {
  SdkV1OperationContract,
  SdkV1ObjectSchemaContract,
  SdkV1OperationOwner,
  SdkV1OperationModule,
} from "./v1-contract/types.js";
export {
  SDK_V1_OPERATIONS,
  SDK_V1_OPERATION_MODULES,
  SDK_V1_OPERATION_OWNERSHIP,
} from "./v1-contract/registry.js";

import type { SdkV1ObjectSchemaContract } from "./v1-contract/types.js";

/** Requiredness is part of the SDK type contract; changes require an SDK update. */
export const SDK_V1_OBJECT_SCHEMAS = {
  WorkspaceQuotaStatus: {
    required: [
      "workspaceId",
      "budgetLimitMinor",
      "reservedMinor",
      "settledMinor",
      "availableMinor",
      "revision",
    ],
    additionalProperties: false,
  },
  UsageRecord: {
    required: [
      "id",
      "kind",
      "subjectId",
      "operation",
      "unit",
      "quantityUnits",
      "costMinor",
      "correctionOfUsageId",
      "attemptId",
      "data",
      "occurredAt",
    ],
    additionalProperties: false,
  },
  UsageRecordPage: { required: ["items"], additionalProperties: false },
  AuditEvent: {
    required: [
      "id",
      "action",
      "subjectId",
      "actorId",
      "correlationId",
      "causationId",
      "data",
      "occurredAt",
    ],
    additionalProperties: false,
  },
  AuditEventPage: { required: ["items"], additionalProperties: false },
  ProjectInput: { required: ["name", "profile"], additionalProperties: false },
  Project: { required: ["id", "revision"], additionalProperties: false },
  DarkTruthContent: {
    required: [
      "type",
      "version",
      "premise",
      "storyBibleId",
      "referenceAssetIds",
    ],
    additionalProperties: false,
  },
  MathematicsEducationContent: {
    required: [
      "type",
      "version",
      "curriculumSourceId",
      "skillId",
      "grade",
      "difficulty",
      "presentationPresetId",
      "audioPresetId",
    ],
    additionalProperties: false,
  },
  HistoryContent: {
    required: [
      "type",
      "version",
      "topic",
      "presetId",
      "format",
      "audienceLevel",
    ],
    additionalProperties: false,
  },
  StrategicReinventionContent: {
    required: [
      "type",
      "version",
      "creatorProfileId",
      "episodeMode",
      "canonicalLocale",
      "sourceAssetIds",
    ],
    additionalProperties: false,
  },
  EpisodeInput: { required: ["content"], additionalProperties: false },
  EpisodeCreated: { required: ["id", "revision"], additionalProperties: false },
  Episode: {
    required: ["id", "revision", "content"],
    additionalProperties: false,
  },
  WorkflowAdmission: {
    required: [
      "template",
      "episodeRevision",
      "locales",
      "variants",
      "approvalMode",
      "publicationMode",
    ],
    additionalProperties: false,
  },
  ResourceLinks: {
    required: ["workflowRun", "job"],
    additionalProperties: false,
  },
  WorkflowCommandAccepted: {
    required: ["workflowRunId", "jobId", "revision", "links"],
    additionalProperties: false,
  },
  WorkflowRun: {
    required: ["id", "revision", "status"],
    additionalProperties: false,
  },
  WorkflowStep: { required: ["id", "status"], additionalProperties: false },
  WorkflowStepPage: { required: ["items"], additionalProperties: false },
  Job: {
    required: ["id", "revision", "status", "attempts", "cancellationRequested"],
    additionalProperties: false,
  },
  JobFailureProblem: {
    required: ["type", "title", "detail", "code", "retryable", "errors"],
    additionalProperties: false,
  },
  Asset: {
    required: ["id", "mimeType", "bytes", "sha256", "lifecycle", "provenance"],
    additionalProperties: false,
  },
  ValidationResult: {
    required: ["id", "createdAt"],
    additionalProperties: true,
  },
  ValidationPage: { required: ["items"], additionalProperties: false },
  PublicationArtifactBinding: {
    required: ["assetId", "role", "contentHash"],
    additionalProperties: false,
  },
  Publication: {
    required: [
      "id",
      "revision",
      "status",
      "workflowRunId",
      "approvalId",
      "approvalRevision",
      "approvalArtifactHash",
      "assetHash",
      "artifactBindings",
      "channelId",
      "visibility",
      "scheduledAt",
      "playlistIds",
      "createdAt",
      "updatedAt",
    ],
    additionalProperties: false,
  },
  ApprovalInput: {
    required: [
      "challengeId",
      "subjectId",
      "expectedRevision",
      "decision",
      "reason",
    ],
    additionalProperties: false,
  },
  ApprovalAccepted: {
    required: ["id", "jobId", "revision"],
    additionalProperties: false,
  },
  ApprovalRevocationInput: {
    required: ["reason"],
    additionalProperties: false,
  },
  ApprovalRevoked: {
    required: ["id", "revision", "state", "revokedAt"],
    additionalProperties: false,
  },
  ProblemError: { required: ["path", "message"], additionalProperties: false },
  Problem: {
    required: [
      "type",
      "title",
      "status",
      "detail",
      "code",
      "requestId",
      "retryable",
      "errors",
    ],
    additionalProperties: false,
  },
  HealthStatus: { required: ["status"], additionalProperties: false },
  OpenApiDocument: { required: [], additionalProperties: true },
} as const satisfies Readonly<Record<string, SdkV1ObjectSchemaContract>>;

export const SDK_V1_ENUMS = {
  "UsageRecord.kind": ["usage", "correction"],
  "ProjectInput.profile": [
    "dark_truth",
    "mathematics_education",
    "dynamic_generic",
    "history",
    "veronicabenini",
  ],
  "StrategicReinventionContent.episodeMode": [
    "story-to-strategy",
    "tactical-lesson",
    "position-essay",
    "myth-reality",
    "decision-framework",
    "case-diagnosis",
    "q-and-a",
    "guided-exercise",
  ],
  "MathematicsEducationContent.grade": [5, 6, 7, 8, 9, 10],
  "MathematicsEducationContent.difficulty": [
    "foundation",
    "standard",
    "challenge",
  ],
  "HistoryContent.presetId": [
    "military-campaign",
    "civilization-rise-fall",
    "historical-biography",
    "archaeology-mystery",
    "world-war-geopolitics",
    "royal-court-intrigue",
    "everyday-life",
    "disaster-pandemic-survival",
    "technology-trade-transformation",
    "dark-strange-history",
  ],
  "HistoryContent.format": ["short", "standard", "long"],
  "HistoryContent.audienceLevel": ["general", "enthusiast", "academic-lite"],
  "HistoryContent.period": [
    "prehistory",
    "ancient",
    "late antiquity",
    "medieval",
    "early modern",
    "industrial age",
    "modern",
    "contemporary history",
    "cross-period",
  ],
  "WorkflowAdmission.variants.items": ["full", "short"],
  "WorkflowAdmission.approvalMode": ["required", "automatic"],
  "WorkflowRun.status": [
    "queued",
    "running",
    "awaiting_approval",
    "succeeded",
    "failed",
    "cancelled",
  ],
  "Job.status": [
    "queued",
    "running",
    "waiting_for_approval",
    "retry_scheduled",
    "cancelling",
    "cancelled",
    "succeeded",
    "succeeded_with_warnings",
    "partially_succeeded",
    "failed",
    "dead_lettered",
  ],
  "JobFailureProblem.code": ["job_failed", "job_dead_lettered"],
  "Publication.status": [
    "pending",
    "executing",
    "published",
    "failed",
    "reconciliation_required",
    "cancelled",
  ],
  "Publication.visibility": ["private", "unlisted", "public"],
  "ApprovalInput.decision": ["approved", "rejected"],
  "HealthStatus.status": ["ok", "ready", "unavailable"],
} as const;

export const SDK_V1_CONSTS = {
  "DarkTruthContent.type": "dark_truth",
  "DarkTruthContent.version": "1",
  "MathematicsEducationContent.type": "mathematics_education",
  "MathematicsEducationContent.version": "1",
  "HistoryContent.type": "history",
  "HistoryContent.version": "1",
  "StrategicReinventionContent.type": "veronicabenini",
  "StrategicReinventionContent.version": "1",
  "StrategicReinventionContent.creatorProfileId": "veronica-benini",
  "StrategicReinventionContent.canonicalLocale": "it",
  "WorkflowAdmission.template": "episode-production",
  "WorkflowAdmission.publicationMode": "none",
  "ApprovalRevoked.state": "revoked",
} as const;
