import { z } from "zod";
import {
  aspectRatioSchema,
  durationRangeSchema,
  shotTreatmentIdSchema,
  visualNarrativePhaseSchema,
} from "../index.js";

const transitionPhaseSchema = z.enum([
  "hook",
  "setup",
  "evidence",
  "escalation",
  "climax",
  "callback",
  "aftermath",
]);

const treatmentCatalogCategorySchema = z.enum([
  "static-reframing",
  "camera-movement",
  "aspect-ratio-adaptation",
  "depth-and-motion",
  "horror-specific",
  "evidence-related",
  "transition",
]);
export type TreatmentCatalogCategory = z.infer<
  typeof treatmentCatalogCategorySchema
>;

const treatmentCatalogStatusSchema = z.enum([
  "supported",
  "later-phase",
  "unsupported",
]);
export type TreatmentCatalogStatus = z.infer<
  typeof treatmentCatalogStatusSchema
>;

const focalMetadataRequirementSchema = z.enum(["none", "optional", "required"]);
export type FocalMetadataRequirement = z.infer<
  typeof focalMetadataRequirementSchema
>;

const overlayAssetRequirementSchema = z.enum([
  "none",
  "local-overlay-asset",
  "external-overlay-asset",
]);
export type OverlayAssetRequirement = z.infer<
  typeof overlayAssetRequirementSchema
>;

const treatmentCompatibilityTagSchema = z.enum([
  "caption-safe",
  "face-sensitive",
  "evidence-readable",
  "fallback-only",
  "text-heavy-risk",
  "low-resolution-risk",
  "crowded-scene-risk",
  "perspective-distortion-risk",
  "overlay-heavy",
]);
export type TreatmentCompatibilityTag = z.infer<
  typeof treatmentCompatibilityTagSchema
>;

const treatmentCatalogEntrySchema = z.object({
  id: shotTreatmentIdSchema,
  label: z.string().min(1),
  category: treatmentCatalogCategorySchema,
  aspectRatios: z.array(aspectRatioSchema).min(1),
  phases: z.array(visualNarrativePhaseSchema).min(1),
  durationMs: durationRangeSchema,
  inlineRenderable: z.boolean(),
  derivedClipCacheRequired: z.boolean(),
  status: treatmentCatalogStatusSchema,
  availableByDefault: z.boolean(),
  focalMetadataRequirement: focalMetadataRequirementSchema,
  overlayAssetRequirement: overlayAssetRequirementSchema,
  compatibilityTags: z.array(treatmentCompatibilityTagSchema),
  incompatibleTreatmentIds: z.array(shotTreatmentIdSchema),
  frequencyCapRefs: z.array(z.string().min(1)),
});
type TreatmentCatalogEntryInput = z.input<typeof treatmentCatalogEntrySchema>;
type TreatmentCatalogEntry = z.output<typeof treatmentCatalogEntrySchema>;

export const shotTreatmentCatalogVersion = "shot-treatment-catalog-v1";

const allPhases: z.infer<typeof visualNarrativePhaseSchema>[] = [
  "hook",
  "setup",
  "evidence",
  "escalation",
  "climax",
  "callback",
  "aftermath",
];

function freezeEntry(entry: TreatmentCatalogEntry) {
  return Object.freeze({
    ...entry,
    aspectRatios: Object.freeze([...entry.aspectRatios]),
    phases: Object.freeze([...entry.phases]),
    compatibilityTags: Object.freeze([...entry.compatibilityTags]),
    incompatibleTreatmentIds: Object.freeze([...entry.incompatibleTreatmentIds]),
    frequencyCapRefs: Object.freeze([...entry.frequencyCapRefs]),
  });
}

function entry(
  value: TreatmentCatalogEntryInput,
) {
  return freezeEntry(treatmentCatalogEntrySchema.parse(value));
}

export type ReadonlyTreatmentCatalogEntry = ReturnType<typeof entry>;

export const shotTreatmentCatalog = Object.freeze([
  entry({
    id: "establishing-wide-crop",
    label: "Establishing wide crop",
    category: "static-reframing",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup", "callback"],
    durationMs: { minMs: 3000, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "medium-crop",
    label: "Medium crop",
    category: "static-reframing",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup", "evidence"],
    durationMs: { minMs: 2000, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: ["caption-safe"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "face-close-up",
    label: "Face close-up",
    category: "static-reframing",
    aspectRatios: ["16:9", "9:16"],
    phases: ["hook", "escalation", "climax"],
    durationMs: { minMs: 1500, maxMs: 4000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: ["face-sensitive", "low-resolution-risk"],
    incompatibleTreatmentIds: ["layered-pseudo-parallax"],
    frequencyCapRefs: [],
  }),
  entry({
    id: "object-detail-crop",
    label: "Object detail crop",
    category: "static-reframing",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence", "climax"],
    durationMs: { minMs: 1500, maxMs: 4000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: ["evidence-readable"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "rule-of-thirds-reposition",
    label: "Rule-of-thirds reposition",
    category: "static-reframing",
    aspectRatios: ["16:9", "9:16"],
    phases: allPhases,
    durationMs: { minMs: 2000, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "vertical-smart-crop",
    label: "Vertical smart crop",
    category: "static-reframing",
    aspectRatios: ["9:16"],
    phases: allPhases,
    durationMs: { minMs: 1500, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: ["caption-safe"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "caption-safe-negative-space-crop",
    label: "Caption-safe negative-space crop",
    category: "static-reframing",
    aspectRatios: ["16:9", "9:16"],
    phases: ["hook", "setup"],
    durationMs: { minMs: 2000, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: ["caption-safe"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "crop-toward-evidence",
    label: "Crop toward evidence",
    category: "evidence-related",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence", "climax"],
    durationMs: { minMs: 1500, maxMs: 4000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: ["evidence-readable"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "slow-push-in",
    label: "Slow push-in",
    category: "camera-movement",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup", "callback"],
    durationMs: { minMs: 3000, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "fast-push-in",
    label: "Fast push-in",
    category: "camera-movement",
    aspectRatios: ["16:9", "9:16"],
    phases: ["hook", "climax"],
    durationMs: { minMs: 1000, maxMs: 3000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: ["text-heavy-risk"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["fast-zoom-short-cap", "fast-zoom-per-minute"],
  }),
  entry({
    id: "slow-pull-out",
    label: "Slow pull-out",
    category: "camera-movement",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup", "aftermath"],
    durationMs: { minMs: 3000, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "lateral-pan",
    label: "Lateral pan",
    category: "camera-movement",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup", "evidence"],
    durationMs: { minMs: 3000, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["pan-direction-repeat-cap"],
  }),
  entry({
    id: "vertical-pan",
    label: "Vertical pan",
    category: "camera-movement",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence", "setup"],
    durationMs: { minMs: 3000, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["pan-direction-repeat-cap"],
  }),
  entry({
    id: "diagonal-pan",
    label: "Diagonal pan",
    category: "camera-movement",
    aspectRatios: ["16:9", "9:16"],
    phases: ["escalation"],
    durationMs: { minMs: 2000, maxMs: 5000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["pan-direction-repeat-cap"],
  }),
  entry({
    id: "pan-plus-zoom",
    label: "Pan plus zoom",
    category: "camera-movement",
    aspectRatios: ["16:9", "9:16"],
    phases: ["escalation", "climax"],
    durationMs: { minMs: 2000, maxMs: 5000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: ["text-heavy-risk"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["fast-zoom-short-cap", "fast-zoom-per-minute"],
  }),
  entry({
    id: "handheld-micro-drift",
    label: "Handheld micro-drift",
    category: "camera-movement",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup", "escalation"],
    durationMs: { minMs: 3000, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "subtle-rotation",
    label: "Subtle rotation",
    category: "camera-movement",
    aspectRatios: ["16:9", "9:16"],
    phases: ["escalation", "climax"],
    durationMs: { minMs: 1500, maxMs: 4000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: ["text-heavy-risk"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["rotation-per-20-seconds"],
  }),
  entry({
    id: "accelerated-climax-zoom",
    label: "Accelerated climax zoom",
    category: "camera-movement",
    aspectRatios: ["16:9", "9:16"],
    phases: ["climax"],
    durationMs: { minMs: 1000, maxMs: 2500 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: ["text-heavy-risk"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["fast-zoom-short-cap", "fast-zoom-per-minute"],
  }),
  entry({
    id: "smart-crop",
    label: "Smart crop",
    category: "aspect-ratio-adaptation",
    aspectRatios: ["16:9", "9:16"],
    phases: allPhases,
    durationMs: { minMs: 1500, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: ["caption-safe"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "pan-and-scan",
    label: "Pan-and-scan",
    category: "aspect-ratio-adaptation",
    aspectRatios: ["9:16"],
    phases: allPhases,
    durationMs: { minMs: 1500, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "blurred-fill",
    label: "Blurred background fill",
    category: "aspect-ratio-adaptation",
    aspectRatios: ["16:9", "9:16"],
    phases: allPhases,
    durationMs: { minMs: 1500, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: ["fallback-only", "overlay-heavy"],
    incompatibleTreatmentIds: ["split-framing", "security-camera-overlay"],
    frequencyCapRefs: ["blurred-fill-share"],
  }),
  entry({
    id: "mirrored-edge-fill",
    label: "Mirrored edge fill",
    category: "aspect-ratio-adaptation",
    aspectRatios: ["16:9", "9:16"],
    phases: allPhases,
    durationMs: { minMs: 1500, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: ["fallback-only"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "layered-foreground-background-fill",
    label: "Layered foreground/background fill",
    category: "aspect-ratio-adaptation",
    aspectRatios: ["16:9", "9:16"],
    phases: ["hook", "callback"],
    durationMs: { minMs: 2000, maxMs: 6000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "split-framing",
    label: "Split framing",
    category: "aspect-ratio-adaptation",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence"],
    durationMs: { minMs: 2000, maxMs: 5000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: ["overlay-heavy", "evidence-readable"],
    incompatibleTreatmentIds: ["blurred-fill", "security-camera-overlay"],
    frequencyCapRefs: [],
  }),
  entry({
    id: "subject-aware-repositioning",
    label: "Subject-aware repositioning",
    category: "aspect-ratio-adaptation",
    aspectRatios: ["16:9", "9:16"],
    phases: allPhases,
    durationMs: { minMs: 1500, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: ["caption-safe"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "separate-background-foreground-scaling",
    label: "Separate background/foreground scaling",
    category: "aspect-ratio-adaptation",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup", "callback"],
    durationMs: { minMs: 2000, maxMs: 6000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "layered-pseudo-parallax",
    label: "Layered pseudo-parallax",
    category: "depth-and-motion",
    aspectRatios: ["16:9", "9:16"],
    phases: ["hook", "callback", "climax"],
    durationMs: { minMs: 2000, maxMs: 6000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: [
      "face-sensitive",
      "low-resolution-risk",
      "crowded-scene-risk",
      "perspective-distortion-risk",
    ],
    incompatibleTreatmentIds: ["face-close-up"],
    frequencyCapRefs: ["parallax-per-video"],
  }),
  entry({
    id: "foreground-obstruction-movement",
    label: "Foreground obstruction movement",
    category: "depth-and-motion",
    aspectRatios: ["16:9", "9:16"],
    phases: ["escalation"],
    durationMs: { minMs: 1500, maxMs: 4000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "background-drift",
    label: "Background drift",
    category: "depth-and-motion",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup"],
    durationMs: { minMs: 3000, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "depth-based-zoom",
    label: "Depth-based zoom",
    category: "depth-and-motion",
    aspectRatios: ["16:9", "9:16"],
    phases: ["hook", "callback", "climax"],
    durationMs: { minMs: 2000, maxMs: 6000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: ["low-resolution-risk"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "simulated-rack-focus",
    label: "Simulated rack focus",
    category: "depth-and-motion",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence", "climax"],
    durationMs: { minMs: 1500, maxMs: 4000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "required",
    overlayAssetRequirement: "none",
    compatibilityTags: ["text-heavy-risk"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "focus-breathing",
    label: "Focus breathing",
    category: "depth-and-motion",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup", "escalation"],
    durationMs: { minMs: 3000, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "none",
    compatibilityTags: ["text-heavy-risk"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "vignette-drift",
    label: "Vignette drift",
    category: "depth-and-motion",
    aspectRatios: ["16:9", "9:16"],
    phases: allPhases,
    durationMs: { minMs: 1000, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "animated-shadow",
    label: "Animated shadow",
    category: "depth-and-motion",
    aspectRatios: ["16:9", "9:16"],
    phases: ["escalation"],
    durationMs: { minMs: 1500, maxMs: 4000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "light-sweep",
    label: "Light sweep",
    category: "depth-and-motion",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence"],
    durationMs: { minMs: 1500, maxMs: 4000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: ["evidence-readable"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "fog-or-grain-overlay",
    label: "Fog or grain overlay",
    category: "depth-and-motion",
    aspectRatios: ["16:9", "9:16"],
    phases: allPhases,
    durationMs: { minMs: 1000, maxMs: 8000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: ["overlay-heavy"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "security-camera-overlay",
    label: "Security-camera overlay",
    category: "horror-specific",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence", "escalation"],
    durationMs: { minMs: 2000, maxMs: 6000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: ["overlay-heavy"],
    incompatibleTreatmentIds: ["blurred-fill", "split-framing"],
    frequencyCapRefs: ["surveillance-glitch-static-combined-share"],
  }),
  entry({
    id: "recording-timestamp",
    label: "Recording timestamp",
    category: "evidence-related",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence"],
    durationMs: { minMs: 2000, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: ["evidence-readable"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "analogue-noise",
    label: "Analogue noise",
    category: "horror-specific",
    aspectRatios: ["16:9", "9:16"],
    phases: allPhases,
    durationMs: { minMs: 1000, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["surveillance-glitch-static-combined-share"],
  }),
  entry({
    id: "film-grain",
    label: "Film grain",
    category: "horror-specific",
    aspectRatios: ["16:9", "9:16"],
    phases: allPhases,
    durationMs: { minMs: 1000, maxMs: 8000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "exposure-flash",
    label: "Exposure flash",
    category: "horror-specific",
    aspectRatios: ["16:9", "9:16"],
    phases: ["hook", "climax"],
    durationMs: { minMs: 100, maxMs: 300 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["exposure-flash-short-cap", "exposure-flash-per-minute"],
  }),
  entry({
    id: "emergency-light-pulse",
    label: "Emergency-light pulse",
    category: "horror-specific",
    aspectRatios: ["16:9", "9:16"],
    phases: ["escalation", "climax"],
    durationMs: { minMs: 1000, maxMs: 4000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "fluorescent-flicker",
    label: "Fluorescent flicker",
    category: "horror-specific",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup", "escalation"],
    durationMs: { minMs: 1000, maxMs: 5000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "frame-skip",
    label: "Frame skip",
    category: "horror-specific",
    aspectRatios: ["16:9", "9:16"],
    phases: ["climax"],
    durationMs: { minMs: 200, maxMs: 1000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: ["text-heavy-risk"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["surveillance-glitch-static-combined-share"],
  }),
  entry({
    id: "chromatic-separation",
    label: "Chromatic separation",
    category: "horror-specific",
    aspectRatios: ["16:9", "9:16"],
    phases: ["climax"],
    durationMs: { minMs: 500, maxMs: 2000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: ["text-heavy-risk"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "short-blackout",
    label: "Short blackout",
    category: "transition",
    aspectRatios: ["16:9", "9:16"],
    phases: ["climax", "callback"],
    durationMs: { minMs: 100, maxMs: 500 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: ["blackout-short-cap", "blackout-per-intense-sequence"],
  }),
  entry({
    id: "static-burst",
    label: "Static burst",
    category: "horror-specific",
    aspectRatios: ["16:9", "9:16"],
    phases: ["climax"],
    durationMs: { minMs: 200, maxMs: 800 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: ["overlay-heavy", "text-heavy-risk"],
    incompatibleTreatmentIds: ["declassified-file-overlay", "audio-waveform-insert", "text-message-insert"],
    frequencyCapRefs: ["surveillance-glitch-static-combined-share"],
  }),
  entry({
    id: "damaged-film-frame",
    label: "Damaged-film frame",
    category: "evidence-related",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence"],
    durationMs: { minMs: 1000, maxMs: 4000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: ["evidence-readable"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "declassified-file-overlay",
    label: "Declassified-file overlay",
    category: "evidence-related",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence"],
    durationMs: { minMs: 2000, maxMs: 5000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: ["evidence-readable", "overlay-heavy"],
    incompatibleTreatmentIds: ["static-burst"],
    frequencyCapRefs: [],
  }),
  entry({
    id: "audio-waveform-insert",
    label: "Audio-waveform insert",
    category: "evidence-related",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence"],
    durationMs: { minMs: 2000, maxMs: 4000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: ["evidence-readable", "overlay-heavy"],
    incompatibleTreatmentIds: ["static-burst"],
    frequencyCapRefs: [],
  }),
  entry({
    id: "clock-close-up",
    label: "Clock close-up",
    category: "evidence-related",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence", "climax"],
    durationMs: { minMs: 1500, maxMs: 4000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "optional",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "handwritten-note-insert",
    label: "Handwritten-note insert",
    category: "evidence-related",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence", "callback"],
    durationMs: { minMs: 2000, maxMs: 5000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: ["evidence-readable", "overlay-heavy"],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "text-message-insert",
    label: "Text-message insert",
    category: "evidence-related",
    aspectRatios: ["16:9", "9:16"],
    phases: ["evidence"],
    durationMs: { minMs: 2000, maxMs: 4000 },
    inlineRenderable: false,
    derivedClipCacheRequired: true,
    status: "later-phase",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "local-overlay-asset",
    compatibilityTags: ["evidence-readable", "overlay-heavy"],
    incompatibleTreatmentIds: ["static-burst"],
    frequencyCapRefs: [],
  }),
  entry({
    id: "archive-photo-treatment",
    label: "Archive-photo treatment",
    category: "horror-specific",
    aspectRatios: ["16:9", "9:16"],
    phases: ["setup", "evidence"],
    durationMs: { minMs: 2000, maxMs: 6000 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: false,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
  entry({
    id: "short-dissolve",
    label: "Short dissolve",
    category: "transition",
    aspectRatios: ["16:9", "9:16"],
    phases: transitionPhaseSchema.options,
    durationMs: { minMs: 120, maxMs: 500 },
    inlineRenderable: true,
    derivedClipCacheRequired: false,
    status: "supported",
    availableByDefault: true,
    focalMetadataRequirement: "none",
    overlayAssetRequirement: "none",
    compatibilityTags: [],
    incompatibleTreatmentIds: [],
    frequencyCapRefs: [],
  }),
]) as readonly ReadonlyTreatmentCatalogEntry[];

const treatmentCatalogById = new Map<string, ReadonlyTreatmentCatalogEntry>(
  shotTreatmentCatalog.map((catalogEntry) => [catalogEntry.id, catalogEntry]),
);

export function getTreatment(
  id: string,
): ReadonlyTreatmentCatalogEntry | undefined {
  return treatmentCatalogById.get(id);
}

export function isTreatmentSupported(id: string): boolean {
  const treatment = getTreatment(id);
  return treatment !== undefined && treatment.status === "supported";
}

export function isTreatmentValidForAspectRatio(
  id: string,
  aspectRatio: z.infer<typeof aspectRatioSchema>,
): boolean {
  const treatment = getTreatment(id);
  return treatment?.aspectRatios.includes(aspectRatio) ?? false;
}

export function isTreatmentValidForPhase(
  id: string,
  phase: z.infer<typeof visualNarrativePhaseSchema>,
): boolean {
  const treatment = getTreatment(id);
  return treatment?.phases.includes(phase) ?? false;
}

export function isTreatmentValidForDuration(
  id: string,
  durationMs: number,
): boolean {
  const treatment = getTreatment(id);
  return (
    treatment !== undefined &&
    durationMs >= treatment.durationMs.minMs &&
    durationMs <= treatment.durationMs.maxMs
  );
}

export function areTreatmentsCompatible(ids: readonly string[]): boolean {
  const uniqueIds = new Set(ids);
  for (const id of uniqueIds) {
    const treatment = getTreatment(id);
    if (treatment === undefined) {
      return false;
    }
    for (const incompatibleId of treatment.incompatibleTreatmentIds) {
      if (uniqueIds.has(incompatibleId)) {
        return false;
      }
    }
  }
  return true;
}
