import { z } from "zod";

export const imageBatchManifestItemSchema = z.object({
  customId: z.string().min(1),
  episodeNumber: z.string().min(1),
  episodeSlug: z.string().min(1),
  language: z.literal("en"),
  format: z.literal("full"),
  sceneId: z.string().min(1),
  sceneIndex: z.number().int().nonnegative(),
  renderability: z
    .enum([
      "direct",
      "requiresInference",
      "mergeWithPrevious",
      "mergeWithNext",
      "skip",
    ])
    .optional(),
  reusedFromSceneId: z.string().min(1).optional(),
  promptHash: z.string().min(1),
  providerRequestHash: z.string().min(1),
  generationConfigurationHash: z.string().min(1),
  expectedOutputPath: z.string().min(1),
  characterIds: z.array(z.string().min(1)),
  characterReferenceHashes: z.array(z.string().min(1)),
  requestedSize: z.string().min(1),
  quality: z.string().min(1).optional(),
  outputFormat: z.enum(["png", "jpeg", "webp"]),
  status: z.enum([
    "planned",
    "submitted",
    "api-succeeded",
    "api-failed",
    "expired",
    "policy-rejected",
    "decode-failed",
    "validation-failed",
    "persisted",
    "skipped-cached",
    "retry-required",
  ]),
  imageHash: z.string().min(1).optional(),
  actualWidth: z.number().int().positive().optional(),
  actualHeight: z.number().int().positive().optional(),
  actualMimeType: z.string().min(1).optional(),
  actualByteSize: z.number().int().nonnegative().optional(),
  usage: z
    .object({
      inputTokens: z.number().int().nonnegative(),
      cachedInputTokens: z.number().int().nonnegative().optional(),
      outputTokens: z.number().int().nonnegative(),
    })
    .optional(),
  estimatedCostUsd: z.number().nonnegative().optional(),
  error: z
    .object({
      category: z.string().min(1),
      code: z.string().min(1).optional(),
      message: z.string().min(1),
    })
    .optional(),
});

export const imageBatchManifestSchema = z.object({
  schemaVersion: z.string().min(1),
  category: z.literal("image-generation"),
  localBatchId: z.string().min(1),
  rootLocalBatchId: z.string().min(1),
  parentLocalBatchId: z.string().min(1).optional(),
  retryNumber: z.number().int().nonnegative(),
  createdAt: z.string().min(1),
  updatedAt: z.string().min(1),
  endpoint: z.enum(["/v1/images/generations", "/v1/images/edits"]),
  model: z.string().min(1),
  completionWindow: z.literal("24h"),
  inputFilePath: z.string().min(1),
  inputFileHash: z.string().min(1),
  openAIInputFileId: z.string().min(1).optional(),
  openAIBatchId: z.string().min(1).optional(),
  outputFileId: z.string().min(1).optional(),
  errorFileId: z.string().min(1).optional(),
  status: z.enum([
    "prepared",
    "uploading",
    "submitted",
    "validating",
    "in_progress",
    "finalizing",
    "completed",
    "failed",
    "expired",
    "cancelling",
    "cancelled",
    "imported",
    "imported_with_failures",
  ]),
  items: z.array(imageBatchManifestItemSchema),
  resultFilePath: z.string().min(1).optional(),
  errorFilePath: z.string().min(1).optional(),
  reportFilePath: z.string().min(1).optional(),
  submittedAt: z.string().min(1).optional(),
  completedAt: z.string().min(1).optional(),
  importedAt: z.string().min(1).optional(),
});

export const sceneImageJobSchema = z.object({
  episodeNumber: z.string().min(1),
  episodeSlug: z.string().min(1),
  language: z.literal("en"),
  format: z.literal("full"),
  sceneId: z.string().min(1),
  sceneIndex: z.number().int().nonnegative(),
  renderability: z
    .enum([
      "direct",
      "requiresInference",
      "mergeWithPrevious",
      "mergeWithNext",
      "skip",
    ])
    .optional(),
  reusedFromSceneId: z.string().min(1).optional(),
  startTimeSeconds: z.number().nonnegative().optional(),
  endTimeSeconds: z.number().nonnegative().optional(),
  promptPath: z.string().min(1).optional(),
  positivePrompt: z.string().min(1),
  negativePrompt: z.string().min(1).optional(),
  characterIds: z.array(z.string().min(1)),
  characterReferencePaths: z.array(z.string().min(1)),
  model: z.string().min(1),
  quality: z.string().min(1),
  requestedSize: z.string().min(1),
  outputFormat: z.enum(["png", "jpeg", "webp"]),
  expectedOutputPath: z.string().min(1),
  promptHash: z.string().min(1),
  providerRequestHash: z.string().min(1),
  generationConfigurationHash: z.string().min(1),
});
