import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import * as rootExports from "@mediaforge/educational-renderer";
import * as contracts from "@mediaforge/educational-renderer/contracts";
import * as errors from "@mediaforge/educational-renderer/errors";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
function cli(args: readonly string[], cwd = packageRoot, signal?: "SIGINT" | "SIGTERM"): Promise<{ code: number | null; stdout: string; stderr: string }> { return new Promise((resolve, reject) => { const child = spawn(path.join(packageRoot, "bin", "educational-renderer.js"), args, { cwd, stdio: ["ignore", "pipe", "pipe"] }); if (signal) setTimeout(() => child.kill(signal), 1_500); let stdout = ""; let stderr = ""; child.stdout.on("data", (chunk: Buffer) => { stdout += chunk.toString(); }); child.stderr.on("data", (chunk: Buffer) => { stderr += chunk.toString(); }); child.on("error", reject); child.on("close", (code) => resolve({ code, stdout, stderr })); }); }

describe("built public package", () => {
  it("resolves the deliberately small root and public subpaths", () => { expect(Object.keys(rootExports)).toEqual(["createEducationalRenderer"]); expect(contracts.renderRequestSchema).toBeDefined(); expect(errors.RendererError).toBeDefined(); });
  it("invokes the executable installed package bin", async () => { const result = await cli(["--help"]); expect(result.code).toBe(0); expect(result.stderr).toBe(""); expect(result.stdout).toContain("Usage: educational-renderer"); });
  it("keeps JSON stdout parseable and stderr separate for command families", async () => { const workspace = await fs.mkdtemp(path.join(os.tmpdir(), "renderer-cli-")); try { const plan = { version: "1", lessonId: "cli", locale: "de", title: "CLI", scenes: [{ id: "title", type: "title", durationMs: 1_000, localeSensitivity: "localized", title: "CLI" }] }; await fs.writeFile(path.join(workspace, "plan.json"), JSON.stringify(plan)); const validate = await cli(["validate", "--plan", "plan.json", "--profile", "preview", "--json"], workspace); expect(validate.code).toBe(0); expect(validate.stderr).toBe(""); expect(JSON.parse(validate.stdout)).toMatchObject({ resultVersion: "1", valid: true }); const render = await cli(["render", "--plan", "plan.json", "--profile", "preview", "--output", "output", "--json"], workspace); expect(render.code, render.stderr).toBe(0); expect(render.stderr).toBe(""); expect(JSON.parse(render.stdout)).toMatchObject({ resultVersion: "1", status: "completed" }); const refused = await cli(["render", "--plan", "plan.json", "--profile", "preview", "--output", "output", "--json"], workspace); expect(refused.code).toBe(5); expect(refused.stderr).toBe(""); expect(JSON.parse(refused.stdout)).toMatchObject({ status: "failed", errors: [{ code: "OUTPUT_ALREADY_EXISTS" }] }); const overwritten = await cli(["render", "--plan", "plan.json", "--profile", "preview", "--output", "output", "--overwrite", "--json"], workspace); expect(overwritten.code, overwritten.stderr).toBe(0); const inspect = await cli(["inspect", "--json"], workspace); expect(JSON.parse(inspect.stdout)).toMatchObject({ resultVersion: "1" }); const cache = await cli(["cache", "inspect", "--json"], workspace); expect(JSON.parse(cache.stdout)).toMatchObject({ resultVersion: "1" }); const invalid = await cli(["benchmark"], workspace); expect(invalid.code).not.toBe(0); expect(invalid.stdout).toBe(""); expect(invalid.stderr).toContain("required option"); } finally { await fs.rm(workspace, { recursive: true, force: true }); } });
  it("returns stable invalid-input exits for formulas, profiles, plans, and options", async () => { const workspace = await fs.mkdtemp(path.join(os.tmpdir(), "renderer-cli-invalid-")); try { const invalidFormula = { version: "1", lessonId: "invalid", locale: "de", title: "Invalid", scenes: [{ id: "equation", type: "equation", durationMs: 1_000, localeSensitivity: "language-neutral", equation: "\\notacommand{" }] }; await fs.writeFile(path.join(workspace, "invalid.json"), JSON.stringify(invalidFormula)); const formula = await cli(["validate", "--plan", "invalid.json", "--profile", "preview", "--json"], workspace); expect(formula.code).toBe(3); expect(formula.stderr).toBe(""); expect(JSON.parse(formula.stdout)).toMatchObject({ valid: false, errors: [{ code: "INVALID_FORMULA" }] }); const profile = await cli(["validate", "--plan", "invalid.json", "--profile", "bad"], workspace); expect(profile.code).toBe(3); expect(profile.stdout).toBe(""); expect(profile.stderr).toContain("INVALID_RENDER_PROFILE"); await fs.writeFile(path.join(workspace, "broken.json"), "{"); const broken = await cli(["validate", "--plan", "broken.json", "--profile", "preview"], workspace); expect(broken.code).toBe(3); expect(broken.stderr).toContain("INVALID_VISUAL_PLAN"); const option = await cli(["inspect", "--unknown"], workspace); expect(option.code).not.toBe(0); expect(option.stdout).toBe(""); expect(option.stderr).toContain("unknown option"); } finally { await fs.rm(workspace, { recursive: true, force: true }); } });
  it.each(["SIGINT", "SIGTERM"] as const)("returns 130 and one JSON result on %s", async (signal) => { const workspace = await fs.mkdtemp(path.join(os.tmpdir(), "renderer-signal-")); try { const plan = { version: "1", lessonId: "signal", locale: "de", title: "Signal", scenes: [{ id: "title", type: "title", durationMs: 300_000, localeSensitivity: "localized", title: "Signal" }] }; await fs.writeFile(path.join(workspace, "plan.json"), JSON.stringify(plan)); const result = await cli(["render", "--plan", "plan.json", "--profile", "youtube-full", "--output", "output", "--json"], workspace, signal); expect(result.code).toBe(130); expect(result.stderr).toBe(""); const document = JSON.parse(result.stdout) as { resultVersion: string; status: string; scenes: Array<{ status: string; errors: Array<{ code: string }> }> }; expect(document).toMatchObject({ resultVersion: "1", status: "cancelled" }); for (const scene of document.scenes) { expect(["completed", "cancelled"]).toContain(scene.status); if (scene.status === "cancelled") expect(scene.errors).toContainEqual(expect.objectContaining({ code: "PROCESS_INTERRUPTED" })); } } finally { await fs.rm(workspace, { recursive: true, force: true }); } });
});
