import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createEducationalRenderer } from "../../src/index.js";
import { EducationalRendererService } from "../../src/application/renderer.js";
import type { RenderRequest, RendererEvent } from "../../src/contracts.js";
import { SceneCache } from "../../src/domain/cache.js";
import { runProcess } from "../../src/infrastructure/process.js";

const roots: string[] = [];
async function setup() { const root = await fs.mkdtemp(path.join(os.tmpdir(), "educational-renderer-test-")); roots.push(root); return { root, renderer: await createEducationalRenderer({ workspaceDirectory: root, cacheDirectory: path.join(root, "cache"), temporaryDirectory: path.join(root, "tmp") }) }; }
const request = (root: string): RenderRequest => ({ requestVersion: "1", jobId: "integration", profile: "preview", outputDirectory: path.join(root, "output"), execution: { overwrite: true }, visualPlan: { version: "1", lessonId: "integration", locale: "de", title: "Test", scenes: [{ id: "title", type: "title", durationMs: 1_000, localeSensitivity: "localized", title: "Gleichungen", subtitle: "Ein Test" }, { id: "answer", type: "equation", durationMs: 1_000, localeSensitivity: "language-neutral", equation: "x=3" }] } });
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => fs.rm(root, { recursive: true, force: true }))); });
describe("real Linux rendering", () => {
  it("renders, verifies, emits ordered events, and reuses scene cache", async () => {
    const { root, renderer } = await setup(); const events: RendererEvent[] = []; const cold = await renderer.render(request(root), { onEvent: (event) => events.push(event) }); expect(cold.status, JSON.stringify(cold.errors)).toBe("completed"); expect(cold.output?.width).toBe(960); expect(cold.output?.frameRate).toBe(15); expect(await fs.stat(cold.output!.videoPath)).toBeTruthy(); expect(events[0]?.type).toBe("job-started"); expect(events.at(-1)?.type).toBe("job-completed");
    const warm = await renderer.render(request(root)); expect(warm.cache.hits).toBe(2); expect(warm.scenes.every((scene) => scene.cacheStatus === "hit")).toBe(true);
  });
  it("renders animated chalk equation scenes without changing static defaults", async () => {
    const { root, renderer } = await setup();
    const animated = await renderer.render({ requestVersion: "1", jobId: "chalk", profile: "preview", outputDirectory: path.join(root, "chalk-output"), execution: { overwrite: true }, visualPlan: { version: "1", lessonId: "chalk", locale: "de", title: "Chalk", scenes: [{ id: "equation", type: "equation", durationMs: 1_600, localeSensitivity: "language-neutral", equation: "x=3", animation: { mode: "chalk-write" } }] } });
    expect(animated.status, JSON.stringify(animated.errors)).toBe("completed");
    expect(animated.output?.videoCodec).toBe("h264");
    const warm = await renderer.render({ requestVersion: "1", jobId: "chalk", profile: "preview", outputDirectory: path.join(root, "chalk-output-2"), execution: { overwrite: true }, visualPlan: { version: "1", lessonId: "chalk", locale: "de", title: "Chalk", scenes: [{ id: "equation", type: "equation", durationMs: 1_600, localeSensitivity: "language-neutral", equation: "x=3", animation: { mode: "chalk-write" } }] } });
    expect(warm.scenes[0]?.cacheStatus).toBe("hit");
  });
  it("invalidates only a changed scene and recovers corrupt cache", async () => {
    const { root, renderer } = await setup(); const initial = await renderer.render(request(root)); const changed = request(root); changed.visualPlan.scenes[1] = { ...changed.visualPlan.scenes[1]!, equation: "x=4" }; const result = await renderer.render(changed); expect(result.cache.hits).toBe(1); expect(result.cache.misses).toBe(1); const cached = result.scenes[0]!; const inspection = await renderer.inspectCache({ requestVersion: "1", cacheKey: cached.cacheKey }); expect(inspection.entries[0]?.status).toBe("hit"); await fs.writeFile(cached.outputPath!, "corrupt"); const recovered = await renderer.render(changed); expect(recovered.scenes[0]?.cacheStatus).toBe("corrupt"); expect(recovered.status, JSON.stringify(recovered.errors)).toBe("completed"); expect(initial.scenes).toHaveLength(2);
  });
  it("recomposes audio and subtitles without rerendering visuals", async () => {
    const { root, renderer } = await setup(); const rendered = await renderer.render(request(root)); const scenePaths = rendered.scenes.map((scene) => scene.outputPath!); const mtimes = await Promise.all(scenePaths.map(async (item) => (await fs.stat(item)).mtimeMs)); const audio = path.join(root, "tone.wav"); const subtitles = path.join(root, "captions.vtt"); await runProcess("ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i", "anullsrc=r=48000:cl=mono", "-t", "2", audio]); await fs.writeFile(subtitles, "WEBVTT\n\n00:00:00.000 --> 00:00:01.500\nTest\n"); const composed = await renderer.compose({ requestVersion: "1", jobId: "audio-only", profile: "preview", outputDirectory: path.join(root, "audio-output"), scenePaths, audio: { path: audio, volume: .8 }, subtitles: { path: subtitles, mode: "embedded" } }); expect(composed.status).toBe("completed"); expect(composed.output?.audioCodec).toBe("aac"); expect(await Promise.all(scenePaths.map(async (item) => (await fs.stat(item)).mtimeMs))).toEqual(mtimes);
  });
  it("uses workspace-relative resolved paths and rejects input symlink escapes", async () => { const container = await fs.mkdtemp(path.join(os.tmpdir(), "renderer-paths-")); roots.push(container); const workspace = path.join(container, "workspace"); const outside = path.join(container, "outside"); await fs.mkdir(workspace); await fs.mkdir(outside); await fs.writeFile(path.join(outside, "sentinel"), "safe"); const renderer = await createEducationalRenderer({ workspaceDirectory: workspace, cacheDirectory: path.join(workspace, "cache"), temporaryDirectory: path.join(workspace, "tmp") }); const rendered = await renderer.render(request(workspace)); expect(rendered.status).toBe("completed"); const scenePath = rendered.scenes[0]?.outputPath; expect(scenePath).toBeDefined(); const relativeScene = path.relative(workspace, scenePath!); const relativeCompose = await renderer.compose({ requestVersion: "1", jobId: "relative", profile: "preview", outputDirectory: "relative-output", scenePaths: [relativeScene] }); expect(relativeCompose.status).toBe("completed"); const outsideScene = path.join(outside, "scene.mp4"); await fs.copyFile(scenePath!, outsideScene); await fs.symlink(outsideScene, path.join(workspace, "scene-escape.mp4")); const sceneEscape = await renderer.compose({ requestVersion: "1", jobId: "scene-escape", profile: "preview", outputDirectory: "scene-escape-output", scenePaths: ["scene-escape.mp4"] }); expect(sceneEscape.errors[0]?.code).toBe("FILESYSTEM_BOUNDARY_VIOLATION"); const audioOutside = path.join(outside, "tone.wav"); await runProcess("ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i", "anullsrc=r=48000:cl=mono", "-t", "1", audioOutside]); await fs.symlink(audioOutside, path.join(workspace, "audio-escape.wav")); const audioEscape = await renderer.compose({ requestVersion: "1", jobId: "audio-escape", profile: "preview", outputDirectory: "audio-escape-output", scenePaths: [relativeScene], audio: { path: "audio-escape.wav", volume: 1 } }); expect(audioEscape.errors[0]?.code).toBe("FILESYSTEM_BOUNDARY_VIOLATION"); const subtitleOutside = path.join(outside, "captions.vtt"); await fs.writeFile(subtitleOutside, "WEBVTT\n"); await fs.symlink(subtitleOutside, path.join(workspace, "subtitle-escape.vtt")); const subtitleEscape = await renderer.compose({ requestVersion: "1", jobId: "subtitle-escape", profile: "preview", outputDirectory: "subtitle-escape-output", scenePaths: [relativeScene], subtitles: { path: "subtitle-escape.vtt", mode: "embedded" } }); expect(subtitleEscape.errors[0]?.code).toBe("FILESYSTEM_BOUNDARY_VIOLATION"); await fs.symlink(outside, path.join(workspace, "fixture-escape")); await expect(renderer.benchmark({ requestVersion: "1", fixtureDirectory: "fixture-escape", profiles: ["preview"], outputDirectory: "benchmark-output" })).rejects.toMatchObject({ data: { code: "FILESYSTEM_BOUNDARY_VIOLATION" } }); expect(await fs.readFile(path.join(outside, "sentinel"), "utf8")).toBe("safe"); });
  it("fails composition preflight on the final target filesystem", async () => { const { root, renderer } = await setup(); const rendered = await renderer.render(request(root)); const lowDisk = await EducationalRendererService.create({ workspaceDirectory: root, cacheDirectory: path.join(root, "low-cache"), temporaryDirectory: path.join(root, "low-tmp") }, { statfs: async () => ({ bavail: 1, bsize: 1 }) }); const result = await lowDisk.compose({ requestVersion: "1", jobId: "low-disk", profile: "preview", outputDirectory: "low-output", scenePaths: rendered.scenes.flatMap((scene) => scene.outputPath ? [scene.outputPath] : []) }); expect(result).toMatchObject({ status: "failed", errors: [{ code: "INSUFFICIENT_DISK_SPACE" }] }); });
  it("preserves the first promoted scene and resumes in canonical order", async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), "renderer-resume-")); roots.push(root); let staged = 0; const cacheRoot = path.join(root, "cache"); const cache = new SceneCache(cacheRoot, { promotionStep: (step) => { if (step === "video-staged" && ++staged === 2) throw new Error("injected second-scene failure"); } }); const interrupted = await EducationalRendererService.create({ workspaceDirectory: root, cacheDirectory: cacheRoot, temporaryDirectory: path.join(root, "tmp") }, { cache }); const first = await interrupted.render(request(root)); expect(first.status).toBe("incomplete"); expect(first.scenes.map((scene) => scene.sceneId)).toEqual(["title", "answer"]); expect(first.scenes[0]?.status).toBe("completed"); expect(first.scenes[1]?.status).toBe("failed"); const resumed = await (await createEducationalRenderer({ workspaceDirectory: root, cacheDirectory: cacheRoot, temporaryDirectory: path.join(root, "tmp-resume") })).render(request(root)); expect(resumed.status).toBe("completed"); expect(resumed.scenes.map((scene) => scene.sceneId)).toEqual(["title", "answer"]); expect(resumed.scenes.map((scene) => scene.cacheStatus)).toEqual(["hit", "miss"]); });
  it("keys and renders the actual configured font", async () => { const { root } = await setup(); const cacheDirectory = path.join(root, "font-cache"); const sans = await createEducationalRenderer({ workspaceDirectory: root, cacheDirectory, temporaryDirectory: path.join(root, "sans-tmp"), fontFile: "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf" }); const sansResult = await sans.render({ ...request(root), outputDirectory: path.join(root, "sans-output") }); const serif = await createEducationalRenderer({ workspaceDirectory: root, cacheDirectory, temporaryDirectory: path.join(root, "serif-tmp"), fontFile: "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf" }); const serifResult = await serif.render({ ...request(root), outputDirectory: path.join(root, "serif-output") }); expect(serifResult.status).toBe("completed"); expect(serifResult.scenes.map((scene) => scene.cacheStatus)).toEqual(["miss", "miss"]); expect(serifResult.scenes.map((scene) => scene.cacheKey)).not.toEqual(sansResult.scenes.map((scene) => scene.cacheKey)); });
  it("rejects symlinked cache and temporary roots", async () => { const container = await fs.mkdtemp(path.join(os.tmpdir(), "renderer-roots-")); roots.push(container); const workspace = path.join(container, "workspace"); const outside = path.join(container, "outside"); await fs.mkdir(workspace); await fs.mkdir(outside); await fs.symlink(outside, path.join(container, "cache-link")); await fs.symlink(outside, path.join(container, "tmp-link")); await expect(createEducationalRenderer({ workspaceDirectory: workspace, cacheDirectory: path.join(container, "cache-link"), temporaryDirectory: path.join(container, "safe-tmp") })).rejects.toMatchObject({ data: { code: "FILESYSTEM_BOUNDARY_VIOLATION" } }); await expect(createEducationalRenderer({ workspaceDirectory: workspace, cacheDirectory: path.join(container, "safe-cache"), temporaryDirectory: path.join(container, "tmp-link") })).rejects.toMatchObject({ data: { code: "FILESYSTEM_BOUNDARY_VIOLATION" } }); });
});
