import type {
  ViewerVisibleHookFingerprint,
  VisualEventKind,
  VisualStrategy,
} from "./positioning-visual-contracts.js";

export interface OpeningTreatmentProfile
  extends Omit<ViewerVisibleHookFingerprint, "lightingArchetype"> {
  readonly strategyFamily: VisualStrategy;
  readonly lighting: string;
  readonly props: readonly [string, ...string[]];
  readonly motionOpportunities: readonly [VisualEventKind, VisualEventKind, ...VisualEventKind[]];
}

const OPENING_TREATMENTS: Readonly<Record<string, OpeningTreatmentProfile>> = {
  L01: {
    strategyFamily: "client-decision",
    subjectArchetype: "client choosing between two credible professionals",
    environmentArchetype: "consultation decision table with both candidates visible",
    compositionArchetype: "over-shoulder decision triangle with evidence weighted toward the winner",
    cameraArchetype: "50mm seated client eye-line documentary",
    actionArchetype: "client reaches toward the clearer evidence while the stronger craft remains overlooked",
    dominantObjectArchetype: "two contrasting unlabeled portfolios",
    motionArchetype: "choice-reveal then evidence punch-in",
    lighting: "neutral client-room daylight with selective evidence contrast",
    props: ["two contrasting unlabeled portfolios", "selection token"],
    motionOpportunities: ["establishing-crop", "split-composition", "subject-detail", "punch-in"],
  },
  L02: {
    strategyFamily: "market-crowd",
    subjectArchetype: "undifferentiated crowd with one relevant audience cluster",
    environmentArchetype: "large public concourse crossed by broad and precise signal paths",
    compositionArchetype: "wide diffusion field resolving into one isolated cluster",
    cameraArchetype: "24mm elevated architectural wide",
    actionArchetype: "broad signal disperses while a narrow beam reaches its intended group",
    dominantObjectArchetype: "broad glow field and focused signal beam",
    motionArchetype: "diffusion sweep into focal isolation",
    lighting: "high-key concourse light with one precise colored beam",
    props: ["broad glow field and focused signal beam", "cluster markers"],
    motionOpportunities: ["pan", "highlighted-region", "slow-push", "transition-state"],
  },
  L03: {
    strategyFamily: "transformation",
    subjectArchetype: "professional entering a new role while observers retain the prior identity",
    environmentArchetype: "threshold connecting former workplace and unfamiliar expert stage",
    compositionArchetype: "lateral threshold frame with subject ahead and recognition lagging behind",
    cameraArchetype: "32mm lateral tracking profile",
    actionArchetype: "professional crosses the role threshold while audience gaze stays on the old position",
    dominantObjectArchetype: "old-role silhouette and empty expert podium",
    motionArchetype: "threshold crossing with delayed background reveal",
    lighting: "cool former-role light transitioning to warm stage light",
    props: ["old-role silhouette and empty expert podium", "new proof toolkit"],
    motionOpportunities: ["pan", "subject-detail", "reveal", "transition-state"],
  },
  L04: {
    strategyFamily: "content-ecosystem",
    subjectArchetype: "disconnected media fragments resolving around one recognizable source",
    environmentArchetype: "editorial production wall spanning recording publishing and social formats",
    compositionArchetype: "fragmented collage reorganizing into a coherent radial topic cluster",
    cameraArchetype: "30mm overhead-to-oblique editorial move",
    actionArchetype: "scattered media pieces lock into one recurring knowledge system",
    dominantObjectArchetype: "mixed media fragments around a central source artifact",
    motionArchetype: "collage assembly into radial system",
    lighting: "even editorial work light with central-source emphasis",
    props: ["mixed media fragments around a central source artifact", "format-specific production objects"],
    motionOpportunities: ["establishing-crop", "diagram-build", "pan", "highlighted-region"],
  },
  L05: {
    strategyFamily: "product-object-still-life",
    subjectArchetype: "scattered expertise consolidating into a durable authority artifact",
    environmentArchetype: "working bindery table with manuscript and finished volume states",
    compositionArchetype: "exploded knowledge field converging diagonally into one bound object",
    cameraArchetype: "55mm overhead copy-stand with shallow object relief",
    actionArchetype: "loose pages assemble into a bound book then feed derivative media",
    dominantObjectArchetype: "text-free manuscript pages becoming a bound book",
    motionArchetype: "material consolidation followed by derivative reveal",
    lighting: "warm raking bindery light emphasizing paper depth",
    props: ["text-free manuscript pages becoming a bound book", "binding tools", "derivative media blanks"],
    motionOpportunities: ["prop-detail", "reveal", "pan", "transition-state"],
  },
  L06: {
    strategyFamily: "identity-perception",
    subjectArchetype: "evolved professional seen through an audience-held legacy image",
    environmentArchetype: "street-facing reflection installation joining old category and changed business",
    compositionArchetype: "split-time reflection with current person offset from persistent public image",
    cameraArchetype: "58mm through-glass parallax view",
    actionArchetype: "professional presents changed work while audience reflection remains attached to old category",
    dominantObjectArchetype: "legacy silhouette reflected over new work evidence",
    motionArchetype: "parallax identity mismatch then association replacement",
    lighting: "mixed old cool reflection and current warm practical light",
    props: ["legacy silhouette reflected over new work evidence", "new offer artifact"],
    motionOpportunities: ["slow-push", "masked-overlay", "subject-detail", "transition-state"],
  },
  "L01-S01": {
    strategyFamily: "client-decision",
    subjectArchetype: "client hand choosing between visible proof and hidden skill",
    environmentArchetype: "vertical consultation table at the instant of selection",
    compositionArchetype: "portrait point-of-view with losing work sample below the chosen portfolio",
    cameraArchetype: "45mm vertical client point-of-view",
    actionArchetype: "selection moves to the clearer candidate before hidden craft can be inspected",
    dominantObjectArchetype: "chosen portfolio beside sealed work sample",
    motionArchetype: "decision snap and losing-detail reveal",
    lighting: "hard decision-line daylight across the two options",
    props: ["chosen portfolio beside sealed work sample", "client selection token"],
    motionOpportunities: ["split-composition", "punch-in", "prop-detail"],
  },
  "L01-S02": {
    strategyFamily: "evidence-proof",
    subjectArchetype: "highly skilled craftsperson obscured by an empty proof display",
    environmentArchetype: "vertical workshop opening onto a sparse results wall",
    compositionArchetype: "deep split-focus between active skill and absent visible evidence",
    cameraArchetype: "35mm vertical rack-focus documentary",
    actionArchetype: "excellent work continues while the customer sees only an empty evidence plane",
    dominantObjectArchetype: "finished craft sample and empty display rail",
    motionArchetype: "skill-detail rack focus to missing proof",
    lighting: "rich task light fading into flat evidence-wall light",
    props: ["finished craft sample and empty display rail", "precision tool"],
    motionOpportunities: ["subject-detail", "prop-detail", "reveal"],
  },
  "L01-S03": {
    strategyFamily: "identity-perception",
    subjectArchetype: "peer sorting memory associations around an absent professional",
    environmentArchetype: "vertical memory-test installation with physical category tokens",
    compositionArchetype: "top-to-bottom association sort ending in one empty name position",
    cameraArchetype: "60mm frontal vertical observation",
    actionArchetype: "peer groups remembered associations and exposes the missing intended one",
    dominantObjectArchetype: "unlabeled memory tokens and one empty slot",
    motionArchetype: "association sorting then empty-slot hold",
    lighting: "soft gallery light with one unfilled shadow",
    props: ["unlabeled memory tokens and one empty slot", "category trays"],
    motionOpportunities: ["pan", "highlighted-region", "punch-in"],
  },
  "L02-S01": {
    strategyFamily: "market-crowd",
    subjectArchetype: "seller addressing every passing audience at once",
    environmentArchetype: "dense vertical market aisle with competing neutral stalls",
    compositionArchetype: "overloaded foreground messages dissolving into an indifferent crowd",
    cameraArchetype: "20mm handheld vertical market wide",
    actionArchetype: "many broad signals compete and none earns a stop",
    dominantObjectArchetype: "fan of generic signal placards without text",
    motionArchetype: "rapid signal spread and crowd pass-through",
    lighting: "busy mixed market light without focal hierarchy",
    props: ["fan of generic signal placards without text", "repeated stall objects"],
    motionOpportunities: ["pan", "alternate-crop", "transition-state"],
  },
  "L02-S02": {
    strategyFamily: "audience-segmentation",
    subjectArchetype: "small specialist audience revealed as a high-value room",
    environmentArchetype: "narrow doorway opening from crowd corridor into focused consultation space",
    compositionArchetype: "compressed threshold expanding upward into a deep relevant niche",
    cameraArchetype: "75mm doorway compression shifting to 32mm depth",
    actionArchetype: "subject enters the smaller opening and discovers stronger relevance beyond it",
    dominantObjectArchetype: "narrow doorway and concentrated audience circle",
    motionArchetype: "doorway punch-through and spatial expansion",
    lighting: "dim broad corridor against bright focused room",
    props: ["narrow doorway and concentrated audience circle", "specialist context objects"],
    motionOpportunities: ["punch-in", "reveal", "slow-push"],
  },
  "L02-S03": {
    strategyFamily: "process-visualization",
    subjectArchetype: "hands testing market problem and solution alignment",
    environmentArchetype: "vertical diagnostic surface with three physical gates",
    compositionArchetype: "stacked three-stage route where only one aligned path survives",
    cameraArchetype: "40mm oblique vertical tabletop",
    actionArchetype: "three components align sequentially to open a single route",
    dominantObjectArchetype: "three unlabeled physical gates and route token",
    motionArchetype: "three-step lock and route reveal",
    lighting: "precise top light activating each gate in order",
    props: ["three unlabeled physical gates and route token", "alignment rings"],
    motionOpportunities: ["diagram-build", "highlighted-region", "punch-in"],
  },
  "L03-S01": {
    strategyFamily: "social-interaction",
    subjectArchetype: "self-declared expert awaiting external recognition",
    environmentArchetype: "vertical industry-event entrance with peer conversation beyond",
    compositionArchetype: "foreground self-label separated from background peer acknowledgement",
    cameraArchetype: "70mm candid vertical eye-line compression",
    actionArchetype: "subject presents a blank badge while peers respond only to demonstrated evidence",
    dominantObjectArchetype: "unlabeled badge and peer-shared work sample",
    motionArchetype: "badge reveal followed by peer-evidence reaction",
    lighting: "event practicals with focus shifting from badge to peers",
    props: ["unlabeled badge and peer-shared work sample", "event lanyard"],
    motionOpportunities: ["subject-detail", "reveal", "alternate-crop"],
  },
  "L03-S02": {
    strategyFamily: "process-visualization",
    subjectArchetype: "professional constructing three coherent recognition signals",
    environmentArchetype: "vertical proof-building bench with three illuminated levels",
    compositionArchetype: "bottom-up stack of offer content and context components",
    cameraArchetype: "38mm low vertical build angle",
    actionArchetype: "three signals lock into one stable expert structure",
    dominantObjectArchetype: "three distinct proof blocks",
    motionArchetype: "sequential three-block construction",
    lighting: "each proof block activates a higher light level",
    props: ["three distinct proof blocks", "structural base"],
    motionOpportunities: ["diagram-build", "slow-push", "highlighted-region"],
  },
  "L03-S03": {
    strategyFamily: "client-decision",
    subjectArchetype: "website visitor making a five-second category decision",
    environmentArchetype: "vertical transit pause with a text-free mobile page frame",
    compositionArchetype: "countdown-like visual pressure above a single first-impression frame",
    cameraArchetype: "50mm close vertical over-thumb view",
    actionArchetype: "visitor pauses briefly then exits when the category remains unclear",
    dominantObjectArchetype: "blank mobile page frame and disappearing attention marker",
    motionArchetype: "five-beat hold then exit snap",
    lighting: "cool screen glow against moving ambient background",
    props: ["blank mobile page frame and disappearing attention marker", "phone without UI text"],
    motionOpportunities: ["punch-in", "highlighted-region", "transition-state"],
  },
  "L04-S01": {
    strategyFamily: "abstract-conceptual",
    subjectArchetype: "unconnected media fragments moving without a shared center",
    environmentArchetype: "vertical studio void filled with drifting format fragments",
    compositionArchetype: "chaotic vortex that fails to form a stable topic shape",
    cameraArchetype: "26mm top-down vertical rotation",
    actionArchetype: "fragments scatter until a latent grid begins to catch them",
    dominantObjectArchetype: "mixed blank media fragments",
    motionArchetype: "fragment vortex into partial snap-to-grid",
    lighting: "uneven moving light stabilizing over the grid",
    props: ["mixed blank media fragments", "latent alignment grid"],
    motionOpportunities: ["pan", "masked-overlay", "transition-state"],
  },
  "L04-S02": {
    strategyFamily: "comparison-composition",
    subjectArchetype: "attention spike contrasted with durable topic recognition",
    environmentArchetype: "vertical dual-metric editorial stage without readable counters",
    compositionArchetype: "brief bright upper burst opposed to a persistent lower memory trail",
    cameraArchetype: "42mm locked vertical split field",
    actionArchetype: "attention flares and disappears while recognition continues accumulating",
    dominantObjectArchetype: "flash field and persistent association trail",
    motionArchetype: "attention flash versus slow memory build",
    lighting: "strobe-like attention burst against steady recognition glow",
    props: ["flash field and persistent association trail", "unlabeled exposure markers"],
    motionOpportunities: ["split-composition", "reveal", "slow-push"],
  },
  "L04-S03": {
    strategyFamily: "social-interaction",
    subjectArchetype: "peer recommendation traveling through a three-person chain",
    environmentArchetype: "vertical event foyer with separated conversational layers",
    compositionArchetype: "bottom-to-top relay triangle carrying one recognizable artifact",
    cameraArchetype: "65mm vertical conversational relay",
    actionArchetype: "one peer passes the expert association to another without the expert present",
    dominantObjectArchetype: "shared expertise artifact moving through the chain",
    motionArchetype: "three-step referral relay pan",
    lighting: "warm social practicals following the moving artifact",
    props: ["shared expertise artifact moving through the chain", "event context objects"],
    motionOpportunities: ["alternate-crop", "pan", "subject-detail"],
  },
  "L05-S01": {
    strategyFamily: "publishing-media-authority",
    subjectArchetype: "independent creator producing and handing a book to a reader",
    environmentArchetype: "vertical small-run print workshop opening to a reader encounter",
    compositionArchetype: "hands-on production foreground rising to reader exchange above",
    cameraArchetype: "48mm vertical workshop documentary",
    actionArchetype: "creator binds a text-free volume and delivers it directly to a reader",
    dominantObjectArchetype: "independently bound text-free book",
    motionArchetype: "binding detail to reader handoff",
    lighting: "warm workshop task light opening into daylight",
    props: ["independently bound text-free book", "binding press", "reader tote"],
    motionOpportunities: ["prop-detail", "pan", "reveal"],
  },
  "L05-S02": {
    strategyFamily: "product-object-still-life",
    subjectArchetype: "overbroad manuscript collapsing under accumulated topics",
    environmentArchetype: "vertical editorial table overloaded by incompatible page stacks",
    compositionArchetype: "top-heavy page tower compressing toward one viable focused spine",
    cameraArchetype: "57mm oblique vertical still-life",
    actionArchetype: "excess page stacks buckle until one focused volume remains",
    dominantObjectArchetype: "overloaded manuscript tower and focused book block",
    motionArchetype: "page-stack collapse into focused consolidation",
    lighting: "raking paper light with deep load-bearing shadows",
    props: ["overloaded manuscript tower and focused book block", "discarded topic bundles"],
    motionOpportunities: ["prop-detail", "transition-state", "punch-in"],
  },
  "L05-S03": {
    strategyFamily: "content-ecosystem",
    subjectArchetype: "single book feeding multiple coherent media outputs",
    environmentArchetype: "vertical distribution table extending upward into media channels",
    compositionArchetype: "book-rooted branching tree optimized for portrait space",
    cameraArchetype: "34mm low-to-high vertical system view",
    actionArchetype: "chapters branch upward into audio video article and Short artifacts",
    dominantObjectArchetype: "text-free book root with branching media objects",
    motionArchetype: "source-to-branches diagram build",
    lighting: "base light propagating upward through each branch",
    props: ["text-free book root with branching media objects", "format-specific blank artifacts"],
    motionOpportunities: ["diagram-build", "pan", "highlighted-region"],
  },
  "L06-S01": {
    strategyFamily: "before-after",
    subjectArchetype: "changed professional separated from audience-held former identity",
    environmentArchetype: "vertical street window showing old portrait foreground and new work beyond",
    compositionArchetype: "foreground legacy image occluding the evolved person in depth",
    cameraArchetype: "72mm vertical depth compression through window",
    actionArchetype: "audience attends to the old image while current work happens behind it",
    dominantObjectArchetype: "legacy portrait silhouette and changed-work scene",
    motionArchetype: "depth reveal from old image to current person",
    lighting: "cool legacy foreground against warm current-work depth",
    props: ["legacy portrait silhouette and changed-work scene", "new service artifact"],
    motionOpportunities: ["slow-push", "masked-overlay", "reveal"],
  },
  "L06-S02": {
    strategyFamily: "comparison-composition",
    subjectArchetype: "professional changing a profile marker while surrounding perception stays fixed",
    environmentArchetype: "vertical public profile installation encircled by unchanged audience tokens",
    compositionArchetype: "small changed foreground panel against dominant static memory field",
    cameraArchetype: "46mm vertical frontal mismatch frame",
    actionArchetype: "profile marker flips but audience-held associations do not move",
    dominantObjectArchetype: "blank bio panel and fixed memory tokens",
    motionArchetype: "panel flip followed by static-field hold",
    lighting: "brief panel change light against unchanged ambient field",
    props: ["blank bio panel and fixed memory tokens", "profile frame without text"],
    motionOpportunities: ["reveal", "highlighted-region", "transition-state"],
  },
  "L06-S03": {
    strategyFamily: "transformation",
    subjectArchetype: "professional deliberately migrating an audience association",
    environmentArchetype: "vertical evidence bridge between legacy and target category walls",
    compositionArchetype: "ascending bridge of proof carrying the subject toward a new association",
    cameraArchetype: "36mm lateral-to-upward vertical tracking",
    actionArchetype: "subject relocates proof objects from the old category to the new one",
    dominantObjectArchetype: "bridge of prior proof and new category artifacts",
    motionArchetype: "staged association migration across bridge",
    lighting: "progressive light shift activated by each moved proof object",
    props: ["bridge of prior proof and new category artifacts", "category wall anchors"],
    motionOpportunities: ["pan", "subject-detail", "transition-state"],
  },
};

export function resolveOpeningTreatmentProfile(contentId: string): OpeningTreatmentProfile {
  const profile = OPENING_TREATMENTS[contentId];
  if (!profile) throw new Error(`Missing deterministic Veronica opening treatment for ${contentId}.`);
  return profile;
}

export function findOpeningTreatmentProfile(contentId: string): OpeningTreatmentProfile | undefined {
  return OPENING_TREATMENTS[contentId];
}

export function openingTreatmentContentIds(): readonly string[] {
  return Object.keys(OPENING_TREATMENTS).sort();
}
