import { response, responseHeader, schema } from "./openapi-helpers.js";
export const openApiComponents = {
  components: {
    securitySchemes: {
      BearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "JWT",
        description:
          "Workspace permissions are enforced per operation after token and membership validation.",
      },
    },
    headers: {
      ETag: {
        description: "Strong resource revision tag.",
        required: true,
        schema: { type: "string", pattern: '^"(0|[1-9][0-9]*)"$' },
      },
      RequestId: {
        description: "Request correlation identifier.",
        required: true,
        schema: {
          type: "string",
          minLength: 3,
          maxLength: 160,
          pattern: "^[A-Za-z0-9][A-Za-z0-9._-]{2,159}$",
        },
      },
      Location: {
        description: "Canonical URL of the asynchronous job.",
        required: true,
        schema: { type: "string" },
      },
      RetryAfter: {
        description: "Suggested polling delay in seconds.",
        required: true,
        schema: { type: "string", pattern: "^[0-9]+$" },
      },
      IdempotencyReplayed: {
        description:
          "True when the stored response for an equal idempotent request is replayed.",
        required: false,
        schema: { type: "string", enum: ["true"] },
      },
    },
    parameters: {
      RequestId: {
        name: "x-request-id",
        in: "header",
        required: false,
        schema: {
          type: "string",
          minLength: 3,
          maxLength: 160,
          pattern: "^[A-Za-z0-9][A-Za-z0-9._-]{2,159}$",
        },
      },
      IdempotencyKey: {
        name: "Idempotency-Key",
        in: "header",
        required: true,
        schema: {
          type: "string",
          minLength: 1,
          maxLength: 255,
          pattern: "^[\\x20-\\x7E]+$",
        },
      },
      IfMatch: {
        name: "If-Match",
        in: "header",
        required: true,
        schema: { type: "string", pattern: '^"(0|[1-9][0-9]*)"$' },
      },
      WorkspaceId: {
        name: "workspace",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      ProjectId: {
        name: "project",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      EpisodeId: {
        name: "episode",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      WorkflowRunId: {
        name: "run",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      JobId: {
        name: "job",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      AssetId: {
        name: "asset",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      PublicationId: {
        name: "publication",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      ApiCredentialId: {
        name: "key",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      WebhookEndpointId: {
        name: "endpoint",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      WebhookDeliveryId: {
        name: "delivery",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      ProductionTemplateId: {
        name: "template",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      MimeTypeFilter: {
        name: "filter[mimeType]",
        in: "query",
        required: false,
        schema: { type: "string", minLength: 1, maxLength: 160 },
      },
      ApprovalId: {
        name: "approval",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      ApprovalChallengeId: {
        name: "challenge",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      SpeechGenerationId: {
        name: "generation",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      SpeechProfileVersionId: {
        name: "version",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      SpeechProfileId: {
        name: "profile",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      GenreId: {
        name: "genre",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      VideoId: {
        name: "video",
        in: "path",
        required: true,
        schema: schema("OpaqueId"),
      },
      PageSize: {
        name: "page[size]",
        in: "query",
        required: false,
        schema: { type: "integer", minimum: 1, maximum: 100, default: 25 },
      },
      PageAfter: {
        name: "page[after]",
        in: "query",
        required: false,
        schema: { type: "string", minLength: 1, maxLength: 4_096 },
      },
      PageCursor: {
        name: "page[cursor]",
        in: "query",
        required: false,
        schema: { type: "string", minLength: 1, maxLength: 4_096 },
      },
      FilterProjectId: {
        name: "filter[projectId]",
        in: "query",
        required: false,
        schema: schema("OpaqueId"),
      },
      FilterProfileId: {
        name: "filter[profileId]",
        in: "query",
        required: false,
        schema: {
          type: "string",
          enum: [
            "dark-truth",
            "mathematics-education",
            "strategic-reinvention",
            "history",
          ],
        },
      },
      FilterLocale: {
        name: "filter[locale]",
        in: "query",
        required: false,
        schema: {
          type: "string",
          enum: ["en", "de", "es", "fr", "pt", "it"],
        },
      },
      FilterRunStatus: {
        name: "filter[runStatus]",
        in: "query",
        required: false,
        schema: {
          type: "string",
          enum: [
            "queued",
            "running",
            "awaiting_approval",
            "succeeded",
            "failed",
            "cancelled",
          ],
        },
      },
      FilterJobStatus: {
        name: "filter[jobStatus]",
        in: "query",
        required: false,
        schema: {
          type: "string",
          enum: [
            "queued",
            "running",
            "waiting_for_approval",
            "retry_scheduled",
            "cancelling",
            "cancelled",
            "succeeded",
            "succeeded_with_warnings",
            "partially_succeeded",
            "failed",
            "dead_lettered",
          ],
        },
      },
      FilterSubjectId: {
        name: "filter[subjectId]",
        in: "query",
        required: false,
        schema: schema("OpaqueId"),
      },
      FilterOperation: {
        name: "filter[operation]",
        in: "query",
        required: false,
        schema: { type: "string", minLength: 1, maxLength: 160 },
      },
      FilterUnit: {
        name: "filter[unit]",
        in: "query",
        required: false,
        schema: { type: "string", minLength: 1, maxLength: 160 },
      },
      FilterAttemptId: {
        name: "filter[attemptId]",
        in: "query",
        required: false,
        schema: schema("OpaqueId"),
      },
      FilterEndpointId: {
        name: "filter[endpointId]",
        in: "query",
        required: false,
        schema: schema("OpaqueId"),
      },
      FilterOccurredAfter: {
        name: "filter[occurredAfter]",
        in: "query",
        required: false,
        schema: { type: "string", format: "date-time" },
      },
      FilterOccurredBefore: {
        name: "filter[occurredBefore]",
        in: "query",
        required: false,
        schema: { type: "string", format: "date-time" },
      },
    },
    schemas: {
      OpaqueId: {
        type: "string",
        minLength: 3,
        maxLength: 160,
        pattern: "^[A-Za-z0-9][A-Za-z0-9._-]*$",
      },
      Revision: { type: "integer", minimum: 0 },
      SpeechEstimateInput: {
        type: "object",
        additionalProperties: false,
        required: ["videoId"],
        properties: {
          videoId: schema("OpaqueId"),
          genreId: schema("OpaqueId"),
          language: { type: "string", pattern: "^[a-z]{2}(?:-[A-Z]{2})?$" },
          text: { type: "string", minLength: 1, maxLength: 200000 },
          profileVersionId: schema("OpaqueId"),
        },
        example: { videoId: "video-1" },
      },
      SpeechGenerationInput: {
        type: "object",
        additionalProperties: false,
        required: ["videoId"],
        properties: {
          videoId: schema("OpaqueId"),
          genreId: schema("OpaqueId"),
          language: { type: "string", pattern: "^[a-z]{2}(?:-[A-Z]{2})?$" },
          text: { type: "string", minLength: 1, maxLength: 200000 },
          profileVersionId: schema("OpaqueId"),
          forceRegeneration: { type: "boolean", default: false },
          supersedesGenerationId: schema("OpaqueId"),
        },
        example: { videoId: "video-1", forceRegeneration: false },
      },
      SpeechEstimate: {
        type: "object",
        additionalProperties: false,
        required: [
          "profileVersionId",
          "provider",
          "billableCharacters",
          "cacheHitExpected",
          "quotaImpact",
        ],
        properties: {
          profileVersionId: schema("OpaqueId"),
          provider: { type: "string", enum: ["openai", "elevenlabs"] },
          billableCharacters: { type: "integer", minimum: 0 },
          estimatedCredits: { type: "number", minimum: 0 },
          estimatedCurrencyAmount: { type: "number", minimum: 0 },
          currency: { type: "string", minLength: 3, maxLength: 3 },
          cacheHitExpected: { type: "boolean" },
          quotaImpact: {
            type: "object",
            additionalProperties: false,
            required: ["allowed", "warning"],
            properties: {
              allowed: { type: "boolean" },
              warning: { type: "boolean" },
              remainingCharacters: { type: "integer", minimum: 0 },
            },
          },
        },
      },
      SpeechGeneration: {
        type: "object",
        additionalProperties: false,
        required: [
          "generationId",
          "revision",
          "state",
          "profileVersionId",
          "provider",
          "cacheHit",
        ],
        properties: {
          generationId: schema("OpaqueId"),
          revision: schema("Revision"),
          state: { type: "string" },
          profileVersionId: schema("OpaqueId"),
          provider: { type: "string", enum: ["openai", "elevenlabs"] },
          cacheHit: { type: "boolean" },
          masterArtifactId: {
            type: "string",
            pattern: "^(?!/)(?!.*(?:^|/)\\.\\.?(?:/|$))[a-zA-Z0-9._/-]+$",
          },
          failure: {
            type: "object",
            additionalProperties: false,
            properties: {
              code: { type: "string" },
              retryable: { type: "boolean" },
              message: { type: "string" },
            },
          },
        },
      },
      SpeechProfileReference: {
        type: "object",
        additionalProperties: false,
        required: ["profileVersionId"],
        properties: { profileVersionId: schema("OpaqueId") },
      },
      VideoSpeechOverrideInput: {
        oneOf: [
          {
            type: "object",
            additionalProperties: false,
            required: ["useGenreDefault"],
            properties: { useGenreDefault: { type: "boolean", enum: [true] } },
          },
          {
            type: "object",
            additionalProperties: false,
            required: ["useGenreDefault", "profileVersionId"],
            properties: {
              useGenreDefault: { type: "boolean", enum: [false] },
              profileVersionId: schema("OpaqueId"),
            },
          },
        ],
      },
      SpeechProfileInput: {
        type: "object",
        additionalProperties: false,
        required: ["key", "displayName"],
        properties: {
          key: { type: "string", pattern: "^[a-z][a-z0-9_-]*$" },
          displayName: { type: "string", minLength: 1, maxLength: 160 },
          consentRecordId: schema("OpaqueId"),
        },
      },
      SpeechProfile: {
        type: "object",
        additionalProperties: false,
        required: [
          "profileId",
          "key",
          "displayName",
          "status",
          "consentStatus",
          "revision",
        ],
        properties: {
          profileId: schema("OpaqueId"),
          key: { type: "string" },
          displayName: { type: "string" },
          status: { type: "string", enum: ["DRAFT", "ACTIVE", "DEPRECATED"] },
          consentStatus: {
            type: "string",
            enum: ["not_required", "valid", "missing", "expired", "revoked"],
          },
          activeVersionId: schema("OpaqueId"),
          revision: schema("Revision"),
        },
      },
      SpeechProfileVersionInput: {
        type: "object",
        additionalProperties: false,
        required: ["language", "configuration"],
        properties: {
          language: { type: "string", pattern: "^[a-z]{2}(?:-[A-Z]{2})?$" },
          configuration: {
            type: "object",
            description:
              "Provider-specific configuration; secrets are not accepted.",
          },
        },
      },
      SpeechPolicy: {
        type: "object",
        additionalProperties: false,
        required: ["profileVersionId", "revision"],
        properties: {
          profileVersionId: { oneOf: [schema("OpaqueId"), { type: "null" }] },
          revision: schema("Revision"),
        },
      },
      SpeechProfileVersion: {
        type: "object",
        additionalProperties: false,
        required: [
          "profileVersionId",
          "profileId",
          "version",
          "language",
          "provider",
          "status",
          "revision",
        ],
        properties: {
          profileVersionId: schema("OpaqueId"),
          profileId: schema("OpaqueId"),
          version: { type: "integer", minimum: 1 },
          language: { type: "string" },
          provider: { type: "string", enum: ["openai", "elevenlabs"] },
          status: { type: "string", enum: ["DRAFT", "ACTIVE", "DEPRECATED"] },
          revision: schema("Revision"),
        },
      },
      SpeechProfilePage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: { items: { type: "array", items: { type: "object" } } },
      },
      SignedBigIntString: { type: "string", pattern: "^-?(0|[1-9][0-9]*)$" },
      NonNegativeBigIntString: { type: "string", pattern: "^(0|[1-9][0-9]*)$" },
      WorkspaceQuotaStatus: {
        type: "object",
        additionalProperties: false,
        required: [
          "workspaceId",
          "budgetLimitMinor",
          "reservedMinor",
          "settledMinor",
          "availableMinor",
          "revision",
        ],
        properties: {
          workspaceId: schema("OpaqueId"),
          budgetLimitMinor: schema("NonNegativeBigIntString"),
          reservedMinor: schema("NonNegativeBigIntString"),
          settledMinor: schema("NonNegativeBigIntString"),
          availableMinor: schema("NonNegativeBigIntString"),
          revision: schema("Revision"),
          dimensions: {
            type: "array",
            items: schema("QuotaDimensionStatus"),
          },
        },
      },
      QuotaDimensionStatus: {
        type: "object",
        additionalProperties: false,
        required: [
          "dimension",
          "limitUnits",
          "reservedUnits",
          "settledUnits",
          "availableUnits",
          "enforcement",
        ],
        properties: {
          dimension: {
            type: "string",
            enum: [
              "active_workflows",
              "storage_bytes",
              "batch_items",
              "active_batches",
              "publication_count",
              "active_publications",
              "provider_budget_minor",
              "principal_provider_budget_minor",
              "speech_characters",
            ],
          },
          limitUnits: { type: "integer", minimum: 0 },
          reservedUnits: { type: "integer", minimum: 0 },
          settledUnits: { type: "integer", minimum: 0 },
          availableUnits: { type: "integer", minimum: 0 },
          enforcement: { type: "string", enum: ["hard", "soft"] },
        },
      },
      ProviderHealthStatus: {
        type: "object",
        additionalProperties: false,
        required: [
          "providerId",
          "scope",
          "state",
          "fallbackExplicit",
          "freshness",
        ],
        properties: {
          providerId: schema("OpaqueId"),
          scope: { type: "string", enum: ["speech", "image", "render"] },
          state: {
            type: "string",
            enum: [
              "available",
              "degraded",
              "unavailable",
              "unconfigured",
              "unsupported",
            ],
          },
          fallbackProviderId: schema("OpaqueId"),
          fallbackExplicit: { type: "boolean" },
          freshness: schema("DateTime"),
          message: { type: "string", minLength: 1, maxLength: 2_000 },
        },
      },
      ProviderHealthPage: {
        type: "object",
        additionalProperties: false,
        required: ["items", "projectedAt"],
        properties: {
          items: {
            type: "array",
            items: schema("ProviderHealthStatus"),
          },
          projectedAt: schema("DateTime"),
        },
      },
      UsageRecord: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "kind",
          "subjectId",
          "operation",
          "unit",
          "quantityUnits",
          "costMinor",
          "correctionOfUsageId",
          "attemptId",
          "data",
          "occurredAt",
        ],
        properties: {
          id: schema("OpaqueId"),
          kind: { type: "string", enum: ["usage", "correction"] },
          subjectId: schema("OpaqueId"),
          operation: { type: "string" },
          unit: { type: "string" },
          quantityUnits: schema("SignedBigIntString"),
          costMinor: schema("SignedBigIntString"),
          correctionOfUsageId: {
            oneOf: [schema("OpaqueId"), { type: "null" }],
          },
          attemptId: { oneOf: [schema("OpaqueId"), { type: "null" }] },
          data: {},
          occurredAt: { type: "string", format: "date-time" },
        },
      },
      UsageRecordPage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: { type: "array", items: schema("UsageRecord") },
          nextAfter: { type: "string", minLength: 1, maxLength: 4_096 },
        },
      },
      AuditEvent: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "action",
          "subjectId",
          "actorId",
          "correlationId",
          "causationId",
          "data",
          "occurredAt",
        ],
        properties: {
          id: schema("OpaqueId"),
          action: { type: "string" },
          subjectId: schema("OpaqueId"),
          actorId: schema("OpaqueId"),
          correlationId: schema("OpaqueId"),
          causationId: { oneOf: [schema("OpaqueId"), { type: "null" }] },
          data: {},
          occurredAt: { type: "string", format: "date-time" },
        },
      },
      AuditEventPage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: { type: "array", items: schema("AuditEvent") },
          nextAfter: { type: "string", minLength: 1, maxLength: 4_096 },
        },
      },
      ApiCredentialRecord: {
        type: "object",
        additionalProperties: false,
        required: [
          "schemaVersion",
          "workspaceId",
          "keyId",
          "name",
          "principalId",
          "permissions",
          "status",
          "expiresAt",
          "revision",
          "createdAt",
          "updatedAt",
        ],
        properties: {
          schemaVersion: {
            type: "string",
            enum: ["mediaforge.api-credential.v1"],
          },
          workspaceId: schema("OpaqueId"),
          keyId: schema("OpaqueId"),
          name: { type: "string", minLength: 1, maxLength: 160 },
          principalId: schema("OpaqueId"),
          permissions: {
            type: "array",
            items: { type: "string", minLength: 1 },
            minItems: 1,
          },
          status: {
            type: "string",
            enum: ["active", "overlapping", "revoked", "expired"],
          },
          expiresAt: schema("DateTime"),
          overlapUntil: schema("DateTime"),
          lastUsedAt: schema("DateTime"),
          rotatedFromKeyId: schema("OpaqueId"),
          revision: schema("Revision"),
          createdAt: schema("DateTime"),
          updatedAt: schema("DateTime"),
        },
      },
      ApiCredentialPage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: {
            type: "array",
            items: schema("ApiCredentialRecord"),
          },
        },
      },
      ApiCredentialIssueInput: {
        type: "object",
        additionalProperties: false,
        required: ["name", "principalId", "permissions", "expiresAt"],
        properties: {
          name: { type: "string", minLength: 1, maxLength: 160 },
          principalId: schema("OpaqueId"),
          permissions: {
            type: "array",
            items: { type: "string", minLength: 1 },
            minItems: 1,
          },
          expiresAt: schema("DateTime"),
          overlapMs: { type: "integer", minimum: 0 },
        },
      },
      ApiCredentialIssueResult: {
        type: "object",
        additionalProperties: false,
        required: ["credential", "replayed", "showOnce"],
        properties: {
          credential: schema("ApiCredentialRecord"),
          token: { type: "string", minLength: 1 },
          replayed: { type: "boolean" },
          showOnce: { type: "boolean" },
        },
      },
      ApiCredentialRevokeInput: {
        type: "object",
        additionalProperties: false,
        required: ["reason"],
        properties: {
          reason: { type: "string", minLength: 1, maxLength: 2_000 },
        },
      },
      DeveloperJourneyStep: {
        type: "object",
        additionalProperties: false,
        required: [
          "operationId",
          "method",
          "path",
          "requestSchema",
          "responseSchema",
          "requiredHeaders",
        ],
        properties: {
          operationId: { type: "string", minLength: 1 },
          method: {
            type: "string",
            enum: ["GET", "POST", "PATCH", "PUT", "DELETE"],
          },
          path: { type: "string", minLength: 1 },
          requestSchema: {
            oneOf: [{ type: "string", minLength: 1 }, { type: "null" }],
          },
          responseSchema: { type: "string", minLength: 1 },
          requiredHeaders: {
            type: "array",
            items: { type: "string", minLength: 1 },
          },
          note: { type: "string", minLength: 1 },
        },
      },
      DeveloperJourneyExamples: {
        type: "object",
        additionalProperties: false,
        required: ["schemaVersion", "title", "steps", "projectedAt"],
        properties: {
          schemaVersion: {
            type: "string",
            enum: ["mediaforge.api-credential.v1"],
          },
          title: { type: "string", minLength: 1 },
          steps: {
            type: "array",
            items: schema("DeveloperJourneyStep"),
            minItems: 1,
          },
          projectedAt: schema("DateTime"),
        },
      },
      WebhookEndpointRecord: {
        type: "object",
        additionalProperties: false,
        required: [
          "schemaVersion",
          "workspaceId",
          "endpointId",
          "url",
          "secretVersion",
          "enabled",
          "eventFilters",
          "revision",
          "createdAt",
          "updatedAt",
        ],
        properties: {
          schemaVersion: {
            type: "string",
            enum: ["mediaforge.webhook-endpoint.v1"],
          },
          workspaceId: schema("OpaqueId"),
          endpointId: schema("OpaqueId"),
          url: { type: "string", format: "uri", maxLength: 2_048 },
          secretVersion: { type: "integer", minimum: 1 },
          enabled: { type: "boolean" },
          eventFilters: {
            type: "array",
            items: { type: "string", minLength: 1 },
            maxItems: 100,
          },
          overlapUntil: schema("DateTime"),
          revision: schema("Revision"),
          createdAt: schema("DateTime"),
          updatedAt: schema("DateTime"),
        },
      },
      WebhookEndpointPage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: {
            type: "array",
            items: schema("WebhookEndpointRecord"),
          },
        },
      },
      WebhookEndpointCreateInput: {
        type: "object",
        additionalProperties: false,
        required: ["url"],
        properties: {
          url: { type: "string", format: "uri", maxLength: 2_048 },
          eventFilters: {
            type: "array",
            items: { type: "string", minLength: 1 },
            maxItems: 100,
          },
        },
      },
      WebhookEndpointCreateResult: {
        type: "object",
        additionalProperties: false,
        required: ["endpoint", "secret", "showOnce"],
        properties: {
          endpoint: schema("WebhookEndpointRecord"),
          secret: { type: "string", minLength: 1 },
          showOnce: { type: "boolean", enum: [true] },
        },
      },
      WebhookEndpointUpdateInput: {
        type: "object",
        additionalProperties: false,
        required: ["url", "eventFilters", "enabled"],
        properties: {
          url: { type: "string", format: "uri", maxLength: 2_048 },
          eventFilters: {
            type: "array",
            items: { type: "string", minLength: 1 },
            maxItems: 100,
          },
          enabled: { type: "boolean" },
        },
      },
      WebhookSecretRotateInput: {
        type: "object",
        additionalProperties: false,
        properties: {
          overlapMs: { type: "integer", minimum: 0 },
        },
      },
      WebhookSecretRotateResult: {
        type: "object",
        additionalProperties: false,
        required: ["endpoint", "secret", "showOnce"],
        properties: {
          endpoint: schema("WebhookEndpointRecord"),
          secret: { type: "string", minLength: 1 },
          showOnce: { type: "boolean", enum: [true] },
        },
      },
      WebhookDeliveryEventSummary: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "type",
          "occurredAt",
          "subjectType",
          "subjectId",
          "subjectVersion",
          "correlationId",
        ],
        properties: {
          id: schema("OpaqueId"),
          type: { type: "string", minLength: 1 },
          occurredAt: schema("DateTime"),
          subjectType: { type: "string", minLength: 1 },
          subjectId: schema("OpaqueId"),
          subjectVersion: { type: "integer", minimum: 1 },
          correlationId: schema("OpaqueId"),
        },
      },
      WebhookDeliveryRecord: {
        type: "object",
        additionalProperties: false,
        required: [
          "schemaVersion",
          "workspaceId",
          "deliveryId",
          "endpointId",
          "eventId",
          "event",
          "state",
          "attemptCount",
          "nextAttemptAt",
          "revision",
          "createdAt",
          "updatedAt",
        ],
        properties: {
          schemaVersion: {
            type: "string",
            enum: ["mediaforge.webhook-delivery.v1"],
          },
          workspaceId: schema("OpaqueId"),
          deliveryId: schema("OpaqueId"),
          endpointId: schema("OpaqueId"),
          eventId: schema("OpaqueId"),
          event: schema("WebhookDeliveryEventSummary"),
          state: {
            type: "string",
            enum: ["pending", "delivered", "dead_letter"],
          },
          attemptCount: { type: "integer", minimum: 0 },
          nextAttemptAt: schema("DateTime"),
          deliveredAt: schema("DateTime"),
          deadLetteredAt: schema("DateTime"),
          lastStatus: { type: "integer", minimum: 100, maximum: 599 },
          lastError: { type: "string", minLength: 1, maxLength: 2_000 },
          replayOfDeliveryId: schema("OpaqueId"),
          revision: schema("Revision"),
          createdAt: schema("DateTime"),
          updatedAt: schema("DateTime"),
        },
      },
      WebhookDeliveryPage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: {
            type: "array",
            items: schema("WebhookDeliveryRecord"),
          },
          nextAfter: { type: "string", minLength: 1, maxLength: 4_096 },
        },
      },
      WebhookDeliveryAttempt: {
        type: "object",
        additionalProperties: false,
        required: ["attemptNumber", "outcome", "attemptedAt"],
        properties: {
          attemptNumber: { type: "integer", minimum: 1 },
          outcome: {
            type: "string",
            enum: ["delivered", "retry", "dead_letter"],
          },
          responseStatus: { type: "integer", minimum: 100, maximum: 599 },
          error: { type: "string", minLength: 1, maxLength: 2_000 },
          attemptedAt: schema("DateTime"),
        },
      },
      WebhookDeliveryAttemptPage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: {
            type: "array",
            items: schema("WebhookDeliveryAttempt"),
          },
        },
      },
      WebhookTestResult: {
        type: "object",
        additionalProperties: false,
        required: ["delivered"],
        properties: {
          delivered: { type: "boolean" },
          responseStatus: { type: "integer", minimum: 100, maximum: 599 },
          error: { type: "string", minLength: 1, maxLength: 2_000 },
        },
      },
      ProductionTemplateSnapshot: {
        type: "object",
        additionalProperties: false,
        required: ["profile", "configDefaults"],
        properties: {
          profile: {
            type: "string",
            enum: [
              "dark_truth",
              "mathematics_education",
              "dynamic_generic",
              "history",
              "strategic_reinvention",
            ],
          },
          configDefaults: { type: "object", additionalProperties: true },
        },
      },
      ProductionTemplateRecord: {
        type: "object",
        additionalProperties: false,
        required: [
          "schemaVersion",
          "workspaceId",
          "templateId",
          "name",
          "profile",
          "revision",
          "snapshot",
          "createdAt",
          "updatedAt",
        ],
        properties: {
          schemaVersion: {
            type: "string",
            enum: ["mediaforge.production-template.v1"],
          },
          workspaceId: schema("OpaqueId"),
          templateId: schema("OpaqueId"),
          name: { type: "string", minLength: 1, maxLength: 160 },
          profile: {
            type: "string",
            enum: [
              "dark_truth",
              "mathematics_education",
              "dynamic_generic",
              "history",
              "strategic_reinvention",
            ],
          },
          revision: schema("Revision"),
          snapshot: schema("ProductionTemplateSnapshot"),
          createdAt: schema("DateTime"),
          updatedAt: schema("DateTime"),
        },
      },
      ProductionTemplatePage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: {
            type: "array",
            items: schema("ProductionTemplateRecord"),
          },
        },
      },
      ProductionTemplateCreateInput: {
        type: "object",
        additionalProperties: false,
        required: ["name", "profile", "snapshot"],
        properties: {
          name: { type: "string", minLength: 1, maxLength: 160 },
          profile: {
            type: "string",
            enum: [
              "dark_truth",
              "mathematics_education",
              "dynamic_generic",
              "history",
              "strategic_reinvention",
            ],
          },
          snapshot: schema("ProductionTemplateSnapshot"),
        },
      },
      ProductionTemplateUpdateInput: {
        type: "object",
        additionalProperties: false,
        required: ["name", "snapshot"],
        properties: {
          name: { type: "string", minLength: 1, maxLength: 160 },
          snapshot: schema("ProductionTemplateSnapshot"),
        },
      },
      ProductionTemplateBinding: {
        type: "object",
        additionalProperties: false,
        required: [
          "schemaVersion",
          "templateId",
          "pinnedRevision",
          "appliedSnapshot",
          "appliedAt",
        ],
        properties: {
          schemaVersion: {
            type: "string",
            enum: ["mediaforge.production-template-binding.v1"],
          },
          templateId: schema("OpaqueId"),
          pinnedRevision: schema("Revision"),
          appliedSnapshot: schema("ProductionTemplateSnapshot"),
          appliedAt: schema("DateTime"),
        },
      },
      ProductionTemplateApplyInput: {
        type: "object",
        additionalProperties: false,
        required: ["templateId"],
        properties: {
          templateId: schema("OpaqueId"),
          pinnedRevision: schema("Revision"),
        },
      },
      ProductionTemplateApplyResult: {
        type: "object",
        additionalProperties: false,
        required: ["binding", "resolvedSnapshot"],
        properties: {
          binding: schema("ProductionTemplateBinding"),
          resolvedSnapshot: schema("ProductionTemplateSnapshot"),
        },
      },
      EpisodeCloneInput: {
        type: "object",
        additionalProperties: false,
        properties: {
          sourceRevision: schema("Revision"),
          targetProjectId: schema("OpaqueId"),
          copyPolicy: {
            type: "string",
            enum: ["content_and_permitted_assets", "content_only"],
          },
        },
      },
      OmittedCloneAsset: {
        type: "object",
        additionalProperties: false,
        required: ["assetId", "reason"],
        properties: {
          assetId: schema("OpaqueId"),
          reason: { type: "string", minLength: 1, maxLength: 160 },
        },
      },
      EpisodeCloneResult: {
        type: "object",
        additionalProperties: false,
        required: ["id", "revision", "omittedAssets", "resetRuntimeIdentity"],
        properties: {
          id: schema("OpaqueId"),
          revision: schema("Revision"),
          omittedAssets: {
            type: "array",
            items: schema("OmittedCloneAsset"),
          },
          resetRuntimeIdentity: { type: "boolean", enum: [true] },
        },
      },
      AssetReuseEligibility: {
        type: "object",
        additionalProperties: false,
        required: ["eligible"],
        properties: {
          eligible: { type: "boolean" },
          reason: { type: "string", minLength: 1, maxLength: 160 },
          mode: {
            type: "string",
            enum: ["reference", "copy_on_write"],
          },
        },
      },
      ReusableAssetRecord: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "mimeType",
          "bytes",
          "sha256",
          "lifecycle",
          "provenance",
          "eligibility",
        ],
        properties: {
          id: schema("OpaqueId"),
          mimeType: { type: "string", minLength: 1, maxLength: 160 },
          bytes: { type: "integer", minimum: 0 },
          sha256: { type: "string", pattern: "^[a-f0-9]{64}$" },
          lifecycle: {
            type: "string",
            enum: ["active", "archived", "shared", "revoked", "prohibited"],
          },
          provenance: { type: "string", maxLength: 8_192 },
          eligibility: schema("AssetReuseEligibility"),
        },
      },
      ReusableAssetPage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: {
            type: "array",
            items: schema("ReusableAssetRecord"),
          },
          nextAfter: { type: "string", minLength: 1, maxLength: 4_096 },
        },
      },
      EpisodeAssetReferenceRecord: {
        type: "object",
        additionalProperties: false,
        required: [
          "schemaVersion",
          "assetId",
          "sha256",
          "provenance",
          "mode",
          "attachmentKey",
          "createdAt",
        ],
        properties: {
          schemaVersion: {
            type: "string",
            enum: ["mediaforge.episode-asset-reference.v1"],
          },
          assetId: schema("OpaqueId"),
          sha256: { type: "string", pattern: "^[a-f0-9]{64}$" },
          provenance: { type: "string", maxLength: 8_192 },
          mode: {
            type: "string",
            enum: ["reference", "copy_on_write"],
          },
          attachmentKey: schema("OpaqueId"),
          createdAt: schema("DateTime"),
        },
      },
      EpisodeAssetReferenceAttachInput: {
        type: "object",
        additionalProperties: false,
        required: ["assetId"],
        properties: {
          assetId: schema("OpaqueId"),
          mode: {
            type: "string",
            enum: ["reference", "copy_on_write"],
          },
          attachmentKey: schema("OpaqueId"),
        },
      },
      EpisodeAssetReferenceAttachResult: {
        type: "object",
        additionalProperties: false,
        required: ["reference", "replayed"],
        properties: {
          reference: schema("EpisodeAssetReferenceRecord"),
          replayed: { type: "boolean" },
        },
      },
      ProjectInput: {
        type: "object",
        additionalProperties: false,
        required: ["name", "profile"],
        properties: {
          name: { type: "string", minLength: 1, maxLength: 160 },
          profile: {
            type: "string",
            enum: [
              "dark_truth",
              "mathematics_education",
              "dynamic_generic",
              "history",
              "strategic_reinvention",
            ],
          },
        },
      },
      Project: {
        type: "object",
        additionalProperties: false,
        required: ["id", "revision"],
        properties: { id: schema("OpaqueId"), revision: schema("Revision") },
      },
      ProjectPage: {
        type: "object", additionalProperties: false, required: ["items"],
        properties: { items: { type: "array", items: schema("ProjectSummary") }, nextAfter: { type: "string", minLength: 1, maxLength: 4096 } },
      },
      ProjectSummary: {
        type: "object", additionalProperties: false, required: ["id", "name", "profile", "revision", "createdAt", "updatedAt"],
        properties: { id: schema("OpaqueId"), name: { type: "string", minLength: 1, maxLength: 160 }, profile: { type: "string", enum: ["dark_truth", "mathematics_education", "dynamic_generic", "history", "strategic_reinvention"] }, revision: schema("Revision"), createdAt: { type: "string", format: "date-time" }, updatedAt: { type: "string", format: "date-time" } },
      },
      DarkTruthContent: {
        type: "object",
        additionalProperties: false,
        required: [
          "type",
          "version",
          "premise",
          "storyBibleId",
          "referenceAssetIds",
        ],
        properties: {
          type: { const: "dark_truth" },
          version: { const: "1" },
          premise: { type: "string", minLength: 1, maxLength: 20_000 },
          storyBibleId: schema("OpaqueId"),
          referenceAssetIds: {
            type: "array",
            maxItems: 100,
            items: schema("OpaqueId"),
          },
        },
      },
      MathematicsEducationContent: {
        type: "object",
        additionalProperties: false,
        required: [
          "type",
          "version",
          "curriculumSourceId",
          "skillId",
          "grade",
          "difficulty",
          "presentationPresetId",
          "audioPresetId",
        ],
        properties: {
          type: { const: "mathematics_education" },
          version: { const: "1" },
          curriculumSourceId: schema("OpaqueId"),
          skillId: {
            type: "string",
            pattern: "^M(?:5|6|7|8|9|10)-[A-Z]{2}-\\d{3}$",
          },
          grade: { type: "integer", enum: [5, 6, 7, 8, 9, 10] },
          difficulty: {
            type: "string",
            enum: ["foundation", "standard", "challenge"],
          },
          presentationPresetId: schema("OpaqueId"),
          audioPresetId: schema("OpaqueId"),
        },
      },
      HistoryContent: {
        type: "object",
        additionalProperties: false,
        required: [
          "type",
          "version",
          "topic",
          "presetId",
          "format",
          "audienceLevel",
        ],
        properties: {
          type: { const: "history" },
          version: { const: "1" },
          topic: { type: "string", minLength: 1, maxLength: 20_000 },
          presetId: {
            type: "string",
            enum: [
              "military-campaign",
              "civilization-rise-fall",
              "historical-biography",
              "archaeology-mystery",
              "world-war-geopolitics",
              "royal-court-intrigue",
              "everyday-life",
              "disaster-pandemic-survival",
              "technology-trade-transformation",
              "dark-strange-history",
            ],
          },
          format: { type: "string", enum: ["short", "standard", "long"] },
          audienceLevel: {
            type: "string",
            enum: ["general", "enthusiast", "academic-lite"],
          },
          period: {
            type: "string",
            enum: [
              "prehistory",
              "ancient",
              "late antiquity",
              "medieval",
              "early modern",
              "industrial age",
              "modern",
              "contemporary history",
              "cross-period",
            ],
          },
        },
      },
      StrategicReinventionContent: {
        type: "object",
        additionalProperties: false,
        required: [
          "type",
          "version",
          "creatorProfileId",
          "episodeMode",
          "canonicalLocale",
          "sourceAssetIds",
        ],
        properties: {
          type: { const: "strategic_reinvention" },
          version: { const: "1" },
          creatorProfileId: { const: "veronica-benini" },
          episodeMode: {
            type: "string",
            enum: [
              "story-to-strategy",
              "tactical-lesson",
              "position-essay",
              "myth-reality",
              "decision-framework",
              "case-diagnosis",
              "q-and-a",
              "guided-exercise",
            ],
          },
          canonicalLocale: { const: "it" },
          sourceAssetIds: {
            type: "array",
            minItems: 1,
            maxItems: 100,
            items: schema("OpaqueId"),
          },
        },
      },
      DynamicGenericContent: {
        type: "object",
        additionalProperties: false,
        required: ["type", "version", "input", "budgetTier"],
        properties: {
          type: { const: "dynamic_generic" },
          version: { const: "1" },
          input: {
            oneOf: [
              {
                type: "object",
                additionalProperties: false,
                required: ["kind", "locale", "title", "body"],
                properties: {
                  kind: { const: "completed_story" },
                  locale: {
                    type: "string",
                    pattern: "^[a-z]{2}(?:-[A-Z]{2})?$",
                  },
                  canonicalLanguage: {
                    type: "string",
                    pattern: "^[a-z]{2}(?:-[A-Z]{2})?$",
                  },
                  title: { type: "string", minLength: 1, maxLength: 300 },
                  body: { type: "string", minLength: 1, maxLength: 120000 },
                },
              },
              {
                type: "object",
                additionalProperties: false,
                required: ["kind", "locale", "title", "sections"],
                properties: {
                  kind: { const: "structured_outline" },
                  locale: {
                    type: "string",
                    pattern: "^[a-z]{2}(?:-[A-Z]{2})?$",
                  },
                  canonicalLanguage: {
                    type: "string",
                    pattern: "^[a-z]{2}(?:-[A-Z]{2})?$",
                  },
                  title: { type: "string", minLength: 1, maxLength: 300 },
                  sections: {
                    type: "array",
                    minItems: 1,
                    maxItems: 200,
                    items: {
                      type: "object",
                      additionalProperties: false,
                      required: ["id", "body"],
                      properties: {
                        id: schema("OpaqueId"),
                        heading: { type: "string", maxLength: 200 },
                        body: {
                          type: "string",
                          minLength: 1,
                          maxLength: 30000,
                        },
                      },
                    },
                  },
                },
              },
            ],
            discriminator: { propertyName: "kind" },
          },
          budgetTier: {
            type: "string",
            enum: ["economy", "standard", "premium"],
          },
          overrides: {
            type: "object",
            additionalProperties: false,
            description:
              "Bounded semantic overrides; arbitrary executable configuration is rejected.",
            properties: {
              baseProfile: {
                type: "string",
                enum: [
                  "neutral-narrative",
                  "horror-compatible",
                  "educational-compatible",
                  "presenter-advice-compatible",
                  "documentary",
                  "children-family",
                  "comedy-light",
                  "inspirational",
                  "business-explainer",
                  "historical",
                  "science-technology",
                  "abstract-experimental",
                ],
              },
              narrationPacing: {
                type: "string",
                enum: ["slow", "measured", "balanced", "brisk", "urgent"],
              },
              visualPreset: {
                type: "string",
                enum: [
                  "neutral-cinematic",
                  "dark-cinematic",
                  "warm-illustrative",
                  "clean-educational",
                  "documentary-realism",
                  "presenter-clean",
                  "playful-graphic",
                  "archival",
                  "technical-diagram",
                ],
              },
              durationClass: {
                type: "string",
                enum: ["short", "standard", "long"],
              },
              sceneDensity: { type: "number", minimum: 0, maximum: 1 },
              imageStrategy: {
                type: "string",
                enum: [
                  "key-scenes",
                  "balanced-scenes",
                  "dense-scenes",
                  "diagrams-first",
                  "presenter-support",
                ],
              },
              musicIntensity: { type: "number", minimum: 0, maximum: 1 },
              thumbnailStrategy: {
                type: "string",
                enum: [
                  "single-subject",
                  "question",
                  "contrast",
                  "outcome",
                  "mystery",
                  "educational-proof",
                  "presenter-promise",
                ],
              },
              budgetTier: {
                type: "string",
                enum: ["economy", "standard", "premium"],
              },
              requiresReview: { type: "boolean" },
            },
          },
        },
      },
      EpisodeContent: {
        oneOf: [
          schema("DarkTruthContent"),
          schema("MathematicsEducationContent"),
          schema("HistoryContent"),
          schema("StrategicReinventionContent"),
          schema("DynamicGenericContent"),
        ],
        discriminator: { propertyName: "type" },
      },
      EpisodeInput: {
        type: "object",
        additionalProperties: false,
        required: ["content"],
        properties: { content: schema("EpisodeContent") },
      },
      EpisodeCreated: {
        type: "object",
        additionalProperties: false,
        required: ["id", "revision"],
        properties: { id: schema("OpaqueId"), revision: schema("Revision") },
      },
      Episode: {
        type: "object",
        additionalProperties: false,
        required: ["id", "revision", "content"],
        properties: {
          id: schema("OpaqueId"),
          revision: schema("Revision"),
          content: schema("EpisodeContent"),
        },
      },
      EpisodePage: {
        type: "object", additionalProperties: false, required: ["items"],
        properties: { items: { type: "array", items: schema("EpisodeSummary") }, nextAfter: { type: "string", minLength: 1, maxLength: 4096 } },
      },
      EpisodeSummary: {
        type: "object", additionalProperties: false, required: ["id", "revision", "content", "createdAt", "updatedAt"],
        properties: { id: schema("OpaqueId"), revision: schema("Revision"), content: schema("EpisodeContent"), createdAt: { type: "string", format: "date-time" }, updatedAt: { type: "string", format: "date-time" } },
      },
      WorkflowAdmission: {
        type: "object",
        additionalProperties: false,
        required: [
          "template",
          "episodeRevision",
          "locales",
          "variants",
          "approvalMode",
          "publicationMode",
        ],
        properties: {
          template: { const: "episode-production" },
          episodeRevision: schema("Revision"),
          locales: {
            type: "array",
            minItems: 1,
            maxItems: 10,
            uniqueItems: true,
            items: { type: "string", pattern: "^[a-z]{2}(?:-[A-Z]{2})?$" },
          },
          variants: {
            type: "array",
            minItems: 1,
            maxItems: 2,
            uniqueItems: true,
            items: { type: "string", enum: ["full", "short"] },
          },
          approvalMode: { type: "string", enum: ["required", "automatic"] },
          publicationMode: { const: "none" },
        },
      },
      ResourceLinks: {
        type: "object",
        additionalProperties: false,
        required: ["workflowRun", "job"],
        properties: {
          workflowRun: { type: "string" },
          job: { type: "string" },
        },
      },
      WorkflowCommandAccepted: {
        type: "object",
        additionalProperties: false,
        required: ["workflowRunId", "jobId", "revision", "links"],
        properties: {
          workflowRunId: schema("OpaqueId"),
          jobId: schema("OpaqueId"),
          revision: schema("Revision"),
          links: schema("ResourceLinks"),
        },
      },
      WorkflowRun: {
        type: "object",
        additionalProperties: false,
        required: ["id", "revision", "status"],
        properties: {
          id: schema("OpaqueId"),
          revision: schema("Revision"),
          status: {
            type: "string",
            enum: [
              "queued",
              "running",
              "awaiting_approval",
              "succeeded",
              "failed",
              "cancelled",
            ],
          },
        },
      },
      WorkflowStep: {
        type: "object",
        additionalProperties: false,
        required: ["id", "status"],
        properties: {
          id: schema("OpaqueId"),
          status: { type: "string" },
          phase: { type: "string" },
          message: { type: "string", maxLength: 2_000 },
        },
      },
      WorkflowStepPage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: { items: { type: "array", items: schema("WorkflowStep") } },
      },
      ProductionUnitAddress: {
        type: "object",
        additionalProperties: false,
        required: ["kind"],
        properties: {
          kind: {
            type: "string",
            enum: [
              "brief_script",
              "narration",
              "visual_plan",
              "scene_visual",
              "map",
              "diagram",
              "tts",
              "subtitles",
              "render",
              "review_readiness",
              "publish_readiness",
            ],
          },
          unitKey: schema("OpaqueId"),
        },
      },
      ProductionUnitSnapshot: {
        type: "object",
        additionalProperties: false,
        required: ["address", "inputFingerprint", "status"],
        properties: {
          address: schema("ProductionUnitAddress"),
          inputFingerprint: { type: "string", pattern: "^[a-f0-9]{64}$" },
          contentHash: { type: "string", pattern: "^[a-f0-9]{64}$" },
          status: {
            type: "string",
            enum: ["missing", "valid", "stale", "invalidated"],
          },
          artifactRecordId: schema("OpaqueId"),
        },
      },
      ProductionUnitChange: {
        type: "object",
        additionalProperties: false,
        required: ["address", "nextInputFingerprint"],
        properties: {
          address: schema("ProductionUnitAddress"),
          nextInputFingerprint: { type: "string", pattern: "^[a-f0-9]{64}$" },
          nextContentHash: { type: "string", pattern: "^[a-f0-9]{64}$" },
          reason: { type: "string", minLength: 1, maxLength: 2_000 },
        },
      },
      InvalidatedProductionUnit: {
        type: "object",
        additionalProperties: false,
        required: ["address", "previousStatus", "reason", "preservedUpstream"],
        properties: {
          address: schema("ProductionUnitAddress"),
          previousStatus: {
            type: "string",
            enum: ["missing", "valid", "stale", "invalidated"],
          },
          reason: { type: "string", minLength: 1, maxLength: 2_000 },
          preservedUpstream: { type: "boolean" },
        },
      },
      GateEvidenceUpdate: {
        type: "object",
        additionalProperties: false,
        required: ["code", "message", "affectedUnitAddresses"],
        properties: {
          code: {
            type: "string",
            enum: [
              "validation_stale",
              "approval_stale",
              "render_stale",
              "evidence_changed",
            ],
          },
          message: { type: "string", minLength: 1, maxLength: 2_000 },
          affectedUnitAddresses: {
            type: "array",
            minItems: 1,
            items: schema("ProductionUnitAddress"),
          },
          contentHashes: {
            type: "array",
            items: { type: "string", pattern: "^[a-f0-9]{64}$" },
          },
        },
      },
      ArtifactInvalidationPreviewInput: {
        type: "object",
        additionalProperties: false,
        required: ["units", "changes"],
        properties: {
          units: {
            type: "array",
            minItems: 1,
            items: schema("ProductionUnitSnapshot"),
          },
          changes: {
            type: "array",
            minItems: 1,
            items: schema("ProductionUnitChange"),
          },
        },
      },
      ArtifactInvalidationPreview: {
        type: "object",
        additionalProperties: false,
        required: [
          "changedAddresses",
          "invalidatedUnits",
          "preservedUnits",
          "regenerationTargets",
          "staleReviewReadiness",
          "stalePublishReadiness",
          "gateEvidenceUpdates",
          "projectedAt",
        ],
        properties: {
          changedAddresses: {
            type: "array",
            minItems: 1,
            items: schema("ProductionUnitAddress"),
          },
          invalidatedUnits: {
            type: "array",
            items: schema("InvalidatedProductionUnit"),
          },
          preservedUnits: {
            type: "array",
            items: schema("ProductionUnitAddress"),
          },
          regenerationTargets: {
            type: "array",
            items: schema("ProductionUnitAddress"),
          },
          staleReviewReadiness: { type: "boolean" },
          stalePublishReadiness: { type: "boolean" },
          gateEvidenceUpdates: {
            type: "array",
            items: schema("GateEvidenceUpdate"),
          },
          projectedAt: schema("DateTime"),
        },
      },
      ProductionUnitRegenerationInput: {
        type: "object",
        additionalProperties: false,
        required: ["targets"],
        properties: {
          targets: {
            type: "array",
            minItems: 1,
            items: schema("ProductionUnitAddress"),
          },
          reason: { type: "string", minLength: 1, maxLength: 2_000 },
        },
      },
      ProductionUnitRegenerationAccepted: {
        type: "object",
        additionalProperties: false,
        required: ["acceptedTargets", "workflowRunId", "jobId", "revision"],
        properties: {
          acceptedTargets: {
            type: "array",
            minItems: 1,
            items: schema("ProductionUnitAddress"),
          },
          workflowRunId: schema("OpaqueId"),
          jobId: schema("OpaqueId"),
          revision: schema("Revision"),
        },
      },
      WorkflowPortfolioRecovery: {
        type: "object",
        additionalProperties: false,
        required: ["classification", "availableActions"],
        properties: {
          classification: {
            type: "string",
            enum: [
              "none",
              "in_progress",
              "retryable",
              "non_retryable",
              "reconciliation_required",
              "abandoned",
            ],
          },
          availableActions: {
            type: "array",
            minItems: 1,
            items: {
              type: "string",
              enum: ["resume", "cancel", "abandon", "view_timeline"],
            },
          },
          sanitizedFailureCode: { type: "string", minLength: 1, maxLength: 160 },
          message: { type: "string", minLength: 1, maxLength: 2_000 },
        },
      },
      WorkflowPortfolioEntry: {
        type: "object",
        additionalProperties: false,
        required: [
          "projectId",
          "episodeId",
          "runId",
          "runRevision",
          "runStatus",
          "profileId",
          "recovery",
          "createdAt",
          "updatedAt",
        ],
        properties: {
          projectId: schema("OpaqueId"),
          episodeId: schema("OpaqueId"),
          runId: schema("OpaqueId"),
          runRevision: schema("Revision"),
          runStatus: {
            type: "string",
            enum: [
              "queued",
              "running",
              "awaiting_approval",
              "succeeded",
              "failed",
              "cancelled",
            ],
          },
          profileId: {
            type: "string",
            enum: [
              "dark-truth",
              "mathematics-education",
              "strategic-reinvention",
              "history",
            ],
          },
          locale: {
            type: "string",
            enum: ["en", "de", "es", "fr", "pt", "it"],
          },
          episodeRevision: schema("Revision"),
          latestJobId: schema("OpaqueId"),
          latestJobStatus: { type: "string" },
          latestJobAttempts: { type: "integer", minimum: 0 },
          latestStageId: schema("OpaqueId"),
          latestStageStatus: { type: "string", maxLength: 160 },
          preservedArtifactHashes: {
            type: "array",
            items: { type: "string", pattern: "^[a-f0-9]{64}$" },
          },
          blockers: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["code", "message", "severity"],
              properties: {
                code: { type: "string", minLength: 1, maxLength: 160 },
                message: { type: "string", minLength: 1, maxLength: 2_000 },
                severity: { type: "string", enum: ["blocking", "warning"] },
              },
            },
          },
          recovery: schema("WorkflowPortfolioRecovery"),
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
      },
      WorkflowPortfolioPage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: {
            type: "array",
            items: schema("WorkflowPortfolioEntry"),
          },
          nextCursor: { type: "string", minLength: 1, maxLength: 4_096 },
        },
      },
      Job: {
        type: "object",
        additionalProperties: false,
        description:
          "Asynchronous job status. `failure` is present only for failed or dead-lettered jobs and never contains the persisted raw cause.",
        required: [
          "id",
          "revision",
          "status",
          "attempts",
          "cancellationRequested",
        ],
        properties: {
          id: schema("OpaqueId"),
          revision: schema("Revision"),
          status: {
            type: "string",
            enum: [
              "queued",
              "running",
              "waiting_for_approval",
              "retry_scheduled",
              "cancelling",
              "cancelled",
              "succeeded",
              "succeeded_with_warnings",
              "partially_succeeded",
              "failed",
              "dead_lettered",
            ],
          },
          attempts: { type: "integer", minimum: 0 },
          cancellationRequested: { type: "boolean" },
          failure: schema("JobFailureProblem"),
        },
        allOf: [
          {
            if: {
              properties: { status: { enum: ["failed", "dead_lettered"] } },
              required: ["status"],
            },
            then: { required: ["failure"] },
            else: { not: { required: ["failure"] } },
          },
        ],
      },
      JobFailureProblem: {
        type: "object",
        additionalProperties: false,
        description:
          "Redacted RFC 9457-like asynchronous failure. It intentionally omits HTTP status and request identifiers.",
        required: ["type", "title", "detail", "code", "retryable", "errors"],
        properties: {
          type: { type: "string", format: "uri" },
          title: { type: "string" },
          detail: { type: "string" },
          code: { type: "string", enum: ["job_failed", "job_dead_lettered"] },
          retryable: { type: "boolean" },
          errors: { type: "array", items: schema("ProblemError") },
        },
      },
      Asset: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "mimeType",
          "bytes",
          "sha256",
          "lifecycle",
          "provenance",
        ],
        properties: {
          id: schema("OpaqueId"),
          mimeType: { type: "string", pattern: "^[^/]+/[^/]+$" },
          bytes: { type: "integer", minimum: 0 },
          sha256: { type: "string", pattern: "^[a-f0-9]{64}$" },
          lifecycle: { type: "string" },
          provenance: { type: "string" },
        },
      },
      AssetPage: {
        type: "object", additionalProperties: false, required: ["items"],
        properties: { items: { type: "array", items: schema("Asset") }, nextAfter: { type: "string", minLength: 1, maxLength: 4096 } },
      },
      ApprovalChallenge: {
        type: "object", additionalProperties: false,
        required: ["id", "subjectId", "subjectRevision", "artifactHash", "expiresAt", "consumedAt"],
        properties: { id: schema("OpaqueId"), subjectId: schema("OpaqueId"), subjectRevision: schema("Revision"), artifactHash: { type: "string", pattern: "^[a-f0-9]{64}$" }, expiresAt: { type: "string", format: "date-time" }, consumedAt: { oneOf: [{ type: "string", format: "date-time" }, { type: "null" }] } },
      },
      ValidationResult: {
        type: "object",
        required: ["id", "createdAt"],
        properties: {
          id: schema("OpaqueId"),
          createdAt: { type: "string", format: "date-time" },
          status: { type: "string" },
          code: { type: "string" },
          message: { type: "string", maxLength: 2_000 },
        },
      },
      ValidationPage: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: { type: "array", items: schema("ValidationResult") },
          nextAfter: { type: "string" },
        },
      },
      PublicationArtifactBinding: {
        type: "object",
        additionalProperties: false,
        required: ["assetId", "role", "contentHash"],
        properties: {
          assetId: schema("OpaqueId"),
          role: { type: "string", minLength: 1, maxLength: 160 },
          contentHash: { type: "string", minLength: 1, maxLength: 255 },
        },
      },
      Publication: {
        type: "object",
        additionalProperties: false,
        description:
          "Safe publication state. Execution-only authorization material, actor internals, fences, recovery identity, receipts, and terminal evidence are excluded.",
        required: [
          "id",
          "revision",
          "status",
          "workflowRunId",
          "approvalId",
          "approvalRevision",
          "approvalArtifactHash",
          "assetHash",
          "artifactBindings",
          "channelId",
          "visibility",
          "scheduledAt",
          "playlistIds",
          "createdAt",
          "updatedAt",
        ],
        properties: {
          id: schema("OpaqueId"),
          revision: schema("Revision"),
          status: {
            type: "string",
            enum: [
              "pending",
              "executing",
              "published",
              "failed",
              "reconciliation_required",
              "cancelled",
            ],
          },
          workflowRunId: schema("OpaqueId"),
          approvalId: schema("OpaqueId"),
          approvalRevision: schema("Revision"),
          approvalArtifactHash: {
            type: "string",
            minLength: 1,
            maxLength: 255,
          },
          assetHash: { type: "string", minLength: 1, maxLength: 255 },
          artifactBindings: {
            type: "array",
            items: schema("PublicationArtifactBinding"),
          },
          channelId: schema("OpaqueId"),
          visibility: {
            type: "string",
            enum: ["private", "unlisted", "public"],
          },
          scheduledAt: {
            oneOf: [{ type: "string", format: "date-time" }, { type: "null" }],
          },
          playlistIds: { type: "array", items: schema("OpaqueId") },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
      },
      ApprovalInput: {
        type: "object",
        additionalProperties: false,
        required: [
          "challengeId",
          "subjectId",
          "expectedRevision",
          "decision",
          "reason",
        ],
        properties: {
          challengeId: schema("OpaqueId"),
          subjectId: schema("OpaqueId"),
          expectedRevision: schema("Revision"),
          decision: { type: "string", enum: ["approved", "rejected"] },
          reason: { type: "string", minLength: 1, maxLength: 2_000 },
        },
      },
      ApprovalAccepted: {
        type: "object",
        additionalProperties: false,
        required: ["id", "jobId", "revision"],
        properties: {
          id: schema("OpaqueId"),
          jobId: schema("OpaqueId"),
          revision: schema("Revision"),
        },
      },
      ApprovalRevocationInput: {
        type: "object",
        additionalProperties: false,
        required: ["reason"],
        properties: {
          reason: { type: "string", minLength: 1, maxLength: 2_000 },
        },
      },
      ApprovalRevoked: {
        type: "object",
        additionalProperties: false,
        required: ["id", "revision", "state", "revokedAt"],
        properties: {
          id: schema("OpaqueId"),
          revision: schema("Revision"),
          state: { const: "revoked" },
          revokedAt: { type: "string", format: "date-time" },
        },
      },
      ProblemError: {
        type: "object",
        additionalProperties: false,
        required: ["path", "message"],
        properties: { path: { type: "string" }, message: { type: "string" } },
      },
      Problem: {
        type: "object",
        additionalProperties: false,
        required: [
          "type",
          "title",
          "status",
          "detail",
          "code",
          "requestId",
          "retryable",
          "errors",
        ],
        properties: {
          type: { type: "string", format: "uri" },
          title: { type: "string" },
          status: { type: "integer", minimum: 400, maximum: 599 },
          detail: { type: "string" },
          code: { type: "string", pattern: "^[a-z][a-z0-9_]*$" },
          requestId: { type: "string" },
          retryable: { type: "boolean" },
          errors: { type: "array", items: schema("ProblemError") },
        },
      },
      HealthStatus: {
        type: "object",
        additionalProperties: false,
        required: ["status"],
        properties: {
          status: { type: "string", enum: ["ok", "ready", "unavailable"] },
        },
      },
      OpenApiDocument: { type: "object", additionalProperties: true },
    },
    responses: {
      BadRequest: {
        description: "Request syntax or shape is invalid",
        headers: { "x-request-id": responseHeader("RequestId") },
        content: { "application/problem+json": { schema: schema("Problem") } },
      },
      Unauthorized: {
        description: "Authentication is required",
        headers: { "x-request-id": responseHeader("RequestId") },
        content: { "application/problem+json": { schema: schema("Problem") } },
      },
      Forbidden: {
        description: "Permission is denied",
        headers: { "x-request-id": responseHeader("RequestId") },
        content: { "application/problem+json": { schema: schema("Problem") } },
      },
      NotFound: {
        description: "Resource was not found",
        headers: { "x-request-id": responseHeader("RequestId") },
        content: { "application/problem+json": { schema: schema("Problem") } },
      },
      Conflict: {
        description: "State or idempotency conflict",
        headers: { "x-request-id": responseHeader("RequestId") },
        content: { "application/problem+json": { schema: schema("Problem") } },
      },
      PreconditionFailed: {
        description: "The supplied precondition is stale",
        headers: { "x-request-id": responseHeader("RequestId") },
        content: { "application/problem+json": { schema: schema("Problem") } },
      },
      UnprocessableEntity: {
        description: "Request is semantically invalid",
        headers: { "x-request-id": responseHeader("RequestId") },
        content: { "application/problem+json": { schema: schema("Problem") } },
      },
      PreconditionRequired: {
        description: "A required precondition header is missing",
        headers: { "x-request-id": responseHeader("RequestId") },
        content: { "application/problem+json": { schema: schema("Problem") } },
      },
      TooManyRequests: {
        description: "A quota or rate limit was exceeded",
        headers: { "x-request-id": responseHeader("RequestId") },
        content: { "application/problem+json": { schema: schema("Problem") } },
      },
      Unavailable: {
        description: "A required dependency is unavailable",
        headers: { "x-request-id": responseHeader("RequestId") },
        content: { "application/problem+json": { schema: schema("Problem") } },
      },
    },
  },
};
