import { z } from "zod";

const safeId = z.string().min(1).max(96).regex(/^[a-z0-9][a-z0-9._-]*$/u);
const safePath = z.string().min(1).max(4_096).refine((value) => !value.includes("\0"), "Path contains a NUL byte");
const safeText = z.string().min(1).max(1_000).refine((value) => Array.from(value).every((character) => { const code = character.codePointAt(0) ?? 0; return code === 9 || code === 10 || code === 13 || code >= 32; }), "Unsafe control character");
const finite = z.number().finite();
const range = z.tuple([finite, finite]).refine(([a, b]) => a < b, "Range must increase");
const sha256Schema = z.string().regex(/^[a-f0-9]{64}$/u);
const version = z.literal("1");
const base = { id: safeId, durationMs: z.number().int().min(250).max(300_000), localeSensitivity: z.enum(["language-neutral", "localized", "timing-sensitive"]), narrationCue: z.strictObject({ startMs: z.number().int().nonnegative(), endMs: z.number().int().positive() }).refine((value) => value.startMs < value.endMs).optional() };
const titleSceneSchema = z.strictObject({ ...base, type: z.literal("title"), title: safeText, subtitle: safeText.optional() });
const textSceneSchema = z.strictObject({ ...base, type: z.literal("text"), heading: safeText.optional(), text: safeText, annotation: safeText.optional() });
const equationSceneSchema = z.strictObject({ ...base, type: z.literal("equation"), equation: z.string().min(1).max(300), label: safeText.optional(), highlight: z.string().max(80).optional() });
const equationTransformationSceneSchema = z.strictObject({ ...base, type: z.literal("equation-transformation"), from: z.string().min(1).max(300), to: z.string().min(1).max(300), operation: safeText, highlight: z.string().max(80).optional() });
const graphFunctionSchema = z.strictObject({ expression: z.string().regex(/^[-+]?(?:\d+(?:\.\d+)?)?\*?x(?:[-+]\d+(?:\.\d+)?)?$/u, "Only linear expressions ax+b are supported"), domain: range, color: z.string().regex(/^#[0-9a-fA-F]{6}$/u).optional() });
const coordinateGraphSceneSchema = z.strictObject({ ...base, type: z.literal("coordinate-graph"), xRange: range, yRange: range, functions: z.array(graphFunctionSchema).min(1).max(4), points: z.array(z.strictObject({ x: finite, y: finite, label: safeText.optional() })).max(16).default([]), xLabel: safeText.max(12).optional(), yLabel: safeText.max(12).optional(), annotation: safeText.optional(), expensiveGrid: z.boolean().default(false) });
const geometrySceneSchema = z.strictObject({ ...base, type: z.literal("geometry"), shape: z.enum(["triangle", "rectangle", "circle"]), labels: z.array(safeText.max(40)).max(8).default([]) });
const summarySceneSchema = z.strictObject({ ...base, type: z.literal("summary"), title: safeText, points: z.array(safeText).min(1).max(8) });
export const visualSceneSchema = z.discriminatedUnion("type", [titleSceneSchema, textSceneSchema, equationSceneSchema, equationTransformationSceneSchema, coordinateGraphSceneSchema, geometrySceneSchema, summarySceneSchema]);
export const visualPlanSchema = z.strictObject({ version, lessonId: safeId, locale: z.enum(["de", "en", "es", "fr", "pt"]), title: safeText, scenes: z.array(visualSceneSchema).min(1).max(120) }).superRefine((plan, context) => { const ids = new Set<string>(); for (const [index, scene] of plan.scenes.entries()) { if (ids.has(scene.id)) context.addIssue({ code: "custom", path: ["scenes", index, "id"], message: "Scene IDs must be unique" }); ids.add(scene.id); if (scene.narrationCue && scene.narrationCue.endMs > scene.durationMs) context.addIssue({ code: "custom", path: ["scenes", index, "narrationCue"], message: "Narration cue exceeds scene duration" }); } });
export const profileNameSchema = z.enum(["preview", "draft", "youtube-full", "youtube-short"]);
export const encoderSchema = z.enum(["libx264", "h264_vaapi", "h264_qsv"]);
export const renderProfileInputSchema = z.union([profileNameSchema, z.strictObject({ name: profileNameSchema, frameRate: z.union([z.literal(15), z.literal(24), z.literal(25)]).optional(), encoder: encoderSchema.optional(), preset: z.enum(["ultrafast", "superfast", "veryfast", "faster", "fast"]).optional() })]);
export const audioInputSchema = z.strictObject({ path: safePath, volume: finite.min(0).max(4).default(1) });
export const subtitleInputSchema = z.strictObject({ path: safePath, mode: z.enum(["embedded", "none"]).default("embedded") });
const executionSchema = z.strictObject({ keepTemporaryFiles: z.boolean().optional(), overwrite: z.boolean().optional() });
export const renderRequestSchema = z.strictObject({ requestVersion: version, jobId: safeId, visualPlan: visualPlanSchema, profile: renderProfileInputSchema, outputDirectory: safePath, audio: audioInputSchema.optional(), subtitles: subtitleInputSchema.optional(), execution: executionSchema.optional() });
export const validateRequestSchema = z.strictObject({ requestVersion: version, visualPlan: visualPlanSchema, profile: renderProfileInputSchema });
export const renderSceneRequestSchema = renderRequestSchema.extend({ sceneId: safeId });
export const composeRequestSchema = z.strictObject({ requestVersion: version, jobId: safeId, profile: renderProfileInputSchema, outputDirectory: safePath, scenePaths: z.array(safePath).min(1).max(120), audio: audioInputSchema.optional(), subtitles: subtitleInputSchema.optional(), overwrite: z.boolean().optional() });
export const benchmarkRequestSchema = z.strictObject({ requestVersion: version, fixtureDirectory: safePath, profiles: z.array(profileNameSchema).min(1), encoders: z.array(encoderSchema).min(1).optional(), outputDirectory: safePath });
export const inspectCacheRequestSchema = z.strictObject({ requestVersion: version, cacheKey: sha256Schema.optional() });
export const cleanCacheRequestSchema = z.strictObject({ requestVersion: version, cacheKey: sha256Schema.optional(), corruptOnly: z.boolean().optional() });

export type VisualScene = z.infer<typeof visualSceneSchema>; export type VisualPlanInput = z.infer<typeof visualPlanSchema>; export type RenderProfileInput = z.infer<typeof renderProfileInputSchema>; export type RenderRequest = z.infer<typeof renderRequestSchema>; export type ValidateRequest = z.infer<typeof validateRequestSchema>; export type RenderSceneRequest = z.infer<typeof renderSceneRequestSchema>; export type ComposeRequest = z.infer<typeof composeRequestSchema>; export type BenchmarkRequest = z.infer<typeof benchmarkRequestSchema>; export type InspectCacheRequest = z.infer<typeof inspectCacheRequestSchema>; export type CleanCacheRequest = z.infer<typeof cleanCacheRequestSchema>;
export interface RenderOptions { readonly signal?: AbortSignal; readonly onEvent?: (event: RendererEvent) => void; }

const rendererErrorCodeSchema = z.enum(["INVALID_REQUEST", "INVALID_VISUAL_PLAN", "INVALID_RENDER_PROFILE", "UNSUPPORTED_SCENE_TYPE", "INVALID_FORMULA", "MISSING_ASSET", "MISSING_FONT", "MISSING_TOOL", "UNSUPPORTED_CAPABILITY", "SCENE_RENDER_FAILED", "FFMPEG_FAILED", "FFPROBE_FAILED", "OUTPUT_VALIDATION_FAILED", "OUTPUT_ALREADY_EXISTS", "CACHE_CORRUPTED", "INSUFFICIENT_DISK_SPACE", "PROCESS_TIMEOUT", "PROCESS_INTERRUPTED", "FILESYSTEM_BOUNDARY_VIOLATION", "LOCK_ACQUISITION_FAILED", "INTERNAL_ERROR"]);
const errorSchema = z.strictObject({ code: rendererErrorCodeSchema, message: z.string(), sceneId: safeId.optional(), details: z.record(z.string(), z.union([z.string(), finite, z.boolean(), z.null()])).optional() });
const warningSchema = z.strictObject({ code: z.string(), message: z.string(), sceneId: safeId.optional() });
export const normalizedRenderProfileSchema = z.strictObject({ name: profileNameSchema, width: z.number().int().positive(), height: z.number().int().positive(), frameRate: z.union([z.literal(15), z.literal(24), z.literal(25)]), encoder: encoderSchema, preset: z.enum(["ultrafast", "superfast", "veryfast", "faster", "fast"]), pixelFormat: z.literal("yuv420p") });
const capabilityStatusSchema = z.enum(["available", "unavailable", "untested", "failed-self-test"]); const capabilitySchema = z.strictObject({ status: capabilityStatusSchema, version: z.string().optional(), detail: z.string().optional() });
export const sceneRenderResultSchema = z.strictObject({ resultVersion: version, sceneId: safeId, status: z.enum(["completed", "failed", "cancelled"]), cacheStatus: z.enum(["hit", "miss", "stale", "corrupt", "disabled"]), cacheKey: sha256Schema, outputPath: safePath.optional(), sha256: sha256Schema.optional(), durationMs: finite.nonnegative(), renderDurationMs: finite.nonnegative(), warnings: z.array(warningSchema), errors: z.array(errorSchema) });
const cacheSummarySchema = z.strictObject({ hits: z.number().int().nonnegative(), misses: z.number().int().nonnegative(), stale: z.number().int().nonnegative(), corrupt: z.number().int().nonnegative(), bytesRead: z.number().int().nonnegative() });
const metricsSchema = z.strictObject({ totalDurationMs: finite.nonnegative(), validationDurationMs: finite.nonnegative(), sceneRenderDurationMs: finite.nonnegative(), compositionDurationMs: finite.nonnegative(), ffmpegDurationMs: finite.nonnegative(), renderedFrameCount: z.number().int().nonnegative(), peakTemporaryBytes: z.number().int().nonnegative().optional(), peakRendererProcessRssBytes: z.number().int().nonnegative().optional() });
const mediaOutputSchema = z.strictObject({ videoPath: safePath, manifestPath: safePath, durationMs: finite.nonnegative(), width: z.number().int().positive(), height: z.number().int().positive(), frameRate: finite.positive(), videoCodec: z.string(), audioCodec: z.string().optional(), sha256: sha256Schema });
const capabilitiesSummarySchema = z.strictObject({ ffmpeg: capabilityStatusSchema, ffprobe: capabilityStatusSchema, encoder: z.string() });
export const validationResultSchema = z.strictObject({ resultVersion: version, valid: z.boolean(), warnings: z.array(warningSchema), errors: z.array(errorSchema), normalizedProfile: normalizedRenderProfileSchema.optional() });
export const composeResultSchema = z.strictObject({ resultVersion: version, status: z.enum(["completed", "failed"]), output: mediaOutputSchema.optional(), warnings: z.array(warningSchema), errors: z.array(errorSchema), durationMs: finite.nonnegative() });
export const renderResultSchema = z.strictObject({ resultVersion: version, jobId: safeId, status: z.enum(["completed", "completed-with-warnings", "incomplete", "failed", "cancelled"]), output: mediaOutputSchema.optional(), scenes: z.array(sceneRenderResultSchema), cache: cacheSummarySchema, metrics: metricsSchema, capabilities: capabilitiesSummarySchema, warnings: z.array(warningSchema), errors: z.array(errorSchema) });
export const rendererCapabilitiesSchema = z.strictObject({ resultVersion: version, node: capabilitySchema, ffmpeg: capabilitySchema, ffprobe: capabilitySchema, encoders: z.record(z.string(), capabilitySchema), driDevices: z.array(safePath), fonts: z.array(capabilitySchema), graphviz: capabilitySchema, blender: capabilitySchema, svgRenderer: capabilitySchema, cpuCount: z.number().int().positive(), totalMemoryBytes: z.number().int().nonnegative(), freeSpaceBytes: z.number().int().nonnegative().optional() });
const cacheEntrySchema = z.strictObject({ cacheKey: z.string(), status: z.enum(["hit", "miss", "stale", "corrupt", "disabled"]), bytes: z.number().int().nonnegative(), sceneId: safeId.optional() });
export const cacheInspectionResultSchema = z.strictObject({ resultVersion: version, entries: z.array(cacheEntrySchema), totalBytes: z.number().int().nonnegative() });
export const cleanCacheResultSchema = z.strictObject({ resultVersion: version, removedEntries: z.number().int().nonnegative(), removedBytes: z.number().int().nonnegative() });
const benchmarkRunSchema = z.strictObject({ profile: z.string(), encoder: z.string(), coldDurationMs: finite.nonnegative().optional(), warmDurationMs: finite.nonnegative().optional(), changedOneSceneDurationMs: finite.nonnegative().optional(), audioOnlyCompositionDurationMs: finite.nonnegative().optional(), validationDurationMs: finite.nonnegative().optional(), ffmpegDurationMs: finite.nonnegative().optional(), compositionDurationMs: finite.nonnegative().optional(), sceneDurationsMs: z.record(z.string(), finite.nonnegative()).optional(), renderedFrameCount: z.number().int().nonnegative().optional(), effectiveFrameRate: finite.nonnegative().optional(), cacheHits: z.number().int().nonnegative().optional(), cacheMisses: z.number().int().nonnegative().optional(), cacheHitRate: finite.min(0).max(1).optional(), peakTemporaryBytes: z.number().int().nonnegative().optional(), outputBytes: z.number().int().nonnegative().optional(), peakRendererProcessRssBytes: z.number().int().nonnegative().optional(), status: z.enum(["completed", "failed", "skipped"]), warnings: z.array(z.string()).optional(), failures: z.array(errorSchema).optional() });
export const benchmarkResultSchema = z.strictObject({ resultVersion: version, timestamp: z.iso.datetime(), packageVersion: z.string(), rendererFormatVersion: z.string(), machine: z.strictObject({ cpuCount: z.number().int().positive(), totalMemoryBytes: z.number().int().nonnegative(), nodeVersion: z.string() }), tools: z.strictObject({ ffmpeg: capabilitySchema, ffprobe: capabilitySchema, font: capabilitySchema }), runs: z.array(benchmarkRunSchema) });

export type RendererErrorData = z.infer<typeof errorSchema>; export type RendererWarning = z.infer<typeof warningSchema>; export type CacheStatus = z.infer<typeof sceneRenderResultSchema>["cacheStatus"]; export type SceneRenderResult = z.infer<typeof sceneRenderResultSchema>; export type CacheSummary = z.infer<typeof cacheSummarySchema>; export type RenderMetrics = z.infer<typeof metricsSchema>; export type MediaOutput = z.infer<typeof mediaOutputSchema>; export type RenderResult = z.infer<typeof renderResultSchema>; export type ValidationResult = z.infer<typeof validationResultSchema>; export type ComposeResult = z.infer<typeof composeResultSchema>; export type CapabilityStatus = z.infer<typeof capabilityStatusSchema>; export type Capability = z.infer<typeof capabilitySchema>; export type RendererCapabilities = z.infer<typeof rendererCapabilitiesSchema>; export type RendererCapabilitiesSummary = z.infer<typeof capabilitiesSummarySchema>; export type CacheInspectionResult = z.infer<typeof cacheInspectionResultSchema>; export type CleanCacheResult = z.infer<typeof cleanCacheResultSchema>; export type BenchmarkResult = z.infer<typeof benchmarkResultSchema>; export type NormalizedRenderProfile = z.infer<typeof normalizedRenderProfileSchema>;
export type RendererEvent = { readonly type: "job-started"; readonly jobId: string; readonly timestamp: string } | { readonly type: "scene-started"; readonly jobId: string; readonly sceneId: string; readonly timestamp: string } | { readonly type: "scene-cache-hit"; readonly jobId: string; readonly sceneId: string; readonly cacheKey: string } | { readonly type: "scene-completed"; readonly jobId: string; readonly sceneId: string; readonly durationMs: number } | { readonly type: "scene-failed"; readonly jobId: string; readonly sceneId: string; readonly error: RendererErrorData } | { readonly type: "job-completed"; readonly jobId: string; readonly status: RenderResult["status"] };
