import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import type { EducationalRenderer } from "../api/educational-renderer.js";
import { concatFileContent, composeSegments, encodeStaticScene } from "../composition/ffmpeg.js";
import { renderRequestSchema, visualPlanSchema, type BenchmarkRequest, type BenchmarkResult, type CacheInspectionResult, type CleanCacheRequest, type CleanCacheResult, type ComposeRequest, type ComposeResult, type InspectCacheRequest, type MediaOutput, type NormalizedRenderProfile, type RenderMetrics, type RenderOptions, type RenderRequest, type RenderResult, type RendererCapabilities, type RenderSceneRequest, type SceneRenderResult, type ValidateRequest, type ValidationResult, type VisualScene } from "../contracts.js";
import { SceneCache } from "../domain/cache.js";
import { createSceneCacheKey } from "../domain/cache-key.js";
import { normalizeProfile } from "../domain/profiles.js";
import { RendererError, toRendererErrorData } from "../errors.js";
import { assertNoSymlinkEscape, canonicalJson, fileSize, hashFile, hashText, linkOrCopy, pathExists, resolveContained, writeAtomic, writeJsonAtomic } from "../infrastructure/files.js";
import { inspectCapabilities, probeMedia } from "../infrastructure/media.js";
import { renderSceneSvg, SVG_RENDERER_VERSION, validateFormula } from "../renderers/svg.js";

const PACKAGE_VERSION = "0.1.0"; const RENDERER_FORMAT_VERSION = "educational-video.v1"; const SCENE_SCHEMA_VERSION = "visual-scene.v1"; const THEME_VERSION = "midnight-math.v1"; const DEFAULT_FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf";
export interface EducationalRendererConfiguration { readonly workspaceDirectory: string; readonly cacheDirectory: string; readonly temporaryDirectory: string; readonly ffmpegPath?: string; readonly ffprobePath?: string; readonly fontFile?: string; }
interface SceneContext { readonly request: RenderRequest; readonly profile: NormalizedRenderProfile; readonly scene: VisualScene; readonly outputRoot: string; readonly options: RenderOptions; }

export class EducationalRendererService implements EducationalRenderer {
  private readonly cache: SceneCache; private capabilities?: RendererCapabilities; private fontHash = "";
  private constructor(private readonly config: Required<Pick<EducationalRendererConfiguration, "workspaceDirectory" | "cacheDirectory" | "temporaryDirectory" | "fontFile">>) { this.cache = new SceneCache(config.cacheDirectory); }
  public static async create(input: EducationalRendererConfiguration): Promise<EducationalRendererService> {
    const config = { workspaceDirectory: path.resolve(input.workspaceDirectory), cacheDirectory: path.resolve(input.cacheDirectory), temporaryDirectory: path.resolve(input.temporaryDirectory), fontFile: path.resolve(input.fontFile ?? DEFAULT_FONT) };
    for (const root of [config.workspaceDirectory, config.cacheDirectory, config.temporaryDirectory]) { await assertNoSymlinkEscape(path.dirname(root), root); await fs.mkdir(root, { recursive: true }); }
    if (!(await pathExists(config.fontFile))) throw new RendererError({ code: "MISSING_FONT", message: `Required font file not found: ${config.fontFile}` });
    const service = new EducationalRendererService(config); service.fontHash = await hashFile(config.fontFile); return service;
  }
  private outputRoot(value: string): string { return resolveContained(this.config.workspaceDirectory, value); }
  private sceneKey(scene: VisualScene, profile: NormalizedRenderProfile, locale: string): string { return createSceneCacheKey({ scene, profile, locale, fontHash: this.fontHash }); }
  public async validate(request: ValidateRequest): Promise<ValidationResult> {
    const started = Date.now(); void started;
    try { const visualPlan = visualPlanSchema.parse(request.visualPlan); const profile = normalizeProfile(request.profile); for (const scene of visualPlan.scenes) { if (scene.type === "equation") validateFormula(scene.equation); if (scene.type === "equation-transformation") { validateFormula(scene.from); validateFormula(scene.to); } } return { valid: true, warnings: [], errors: [], normalizedProfile: profile }; }
    catch (error) { const data = toRendererErrorData(error); return { valid: false, warnings: [], errors: [{ ...data, code: data.code === "INTERNAL_ERROR" ? "INVALID_VISUAL_PLAN" : data.code }] }; }
  }
  private async renderSceneInternal(context: SceneContext): Promise<SceneRenderResult> {
    const { request, profile, scene, outputRoot, options } = context; const started = Date.now(); const key = this.sceneKey(scene, profile, request.visualPlan.locale); const outputPath = path.join(outputRoot, "renderer", "scenes", scene.id, "scene.mp4");
    options.onEvent?.({ type: "scene-started", jobId: request.jobId, sceneId: scene.id, timestamp: new Date().toISOString() });
    try {
      let lookup = await this.cache.lookup(key); if (lookup.status === "hit") { await linkOrCopy(lookup.videoPath, outputPath); options.onEvent?.({ type: "scene-cache-hit", jobId: request.jobId, sceneId: scene.id, cacheKey: key }); const result: SceneRenderResult = { resultVersion: "1", sceneId: scene.id, status: "completed", cacheStatus: "hit", cacheKey: key, outputPath, ...(lookup.manifest?.sha256 ? { sha256: lookup.manifest.sha256 } : {}), durationMs: scene.durationMs, renderDurationMs: Date.now()-started, warnings: [], errors: [] }; options.onEvent?.({ type: "scene-completed", jobId: request.jobId, sceneId: scene.id, durationMs: result.renderDurationMs }); return result; }
      const release = await this.cache.acquire(key); try {
        lookup = await this.cache.lookup(key); if (lookup.status === "hit") { await linkOrCopy(lookup.videoPath, outputPath); return { resultVersion: "1", sceneId: scene.id, status: "completed", cacheStatus: "hit", cacheKey: key, outputPath, ...(lookup.manifest?.sha256 ? { sha256: lookup.manifest.sha256 } : {}), durationMs: scene.durationMs, renderDurationMs: Date.now()-started, warnings: [], errors: [] }; }
        const cachePaths = this.cache.paths(key); const svgPath = path.join(this.config.temporaryDirectory, `${key}.svg`); const temporaryVideo = path.join(cachePaths.directory, `.scene.${process.pid}.tmp.mp4`); await writeAtomic(svgPath, renderSceneSvg(scene, profile));
        try { await encodeStaticScene(svgPath, temporaryVideo, scene.durationMs, profile, { ...(options.signal ? { signal: options.signal } : {}) }); const probe = await probeMedia(temporaryVideo); if (probe.width !== profile.width || probe.height !== profile.height || Math.abs(probe.frameRate-profile.frameRate) > 0.01 || Math.abs(probe.durationMs-scene.durationMs) > 100) throw new RendererError({ code: "OUTPUT_VALIDATION_FAILED", message: `Scene ${scene.id} media does not match its profile or duration.`, sceneId: scene.id }); const sha256 = await hashFile(temporaryVideo); const bytes = await fileSize(temporaryVideo); await this.cache.promote(key, temporaryVideo, scene.id, sha256, bytes); await linkOrCopy(cachePaths.video, outputPath); const result: SceneRenderResult = { resultVersion: "1", sceneId: scene.id, status: "completed", cacheStatus: lookup.status === "corrupt" ? "corrupt" : lookup.status === "stale" ? "stale" : "miss", cacheKey: key, outputPath, sha256, durationMs: scene.durationMs, renderDurationMs: Date.now()-started, warnings: [], errors: [] }; options.onEvent?.({ type: "scene-completed", jobId: request.jobId, sceneId: scene.id, durationMs: result.renderDurationMs }); return result; }
        finally { if (!request.execution?.keepTemporaryFiles) await fs.rm(svgPath, { force: true }); await fs.rm(temporaryVideo, { force: true }).catch(() => undefined); }
      } finally { await release(); }
    } catch (error) { const data = { ...toRendererErrorData(error), sceneId: scene.id }; options.onEvent?.({ type: "scene-failed", jobId: request.jobId, sceneId: scene.id, error: data }); return { resultVersion: "1", sceneId: scene.id, status: data.code === "PROCESS_INTERRUPTED" ? "cancelled" : "failed", cacheStatus: "miss", cacheKey: key, durationMs: scene.durationMs, renderDurationMs: Date.now()-started, warnings: [], errors: [data] }; }
  }
  public async renderScene(requestInput: RenderSceneRequest, options: RenderOptions = {}): Promise<SceneRenderResult> {
    const { sceneId, ...base } = requestInput; const request = renderRequestSchema.parse(base); const validation = await this.validate({ requestVersion: "1", visualPlan: request.visualPlan, profile: request.profile }); if (!validation.valid || !validation.normalizedProfile) throw new RendererError(validation.errors[0] ?? { code: "INVALID_VISUAL_PLAN", message: "Visual plan is invalid." }); const scene = request.visualPlan.scenes.find((item) => item.id === sceneId); if (!scene) throw new RendererError({ code: "INVALID_REQUEST", message: `Unknown scene ID: ${sceneId}` }); const outputRoot = this.outputRoot(request.outputDirectory); await assertNoSymlinkEscape(this.config.workspaceDirectory, outputRoot); await fs.mkdir(outputRoot, { recursive: true }); return this.renderSceneInternal({ request, profile: validation.normalizedProfile, scene, outputRoot, options });
  }
  public async compose(request: ComposeRequest): Promise<ComposeResult> {
    const started = Date.now(); try { const profile = normalizeProfile(request.profile); const outputRoot = this.outputRoot(request.outputDirectory); await assertNoSymlinkEscape(this.config.workspaceDirectory, outputRoot); if (request.scenePaths.length === 0) throw new RendererError({ code: "INVALID_REQUEST", message: "Composition requires at least one scene." }); let durationMs = 0; for (const item of request.scenePaths) { resolveContained(this.config.workspaceDirectory, item); const probe = await probeMedia(item); if (probe.width !== profile.width || probe.height !== profile.height || Math.abs(probe.frameRate-profile.frameRate) > .01) throw new RendererError({ code: "OUTPUT_VALIDATION_FAILED", message: `Incompatible scene segment: ${item}` }); durationMs += probe.durationMs; }
      if (request.audio) resolveContained(this.config.workspaceDirectory, request.audio.path); if (request.subtitles) resolveContained(this.config.workspaceDirectory, request.subtitles.path);
      const finalDirectory = path.join(outputRoot, "final"); const rendererTemp = path.join(outputRoot, "renderer", "temporary"); await fs.mkdir(finalDirectory, { recursive: true }); await fs.mkdir(rendererTemp, { recursive: true }); const concatPath = path.join(rendererTemp, "scenes.concat.txt"); await writeAtomic(concatPath, concatFileContent(request.scenePaths)); const videoPath = path.join(finalDirectory, "lesson.mp4"); const temporary = path.join(finalDirectory, `.lesson.${process.pid}.tmp.mp4`); await composeSegments({ scenePaths: request.scenePaths, concatPath, outputPath: temporary, durationMs, profile, ...(request.audio ? { audio: request.audio } : {}), ...(request.subtitles ? { subtitles: request.subtitles } : {}) }); const probe = await probeMedia(temporary); if (probe.width !== profile.width || probe.height !== profile.height || Math.abs(probe.frameRate-profile.frameRate) > .01 || Math.abs(probe.durationMs-durationMs) > 100 || probe.pixelFormat !== "yuv420p" || (request.audio && !probe.audioCodec)) throw new RendererError({ code: "OUTPUT_VALIDATION_FAILED", message: "Final output failed stream verification." }); await fs.rename(temporary, videoPath); const manifestPath = path.join(outputRoot, "manifest.json"); const output: MediaOutput = { videoPath, manifestPath, durationMs: probe.durationMs, width: probe.width, height: probe.height, frameRate: probe.frameRate, videoCodec: probe.videoCodec, ...(probe.audioCodec ? { audioCodec: probe.audioCodec } : {}), sha256: await hashFile(videoPath) }; await writeJsonAtomic(manifestPath, { manifestVersion: "1", jobId: request.jobId, rendererFormatVersion: RENDERER_FORMAT_VERSION, profile, sceneOrder: request.scenePaths, output, status: "completed", deterministicSeed: 0, completedAt: new Date().toISOString() }); return { status: "completed", output, warnings: [], errors: [], durationMs: Date.now()-started };
    } catch (error) { return { status: "failed", warnings: [], errors: [toRendererErrorData(error)], durationMs: Date.now()-started }; }
  }
  public async render(requestInput: RenderRequest, options: RenderOptions = {}): Promise<RenderResult> {
    const started = Date.now(); const validationStarted = Date.now(); let request: RenderRequest; try { request = renderRequestSchema.parse(requestInput); } catch (error) { return this.failedResult(requestInput.jobId, started, Date.now()-validationStarted, error); }
    const validation = await this.validate({ requestVersion: "1", visualPlan: request.visualPlan, profile: request.profile }); const validationDurationMs = Date.now()-validationStarted; if (!validation.valid || !validation.normalizedProfile) return this.failedResult(request.jobId, started, validationDurationMs, new RendererError(validation.errors[0] ?? { code: "INVALID_VISUAL_PLAN", message: "Invalid plan" }));
    const normalizedProfile = validation.normalizedProfile; const outputRoot = this.outputRoot(request.outputDirectory); await assertNoSymlinkEscape(this.config.workspaceDirectory, outputRoot); await fs.mkdir(outputRoot, { recursive: true }); options.onEvent?.({ type: "job-started", jobId: request.jobId, timestamp: new Date().toISOString() }); const scenes: SceneRenderResult[] = [];
    for (const scene of request.visualPlan.scenes) { if (options.signal?.aborted) break; scenes.push(await this.renderSceneInternal({ request, profile: normalizedProfile, scene, outputRoot, options })); }
    const successful = scenes.filter((scene) => scene.status === "completed" && scene.outputPath); let composition: ComposeResult | undefined; if (successful.length === request.visualPlan.scenes.length) composition = await this.compose({ requestVersion: "1", jobId: request.jobId, profile: request.profile, outputDirectory: request.outputDirectory, scenePaths: successful.map((scene) => scene.outputPath as string), ...(request.audio ? { audio: request.audio } : {}), ...(request.subtitles ? { subtitles: request.subtitles } : {}) });
    const errors = [...scenes.flatMap((scene) => scene.errors), ...(composition?.errors ?? [])]; const warnings = [...scenes.flatMap((scene) => scene.warnings), ...(composition?.warnings ?? [])]; const status: RenderResult["status"] = options.signal?.aborted ? "cancelled" : errors.length ? (successful.length ? "incomplete" : "failed") : warnings.length ? "completed-with-warnings" : "completed"; const capabilities = await this.inspectCapabilities(); const sceneRenderDurationMs = scenes.reduce((sum, scene) => sum + scene.renderDurationMs, 0); const metrics: RenderMetrics = { totalDurationMs: Date.now()-started, validationDurationMs, sceneRenderDurationMs, compositionDurationMs: composition?.durationMs ?? 0, ffmpegDurationMs: sceneRenderDurationMs + (composition?.durationMs ?? 0), renderedFrameCount: scenes.filter((scene) => scene.cacheStatus !== "hit" && scene.status === "completed").reduce((sum, scene) => sum + Math.round(scene.durationMs*normalizedProfile.frameRate/1000), 0), temporaryBytesWritten: 0 }; const cache = { hits: scenes.filter((s) => s.cacheStatus === "hit").length, misses: scenes.filter((s) => s.cacheStatus === "miss").length, stale: scenes.filter((s) => s.cacheStatus === "stale").length, corrupt: scenes.filter((s) => s.cacheStatus === "corrupt").length, bytesRead: 0 }; const result: RenderResult = { resultVersion: "1", jobId: request.jobId, status, ...(composition?.output ? { output: composition.output } : {}), scenes, cache, metrics, capabilities: { ffmpeg: capabilities.ffmpeg.status, ffprobe: capabilities.ffprobe.status, encoder: normalizedProfile.encoder }, warnings, errors }; await writeJsonAtomic(path.join(outputRoot, "result.json"), result); if (!composition?.output) await writeJsonAtomic(path.join(outputRoot, "manifest.json"), { manifestVersion: "1", jobId: request.jobId, status, incomplete: true, rendererFormatVersion: RENDERER_FORMAT_VERSION, profile: normalizedProfile, locale: request.visualPlan.locale, sceneOrder: request.visualPlan.scenes.map((scene) => scene.id), scenes, warnings, errors, deterministicSeed: 0, updatedAt: new Date().toISOString() }); options.onEvent?.({ type: "job-completed", jobId: request.jobId, status }); return result;
  }
  private failedResult(jobId: string, started: number, validationDurationMs: number, error: unknown): RenderResult { return { resultVersion: "1", jobId, status: "failed", scenes: [], cache: { hits: 0, misses: 0, stale: 0, corrupt: 0, bytesRead: 0 }, metrics: { totalDurationMs: Date.now()-started, validationDurationMs, sceneRenderDurationMs: 0, compositionDurationMs: 0, ffmpegDurationMs: 0, renderedFrameCount: 0, temporaryBytesWritten: 0 }, capabilities: { ffmpeg: "untested", ffprobe: "untested", encoder: "unknown" }, warnings: [], errors: [toRendererErrorData(error)] }; }
  public async inspectCapabilities(): Promise<RendererCapabilities> { this.capabilities ??= await inspectCapabilities(this.config.workspaceDirectory); return this.capabilities; }
  public async inspectCache(request?: InspectCacheRequest): Promise<CacheInspectionResult> { return this.cache.inspect(request); }
  public async cleanCache(request?: CleanCacheRequest): Promise<CleanCacheResult> { return this.cache.clean(request); }
  public async benchmark(request: BenchmarkRequest): Promise<BenchmarkResult> {
    const fixtureDirectory = resolveContained(this.config.workspaceDirectory, request.fixtureDirectory); const plan = visualPlanSchema.parse(JSON.parse(await fs.readFile(path.join(fixtureDirectory, "visual-plan.json"), "utf8"))); const benchmarkRoot = resolveContained(this.config.workspaceDirectory, request.outputDirectory); await fs.mkdir(benchmarkRoot, { recursive: true }); await fs.rm(path.join(benchmarkRoot, "cache"), { recursive: true, force: true }); const isolated = await EducationalRendererService.create({ workspaceDirectory: this.config.workspaceDirectory, cacheDirectory: path.join(benchmarkRoot, "cache"), temporaryDirectory: path.join(benchmarkRoot, "temporary"), fontFile: this.config.fontFile }); const runs: BenchmarkResult["runs"][number][] = []; const capabilities = await this.inspectCapabilities();
    for (const profile of request.profiles) { for (const encoder of request.encoders ?? ["libx264"]) { if (encoder !== "libx264") { const status = capabilities.encoders[encoder]?.status ?? "unavailable"; if (status !== "available") { runs.push({ profile, encoder, status: "skipped", warnings: [`Optional encoder status: ${status}`] }); continue; } } const outputDirectory = path.join(benchmarkRoot, `${profile}-${encoder}`); const base = { requestVersion: "1", jobId: `benchmark-${profile}-${encoder}`.replaceAll("_", "-"), visualPlan: plan, profile: { name: profile, encoder: encoder as "libx264" }, outputDirectory, audio: { path: path.join(fixtureDirectory, "narration.wav"), volume: 1 }, subtitles: { path: path.join(fixtureDirectory, "subtitles.vtt"), mode: "embedded" } } as const; const cold = await isolated.render(base); const warm = await isolated.render(base); const last = plan.scenes.at(-1); const changedPlan = last?.type === "summary" ? { ...plan, scenes: [...plan.scenes.slice(0, -1), { ...last, title: `${last.title} (Benchmark)` }] } : plan; const changed = await isolated.render({ ...base, jobId: `${base.jobId}-changed`, outputDirectory: `${outputDirectory}-changed`, visualPlan: changedPlan }); const audioOnly = cold.scenes.every((scene) => scene.outputPath) ? await isolated.compose({ requestVersion: "1", jobId: `${base.jobId}-audio`, profile: base.profile, outputDirectory: `${outputDirectory}-audio`, scenePaths: cold.scenes.map((scene) => scene.outputPath as string), audio: base.audio, subtitles: base.subtitles }) : undefined; const failures = [...cold.errors, ...warm.errors, ...changed.errors, ...(audioOnly?.errors ?? [])]; runs.push({ profile, encoder, ...(cold.status === "completed" && warm.status === "completed" && changed.status === "completed" && audioOnly?.status === "completed" ? { coldDurationMs: cold.metrics.totalDurationMs, warmDurationMs: warm.metrics.totalDurationMs, changedOneSceneDurationMs: changed.metrics.totalDurationMs, audioOnlyCompositionDurationMs: audioOnly.durationMs, validationDurationMs: cold.metrics.validationDurationMs, ffmpegDurationMs: cold.metrics.ffmpegDurationMs, compositionDurationMs: cold.metrics.compositionDurationMs, sceneDurationsMs: Object.fromEntries(cold.scenes.map((scene) => [scene.sceneId, scene.renderDurationMs])), renderedFrameCount: cold.metrics.renderedFrameCount, effectiveFrameRate: cold.metrics.sceneRenderDurationMs > 0 ? cold.metrics.renderedFrameCount/(cold.metrics.sceneRenderDurationMs/1000) : 0, cacheHits: warm.cache.hits, cacheMisses: cold.cache.misses, cacheHitRate: warm.scenes.length ? warm.cache.hits/warm.scenes.length : 0, temporaryBytesWritten: cold.metrics.temporaryBytesWritten, outputBytes: cold.output ? await fileSize(cold.output.videoPath) : 0, status: "completed" as const, warnings: ["Peak RSS is not available from the portable process adapter."] } : { status: "failed" as const, failures }) }); } }
    const result: BenchmarkResult = { resultVersion: "1", timestamp: new Date().toISOString(), packageVersion: PACKAGE_VERSION, rendererFormatVersion: RENDERER_FORMAT_VERSION, machine: { cpuCount: os.cpus().length, totalMemoryBytes: os.totalmem(), nodeVersion: process.version }, tools: { ffmpeg: capabilities.ffmpeg, ffprobe: capabilities.ffprobe, font: capabilities.fonts[0] ?? { status: "unavailable" } }, runs }; await writeJsonAtomic(path.join(benchmarkRoot, "benchmark.json"), result); return result;
  }
}
